### ISSUE TITLE
Feature proposal: Can rvm's migrating capabilities help with upgrading?

### ISSUE THREAD

**Issue by marteber** [seek4science/seek#10]
I promise this is the last one for today. :smile:

Is it possible to use e.g. `rvm upgrade 2.1.6 2.1.7` instead of `rvm install 2.1.7`? According to `rvm`'s [documentation](https://rvm.io/rubies/upgrading), that will migrate existing gemsets and environments to the new version, and I actually faced some problems with the environment settings. I guess it perhaps also negates the need to re-install every single gem from scratch with every upgrade?

I would have tested `rvm upgrade` myself but right now I do not feel like tinkering any further with our instance.

**Comment by stuzart** [comment]
I'm doing some work on the docs today so will update with your suggestion.
Sometimes rvm upgrade is not desirable as (we believe) it copies across all gemsets, not just the seek ones. We will double check this, and update the docs pointing out the upgrade option
