### ISSUE TITLE
In Single Page the Paste From Clipboard option does not work if there is an Input attribute

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1007]
**Describe the bug**
The `Paste From Clipboard` button (yellow below) does not work if the dynamic table has a `Input` Attribute (pink below).
The `Input` attribute is of type `Registered Sample (multiple)`.

Moreover, if a User attempts to use the `Paste From Clipboard` and fails, and then manually fills up the (non-refreshed) table, saving will not conclude (for over 10min) and will not display an error message.

**Expected behavior**
The `Paste From Clipboard` works and the dynamic table accepts SEEK Sample names and requests User to confirm the connections after pasting. Or the `Paste From Clipboard` does not paste in the `Input` column and the User has to establish the connections after pasting.

**Screenshots**
![image](https://user-images.githubusercontent.com/77321541/168595789-1de7e546-8490-4d4d-bc66-7c9ff3900edb.png)

**Desktop**
Windows 10 in Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by vdkkia** [comment]
Possible solution: Skip the first column if it is the type of Seek Sample Multi
