### ISSUE TITLE
Creating an issue

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#101]
Using the seek website it is nearly impossible to find the correct way of raising an issue.

When starting here: https://docs.seek4science.org

I go to Contacting us as I wanted to raise an issue

https://docs.seek4science.org/contacting-us.html

Then you go to Reporting Bugs and raising Feature Requests

Then I see

`You can report bugs or request new features using the any of the methods to contact us. `

and this points me back to https://docs.seek4science.org/contacting-us.html

and then you are stuck in an infinite loop... I am not sure if the git is mentioned anywhere...

**Comment by stuzart** [comment]
Thanks. We've only very recently switched over to using github for issues. Previously we used a JIRA that was closed off from public submissions, and the only way to raise an issue was through the mailing lists or contact form. We'll get the docs updated.
