### ISSUE TITLE
Additional metadata properties

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#103]
In SEEK it is as far as I can tell not possible to add additional metadata not covered by the current defined fields. I have mentioned this before in a previous ticket https://github.com/seek4science/seek/issues/20 and I was wondering what the current plan is regarding this? 

The idea is that if you for example have an Amplicon sequencing assay you can for example add the primers as a metadata field such that it is accessible through the API. This would become extremely useful when executing workflows.

**Comment by stuzart** [comment]
This is something we will b  looking at this week, at the ELIXIR Biohackathon, and relates to issue #99

**Comment by stuzart** [comment]
There is a strong overlap between this issue and issue #99 - however there is a subtle difference. I  interpret this as being able to arbitrarily add additional metadata properties to an assay on the fly during creation, whereas #99 requires a particular class of Investigation, Study or Assay to be predefined (or class of extended properties), which are then selected before being then populated and validated .

Hopefully that makes sense, and does this approach also solve this case ?

**Comment by jjkoehorst** [comment]
@stuzart what you are saying is to work according to a defined template in a different section of the seek web interface? and based on that you are working on an amplicon dataset you can have barcodes but if you work with a model you cannot add this metadata? If so, Sounds good to me.

**Comment by alaninmcr** [comment]
I think this can be closed as it is coming in 1.11
