### ISSUE TITLE
tagging teams and spaces, and not just with EDAM!

### ISSUE THREAD

**Issue by CaroleGoble** [seek4science/seek#1037]
there has been discussios  point about tagging everything (including teams and spaces) with open tags and EDAM tags. the limited discussion restricted to EDAM tags. But EDAM is a "Ontology of bioscientific data analysis and data management". 

WorkflowHub is NOT just about biology. It needs to cater for biodiversity, climate change, social sciences, physics, chemistry   - these are all projects that are starting to use it and moreover are contributing to its funding.  

(i) We cannot just restrict tagging to EDAM and (ii) we need tagging on everything - especially teams and spaces as right now we have to look at each Team individually to figure out what they do and we cannot filter on tags

**Comment by stuzart** [comment]
we will address this initially by
[] - removing direct references to EDAM in the UI
[] - removing references to EDAM in the API, e.g. changing `edam_topics `to just `topics`
[] - double check that it is possible for a site admin to edit the Controlled Vocab, including adding new terms even if placeholders not yet from an ontology

we can already manually merge with additional ontologies, one by one or through a script, but I've raised #1044 to make this easier through the UI as it is likely to be a common requirement
