### ISSUE TITLE
feature request: enable CRUD operations on workflows using the REST API

### ISSUE THREAD

**Issue by hmenager** [seek4science/seek#108]
Adding workflow operations to the API would be super nice. Let me know if you need more details!

**Comment by fbacall** [comment]
Hi, we don't have updated API docs for the workflow API yet, but there are some examples in the test code:

Creating:
* Minimum: https://github.com/seek4science/seek/blob/workflow/test/fixtures/files/json/templates/post_min_workflow.json.erb
* Maximum: https://github.com/seek4science/seek/blob/workflow/test/fixtures/files/json/templates/post_max_workflow.json.erb

Updating:
* Minimum: https://github.com/seek4science/seek/blob/workflow/test/fixtures/files/json/templates/patch_min_workflow.json.erb
* Maximum: https://github.com/seek4science/seek/blob/workflow/test/fixtures/files/json/templates/patch_max_workflow.json.erb

Just replace the `<%= ... %>` bits with actual IDs

**Comment by hmenager** [comment]
Indeed, the API already allows this. I was under the impression that the API did not work, but it was actually because the accept header wasn't properly set in this example (https://github.com/seek4science/seekAPIexamples/blob/master/create_local_data_file.py) before. @stuzart has now fixed this.
