### ISSUE TITLE
In the Dynamic Table highlight column of Attribute marked as title

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1089]
The entire column of an Attribute marked as title would be highlighted (all rows of that column).
A blue highlight might be best to not convey wrong messages (e.g. red=wrong, green=correct).

**Comment by rabuono** [comment]
The blue highlight should also appear in the `Experimental overview` table.
This way, all Attributes marked as title will show with the blue highlight and make it easier for the User to distinguish the named Samples in each experimental step being displayed in the table.
![image](https://user-images.githubusercontent.com/77321541/180852464-2707a080-4db1-4c09-9266-f62193e97958.png)

**Comment by floradanna** [comment]
I noticed that "title" column is highlighted only in sources/samples table, but not in Experiment overview table. Can "title" columns be highlighted in Experiment overview tables?
