### ISSUE TITLE
In the dynamic table clarify Sample ID

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1092]
Currently the Sample IDs are shown under a `id` column, in both dynamic table and exported CSV.
Would be clearer if it was named `[instance name] id`
For example: `DataHub id`

~~In all tables would be clearer to have the `DataHub id` immediately on the right side of the Attribute marked as title for that Sample Type.~~

~~The `DataHub id` columns should be highlighted in the same way as described in issue #1089~~

**Comment by vdkkia** [comment]
The id columns come after the first column (the select column with the checkbox) and changing its position will break the Dynamic Table logic. So, the only way to have the title and the id columns next to each other is to add the title as the first attribute upon **sample_type** creation.

**Comment by rabuono** [comment]
@vdkkia Where is the `FAIRDOM-SEEK` text taken from? Is it hard coded?
![image](https://user-images.githubusercontent.com/77321541/180857085-13835725-2fa6-4a0c-b338-0fc3ba9b30f4.png)


I can't seem to make it change by changing the name of the instance in server admin > branding and customization > Name
![image](https://user-images.githubusercontent.com/77321541/180857193-9c85286b-fa11-486b-a616-3ae73b09f23f.png)

**Comment by stuzart** [comment]
FAIRDOM-SEEK is probably the `application_name` and is fixed to source code. Here you probably want to use `instance_name` instead

**Comment by vdkkia** [comment]
@stuzart the `instance_name` is being used [here](https://github.com/seek4science/seek/blob/b473cba256933b306f7a570008e0be010c6a9535/app/assets/javascripts/single_page/dynamic_table.js.erb#L2). 
`rake tmp:cache:clear` did the trick to update it.
