### ISSUE TITLE
Change CSV and Export as CSV to Export table

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1099]
A few tables can now be exported as csv files. This is generally done by clicking on one of the following:
![image](https://user-images.githubusercontent.com/77321541/179252772-2dc7bc7d-4937-4b7d-a2c9-1cd5e35557d1.png)
![image](https://user-images.githubusercontent.com/77321541/179252825-60b528eb-65ec-4c34-82ef-9693ac7cf578.png)

These are on top of the dynamic table when input our showing Samples in Single Page view, on top of the Samples view mentioned on issue #594 and on top of the results of the Sample Query feature mentioned on issue #1048 

 It might be clearer for Users if the button says `Export table` instead.

**Comment by rabuono** [comment]
Still showing as just `CSV` for me
![image](https://user-images.githubusercontent.com/77321541/180859287-ded2fe7b-db12-464b-abe3-dfef5cf1d0dd.png)

Or not at all:
![image](https://user-images.githubusercontent.com/77321541/180859523-c8ae0cbd-d8fa-436f-be99-440776c98097.png)

**Comment by vdkkia** [comment]
This issue is fixed and is used in a different branch than the Dev server.
