### ISSUE TITLE
Paste from Clipboard doesn't work in Safari

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1105]
**Describe the bug**
The feature "Paste from Clipboard" in SP dynamic table doesn't work in Safari. Clicking the button doesn't give any response.

**To Reproduce**
1. Go to SP dynamic table
2. Copy tabular data from excel
3. Click on "Paste from Clipboard"

**Expected behavior**
Paste text into dynamic table

**Screenshots**
![Screenshot 2022-07-19 at 11 44 45](https://user-images.githubusercontent.com/51486716/179720835-04db0975-3071-49ed-bb5a-8b2bc8d7a8ee.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari. It works on Chrome.
 - Version

**Comment by vdkkia** [comment]
As the console errors imply, you haven't allowed the action (paste from clipboard) to be done in the browser.
You can mark the action as allowed in the website permissions

**Comment by floradanna** [comment]
Find out what could block this feature in Safari and link info for solving the problem for the user.

**Comment by floradanna** [comment]
It works now in Safari 16.6 in MacOS Ventura Version 13.5.1

**Comment by kdp-cloud** [comment]
It should work in Safari version 13.1 or higher.
