### ISSUE TITLE
Deletion of SOP when linked to DataHub Study

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1106]
**Describe the bug**
In DataHub, Study must have 1 SOP. However, a user can delete an SOP even if it is already associated with a Study in DataHub (Single Page) and this affect the visualisation of tables in the tree view (see screenshot) and the ISA json export.

**To Reproduce**
1. Go to 'In SP, Design Study -> add SOP file --> save Create Study'
2. Click on  'My items -> SOP-> delete SOP'

**Expected behavior**
Since in SEEK a user must delete SOP and other linked assets to be able to delete Assays, Study, etc, we probably have no choice but to allow `0 or 1` SOP associated with Study (the same apply to SP Assays). This means changing the rule used in DataHub so far.

1. Go to 'In SP, Design Study -> add SOP file --> save Create Study'
2. Click on  'My items -> SOP-> delete SOP'. 
3. Message: "Warning: This SOP is associated to one or more existing Studies or Assays. Associate an SOP before exporting ISA.
4. In SP, Protocol TAB should show the following warning message, if there is no Protocol linked: "Warning: A Protocol is missing. Associate a Protocol before exporting ISA.  

**Screenshots**
![Screenshot 2022-07-19 at 12 31 13](https://user-images.githubusercontent.com/51486716/179745592-027ddb5b-bd1b-42bd-9e61-4103d86c3ff2.png)

![Screenshot 2022-07-19 at 12 31 03](https://user-images.githubusercontent.com/51486716/179745606-2d6b9d99-e767-4056-a586-d9ca20e6cf2d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by floradanna** [comment]
In DataHub, currently there is no possibility to link an SOP to a DataHub Study after the Study has been created. Probably, the `Actions --> Edit Study` in SP needs to show the same window shown during "Design Study" instead of the window shown in SEEK by default.

In other words, currently we show a GUI for Design Study and another GUI (with different options) for Edit Study. We should work on aligning this mismatch.

**Comment by vdkkia** [comment]
I added a new issue for editing ISA Study and Assay here #1111

**Comment by floradanna** [comment]
> In DataHub, currently there is no possibility to link an SOP to a DataHub Study after the Study has been created. Probably, the Actions --> Edit Study in SP needs to show the same window shown during "Design Study" instead of the window shown in SEEK by default.

This is done, however the possibility to Edit SOP needs to be added to the Edit Study GUI (same for Assay).

**Comment by floradanna** [comment]
The first issue about mandatory or optional SOP in Study needs to be solved: https://github.com/seek4science/seek/issues/1106#issue-1309423640.

Issue reopened to fix this.

**Comment by floradanna** [comment]
This is actually a much bigger issue with larger consequences and link to default view. It must be addressed differently.
