### ISSUE TITLE
determine_custom_metadata_keys in ApplicationController

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#1114]
There are two, almost duplicate, determine_custom_metadata_keys methods in ApplicationController. One at line 558 and one at 602. The second one is the one that is called.

The first one should probably be deleted

**Comment by stuzart** [comment]
yes the first one on 558 can just be removed

**Comment by alaninmcr** [comment]
I've included this in the custom_metadata branch

**Comment by stuzart** [comment]
don't mix things up with the experimental api changes. the current changes are wrong
