### ISSUE TITLE
Show the last person that edits something

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1134]
Show who last triggered an update action on an item ( can be fetched from the activity logs ).

Should show this in the activity box: 
![image](https://user-images.githubusercontent.com/201658/181574812-51c32043-255a-45f9-aecb-933d5c683c1f.png)

Some items such as people and projects do not display activity, so perhaps for these the information isn't necessary ?

Only display to members of the same project as the item

**Comment by floradanna** [comment]
> Should show this in the activity box:

Yes, it seems appropriate.

> Some items such as people and projects do not display activity, so perhaps for these the information isn't necessary ?

Indeed, it sounds reasonable.

> Only display to members of the same project as the item

I don't have an answer for that. It is not a technical issue, but rather defining policy for SEEK. Maybe it is worth it to bring it up during FAIRDOM Club meeting. I will try to see what similar software do about this to make a more informed decision.
The minimal info to show would be info currently shown plus:
- last updated by you (logged in user): xxx (in addition to last updated:xxx)
- last used by you (logged in user): xxx (in addition to last used:xxx)

Some considerations to show version history (with or without names)
