### ISSUE TITLE
Inconsistency between Study-SOP and Assay-SOP in Single Page advanced

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1137]
In Single Page, the selection of the Study  _SOP item in the tree view_ or of the _Protocol sub-tab_ of **Study** design tab both give the information about SOP, as shown in the screenshot below.
<img width="643" alt="Screenshot 2022-07-29 at 16 40 22" src="https://user-images.githubusercontent.com/51486716/181784024-6f106ca5-0a47-4d88-b686-8803547fa948.png">

In Single Page, the selection of the _Protocol sub-tab_ of **Assay** design tab (screenshot below) gives the information about SOP as for Study SOP (compare with screenshot above).
<img width="557" alt="Screenshot 2022-07-29 at 16 40 34" src="https://user-images.githubusercontent.com/51486716/181784055-d1f6fe62-bb0a-4c88-87a9-d219f287e9df.png">

In Single Page, the selection of the Assay _SOP item in the tree view_ under **Assay** gives DIFFERENT types of information about the same SOP (see screenshot below). Selecting SOP in this way, it shows:
- Related Items
- Creators, Licence, Activities etc as rectangles on the right side of the page.

This is not shown for STUDY SOP.
<img width="644" alt="Screenshot 2022-07-29 at 16 40 47" src="https://user-images.githubusercontent.com/51486716/181784096-d778aeac-661f-4f01-ae2a-894805975abf.png">

**Comment by floradanna** [comment]
How can we harmonise these information? To be discussed

**Comment by vdkkia** [comment]
This issue is solved since all the Sop items will load the same page after applying harmonization of the ISA items in the tree view.

**Comment by vdkkia** [comment]
This issue is solved since all the Sop items will load the same page after applying harmonization of the ISA items in the tree view.
