### ISSUE TITLE
Feature request: Licenses

### ISSUE THREAD

**Issue by zagorGit** [seek4science/seek#114]
Proposal: add more optional opensource licenses, e.g. MIT, GPLv3, ...listed in [https://opensource.org/licenses](https://opensource.org/licenses) -- browser drop-down and API supported; also enabled for Snapshots

**Comment by alaninmcr** [comment]
I agree. There has been discussion of allowing https://spdx.org/licenses/

One related issue would be that some of the licenses are parameterized e.g. MIT and BSD are parameterized by year and copyright holder. Need to find a solution for that. I should probably raise a new issue :-)

**Comment by mr-c** [comment]
+1 for using the SPDX license identifiers
