### ISSUE TITLE
Remove all the default project folders

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#1141]
Since the users can freely create `project folders` and due to the fact that newly created assets will go to the **Unsorted** folder, it's best to remove all the `project default folders` to prevent confusion.

**Comment by floradanna** [comment]
all except the "Unsorted items" folder, of course.

**Comment by floradanna** [comment]
@vdkkia 
I think the folder "Project items" needs to stay also, because it is needed for users to be able to create their folders, correct?
All subfolders should be removed.

**Comment by vdkkia** [comment]
Yes, the Projects item and the Unsorted item folders are remaining.
