### ISSUE TITLE
404 error when trying to view all search results for a type

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#1144]
Also happens when filtering for with a search query.

Seems to be because there are IDs in the solr index that do not exist in the database, so `find` throws an exception.

**Comment by alaninmcr** [comment]
Do you know what they are IDs of? Is it just random things or a particular class? I'm wondering because of batch sample extraction.

**Comment by fbacall** [comment]
> Do you know what they are IDs of? Is it just random things or a particular class? I'm wondering because of batch sample extraction.

Not sure
