### ISSUE TITLE
wrong statistics 

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1153]
statistics on dashboard page look wrong : e.g dashboard for PoLiMeR project  https://fairdomhub.org/projects/130/stats/dashboard  shows in "most active submitters" Hong Yang with 42 (assets?)   but this user has only 12  related items:  1 investigation, 1 study and 2 assays  + 3 data files + 2 publications + 3 presentations. How can this be?

**Comment by OlgaKrebs** [comment]
![Submitter42](https://user-images.githubusercontent.com/55085007/185146303-e4a75a73-a6f0-4a21-a805-d41f52ec9575.jpg)

**Comment by OlgaKrebs** [comment]
at the same time, Karen van Eunen is shown with 36 submitted assets, but she has >100 ( 79 documents only)

**Comment by OlgaKrebs** [comment]
seems general problem - on https://fairdomhub.org/projects/99/stats/dashboard  Petra shown submitted 42 assets and she has about 180

**Comment by stuzart** [comment]
@OlgaKrebs - in the bottom right, there is a refresh button. If you click that to refresh, do the figures look more sensible, at least Karen's count ?

**Comment by stuzart** [comment]
The wording used to be "Most active contributors" and includes creation and updates in the stats, which count as contributions. Need to either change the wording or the behaviour to only include creation events

**Comment by stuzart** [comment]
agreement to change to only show creation events, and keep the current title
