### ISSUE TITLE
Hide sample types generated via single page from default view

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1172]
Hide sample types created via Single Page from default view, when Single Page advanced in enabled.

Deal with “hiding” Sample Type created via SP from default view in:
* Browse->Sample Type
* Browse->Samples
* Sample
* Search results
* Related items
* Dropdown menu listing sample types when 
  * linking samples to assay
  * select sample type in Registered Sample(s) attribute type
* ...

Same changes need to be applied to API

**Comment by floradanna** [comment]
@stuzart @fbacall 

In DataHub, we need to restrict the use of sample type to the single related Study or Assay. What do you think of this issue? Is the proposed solution feasible in a way that doesn't break anything in the code and that it is safe/coherent?

**Comment by floradanna** [comment]
Is it worth it to apply extra rules to avoid unexpected behaviours? Such as:
- in the backend, applying the sharing permissions of the related Assay/Study to the sample type
- in dynamic table, only show samples linked to the study/assay via Single Page

**Comment by rabuono** [comment]
These extra rules seem reasonable to me. A couple of new features seem needed to enforce them

**Comment by rabuono** [comment]
The sharing permissions portion below relates to issue #1199 

> Is it worth it to apply extra rules to avoid unexpected behaviours? Such as:
> 
> * in the backend, applying the sharing permissions of the related Assay/Study to the sample type
> * in dynamic table, only show samples linked to the study/assay via Single Page
