### ISSUE TITLE
Feature request: Select all and recursive selection for item checkbox selection in the publishing procedure

### ISSUE THREAD

**Issue by markopetek** [seek4science/seek#1177]
When publishing investigations or studies that include many items (in my case one had more than 1000 items) it is very impractical to click checkboxes for each item. Therefore, I kindly ask kindly that you implement a "Select all" or "Check all" button at the selection stage and, if possible, make selections hierarchically recursive, i.e. if you select one study, all elements (assays, data files, documents etc) linked to it will be selected if you have publishing credentials.

For the time being, I found a browser developer console-based workaround for the "Select all" functionality that might be useful for some other users. Find the description here:
https://ma.ttias.be/selecting-all-checkboxes-developer-console/

**Comment by stuzart** [comment]
thanks, we will take a look. It seems like a straightforward improvement.
