### ISSUE TITLE
Download link URL to MIAPPE template is missing the relative sub-URI if used 

### ISSUE THREAD

**Issue by jos4uke** [seek4science/seek#1185]
Hi

I recently installed my own instance of fairdom seek using the sub-URI protocol (with RAILS_RELATIVE_URL_ROOT=/seek). 
And on the new study creation page, clicking the download link to MIAPPE template archive ends up with a 404 error.
The download link is missing the sub-URI part.
Adding the sub-URI fixed the URL and I was able to download the template.
    
Is it possible to fix this by ourselves?
  
Thanks in advance.

Joseph

**Comment by jos4uke** [comment]
And also the zip filename has a typo: "MIAPPE Sudy batch template.zip" instead of "MIAPPE Study batch template.zip"

wrong_URL="http://server_name/batch_upload_template/MIAPPE%20Sudy%20batch%20template.zip"  
  
good_URL="http://server_name/seek/batch_upload_template/MIAPPE%20Sudy%20batch%20template.zip"

**Comment by fbacall** [comment]
Thanks for reporting this @jos4uke 

This will be fixed in the 1.13 release
