### ISSUE TITLE
Request: oauth / ldap for seek api

### ISSUE THREAD

**Issue by CFGrote** [seek4science/seek#119]
Hi SEEK developers!
Thanks for your great work!

Our users log into SEEK with their institutional LDAP account. Currently, they cannot use the SEEK API to create new Projects/Samples/... and only browse the public assets. We have a few use cases where this option would be required and we do not want to have two accounts per person (LDAP and local). So can API-via-LDAP be enabled? 

Thanks, Carsten

**Comment by fbacall** [comment]
Hi!

This commit https://github.com/seek4science/seek/commit/d118b104a0283357947e566703276c0f681aa767 adds support for users to create OAuth applications, or generate API tokens for accessing the API regardless of how they authenticate with SEEK.

Documentation to follow soon.
