### ISSUE TITLE
Display Sample Type creator/submitter and creation date

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1198]
As a User I would like to see who created a Sample Type and when it was created so that I can contact this person to: ask for instructions, ask for changes to the Sample Type.

Outcome of Samples WG and part of discussion #1118

**Comment by stuzart** [comment]
I think this should be quite straight forward, so added to the 1.13.1 milestone (it might even make 1.13.0)

**Comment by rabuono** [comment]
Add the ability to define independent Creator and Submitter to a Sample Type

**Comment by stuzart** [comment]
Following testing this at https://testing.sysmo-db.org - it works but some additional refinements are needed:

- [ ] Include filtering by submitter on the index page
- [ ] Display the submitter icon on the resource list view ( e.g. avatar on the left of the items https://testing.sysmo-db.org/sops )
- [ ] Upgrade task to set the creator to the submitter for sample types before this change
