### ISSUE TITLE
Add sharing permissions to Sample Type

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1199]
As a User I would like to attribute different levels of permission to a Sample Type so that different members of my team can view, edit, or manage it.
Sample Type sharing permissions are independent of Samples sharing permissions.

Outcome of Samples WG and part of discussion #1118

**Comment by rabuono** [comment]
Based on Samples WG discussion
Add sharing permission to sample type, as for every other item:
- Retrospectively, it will be set to follow project default permission
- Not an optional feature to be on/off from admin pane

**Comment by floradanna** [comment]
Important: Process for editing a sample type that has a linked datafile

Same process as described for the editing of samples (#1357)

Process:

- the user goes to "edit sample type",
- if sample type has a linked datafile, SEEK shows a warning "Sample type has been created from a datafile, editing this sample will make the datafile not valid anymore for this sample type" or something.
- if user continue editing, the datafile link for that sample type will gain the label "not valid anymore" or something

**Comment by floradanna** [comment]
Scenario to be analysed: https://github.com/seek4science/seek/discussions/1118#discussioncomment-6751522
