### ISSUE TITLE
creating new SampleType 

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1215]
get an error I can't understand

1 error prohibited this sample type from being saved
There were problems with the following fields:

Sample attributes sample controlled vocab Linked Sample Type must be set if attribute type is SeekSample

**Comment by floradanna** [comment]
Maybe the reason could be that there is no Sample Type specified under "Registered Sample". I highlighted in red in the image below.

![198036170-7a7bb18e-c7cc-47c3-a1aa-07443b523b30](https://user-images.githubusercontent.com/51486716/198039803-e67b79e0-7e22-44ba-ac11-73b86c0eddaa.jpg)

**Comment by OlgaKrebs** [comment]
yes, thanks Flora - I already realised this: it asks for sampletype of the "parent"-Sample. But error message " controlled vocab Linked Sample Type must be set if attribute type is SeekSample" is very unclear. It shuld ask "choose sampletype for linked sample" or similar

**Comment by vdkkia** [comment]
Clarify empty Linked Sample Type error message https://github.com/seek4science/seek/commit/1e740abd4ac3f09882fb48a0879e92bfc7d3f8d2
