### ISSUE TITLE
Source vs Sample template - the difference is not clear

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1225]
Users do not notice the difference between Source and Sample template when designing a Study in DataHub. Mostly, because it is allowed to select Source and Sample templates multiple times, although this cause error. Moreover, the resulting error message is not clear (it should be something like, "Wrong templates selection. Select Source template first, and Sample collection template after that").

I would suggest to only show and allow Source templates in the first dropdown list, and only Sample templates in the second dropdown list.

**Comment by rabuono** [comment]
Relaying from meeting discussions:
Refining the filtering of displayed Templates when prompting user to choose the Templates might be a nice way to tackle this. This is the “level” in the Template metadata. Substitute “Study” with “Study Source” and “Study Sample”.
It will be important to make sure to add this to the validation of Templates when uploading new Templates.

**Comment by kdp-cloud** [comment]
After discussion with @floradanna and @rabuono of whether to keep the grayed-out option in the selection box, we decided to remove it from the list.
![image](https://user-images.githubusercontent.com/82407142/222463430-9b7ae45c-3da4-44fa-bca4-d62869feda1a.png)

**Comment by floradanna** [comment]
**When Design Assay via Single Page:**
keep the “Assay” selected by default, but remove the "not selected" option from the dropdown; users should not be able to select anything else beside Assay.

Keeping the "type = Assay" visible can give the user a reminder of what the template is about.

**When Design Study via Single Page:**
keep the “Study source” or "Study sample" selected by default, but remove the "not selected" option from the dropdown; users should not be able to select anything else beside "Study source" and "Study sample". Otherwise they will get errors.

Keeping the "type = Study source" or "type = Study sample" visible can give the user a reminder of what the template is about.
