### ISSUE TITLE
Delete project has wrong url

### ISSUE THREAD

**Issue by d3j906** [seek4science/seek#1231]
When I create and then attempt to delete a test project, the delete url comes back as: http://[127.0.0.1](http://127.0.0.1:3000/projects/7?return_to=%2Fpeople%2F53%2Fitems):3000/projects/7?return_to=%2Fpeople%2F53%2Fitems

**To Reproduce**
1. Go to my-items (on https://emsl-seek.pnnl.gov)
2. Click on test project4
3. Click on actions and select "delete" 
4. A pop-up message indicates any member will also be deleted - are you sure. Click yes.
5. Invalid url is displayed for 127.0.0.1:3000
6. I can replace the 127.0.0.1:3000 with the emsl-seek.pnnl.gov domain name on https and the project gets deleted.
7. See error (127.0.0.1 refused to connect).

**Expected behavior**
The project would be deleted and no url with 127.0.0.1:3000 would be presented.

 - Client OS: Windows 10
 - Browser Chrome/Edge
 - Version  106.0.5249.119/107.0.1418.26

**Additional context**
Using a docker-compose deployment and originally discovered the issue on 1.12.1. Updated to 1.12.2 and I'm still seeing the issue

**Comment by stuzart** [comment]
Thanks for reporting this. I've not been able to reproduce it on our test instance, but that is running a later pre-release version and it's possible it has been fixed as a side effect of other fixes - we've done a lot relates to paths and handling sub-uris so it could have been fixed as part of that.
However, I will take a further look into it to check there is nothing suspicious about that particular action, recent code changes, and whether it may rely on a particular configuration.

**Comment by stuzart** [comment]
I've not found anything particular to projects that would cause this problem, and not been able to reproduce it. Does it only happen for projects, or also other items deleted via the "My Items" page ?

A possible cause is that the host isn't being passed through to the backend docker deployment from the front end proxy. 
If using nginx, does your server define the `proxy_set_header` for the Host?

e.g

> location / {
>         proxy_set_header   X-Real-IP $remote_addr;
>         proxy_set_header   Host      $host;
>         proxy_set_header   X-Forwarded-Proto $scheme;
>         proxy_pass         http://192.168.10.10:3000;
>     }
>

**Comment by d3j906** [comment]
Thanks Stuart,

And I'm using apche and did not have UseCanonicalName and ProxyPreserveHost on. Thanks for the hint and this has resolved my issue.

UseCanonicalName on
ProxyPreserveHost on
<Location />
     ProxyPass   http://127.0.0.1:3000/ Keepalive=On
     ProxyPassReverse http://127.0.0.1:3000/
</Location>

**Comment by stuzart** [comment]
re-opened, as the documentation still needs updating to describe this for Apache as well as nginx
