### ISSUE TITLE
no creator by default if creating asset

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1237]
I have created few ISA elements today and saw afterwards that I am not listed as creator (only as submitter) as it has been before ... is it a bug? or have we changed this?  e.g. https://fairdomhub.org/assays/2017

**Comment by OlgaKrebs** [comment]
![creatorPerson2](https://user-images.githubusercontent.com/55085007/199969970-e1a7e842-ab45-42a9-aa2e-06fc07c977c6.jpg)
browsing for assays (fliter fr POLIMER project) I see few assays without creator

**Comment by floradanna** [comment]
I am also a bit confused about how Creator and Submitter work for each item. For instance,
- Bob creates an Investigation --> Creator = Bob, Submitter = Bob
- Bob creates a Study --> Creator = not specified; Submitter = Bob
(same for Assay and Sample)

@vdkkia is it only a datahub.test problem? or a seek problem?

<img width="1021" alt="Screenshot 2022-11-07 at 14 02 46" src="https://user-images.githubusercontent.com/51486716/200317133-6200243a-a5c1-4c52-b46b-bfbb73e1fbc0.png">
<img width="1017" alt="Screenshot 2022-11-07 at 14 03 45" src="https://user-images.githubusercontent.com/51486716/200317301-5f33bc58-6e08-4f0a-98a7-8644ee84035e.png">

**Comment by stuzart** [comment]
it should default to the creator being the same as the submitter for all cases. The user can change this or remove it, but it should be there as the default. For me it does for Investigation, Study and Assay when created through the normal forms
