### ISSUE TITLE
Renamed input does not get updated in dynamic table

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1240]
**Describe the bug**
When renaming a "source" or "sample" or "extract" etc... the new name does not appear under the attribute type Registered Samples where the source/sample/extract etc is used. The old name is still shown and there is no error message.

**To Reproduce**
in DataHub test, Single page, dynamic table:
- create a Source (Source Name)
- Use Source Name as input for a Sample (give a Sample Name)
- Use Sample Name as input for an Assay and save
- Go back to Sample Name and change it into a new name and save
- Go to the Assay: in Input attribute the OLD Sample Name will be still visible with no error.

**Expected behavior**
If a SEEK sample is renamed, the new name should automatically be updated everywhere in SEEK.

**Comment by rabuono** [comment]
Removing datahub tag since this seems to be a general SEEK issue.
