### ISSUE TITLE
Gatekeeper function cause issues with sharing permission

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1242]
**Describe the bug**
The project has a gatekeeper, but when a project member makes an item public there is no message about "waiting for gatekeeper's approval". It looks like making the item public worked, but it actually didn't work and there is no way to understand why.

**To Reproduce**
Steps to reproduce the behaviour:
1. datahub test 
3. In a project with gatekeeper, make an item visible for public and save
4. check again the sharing permission that you have just changed

**Expected behavior**
- A message saying "the items will be public after gatekeeper's approval"
- Other changes made in sharing permission (that do not involve the gatekeeper) should be applied immediately
- A notification to the gatekeeper about "new request"

**Comment by fherreazcue** [comment]
The "manage" action was not included in the actions that triggered a publishing log.
This is addressed in [this commit](https://github.com/seek4science/seek/commit/24ff150c23c52cc5ce01344986da1c628cd574b8).
