### ISSUE TITLE
Generate Sitemap for list of public content

### ISSUE THREAD

**Issue by stain** [seek4science/seek#1250]
**Describe the bug**
Programmatic clients such as search engines and FAIR clients have no way to iterate all the content of WorkflowHub or to see when some of the assets may have been updated since last visit.

**Additional context**

[Sitemaps](https://www.sitemaps.org/protocol.html) is a method promoted by search engines that simply list pages and their last modification date. It is possible to have nested sitemaps, e.g. TeSS does it like this https://tess.elixir-europe.org/sitemap.xml per asset type + other pages.

**Other alternatives**

* Each asset collection page e.g. https://workflowhub.eu/workflows could use a schema.org type like https://workflowhub.eu/workflows -- unsure how they will be listed under https://workflowhub.eu/
* [OAI-PMH](https://www.openarchives.org/pmh/) is a classic used by harvesters like OpenAIRE and exposed by repositories like Zenodo
* [SWORD v3](https://sword.cottagelabs.com/swordv3/) is a modern alternative to the above that supports metadata and write operations. 
* .. I'm sure there are many more

**Comment by fbacall** [comment]
https://github.com/lassebunk/dynamic_sitemaps is the gem used in TeSS

**Comment by stain** [comment]
There's also Signposting relations for `collection` which in this case should be within a Linkset document as it would be a big list. This should be very easy to generate as it only needs the URIs and no further metadata.

https://signposting.org/FAIR/
