### ISSUE TITLE
Allow editing of Attributes in existing Sample Types

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1258]
As discussed in the Samples WG.

For existing Sample Types. Allow for edits that do not lead to validation conflicts with existing Samples.
Allow the following changes:
- An Attribute from required to optional
- The Attribute tagged as Title
- Attribute Name
- Attribute PID
- Attribute Description
- Attribute Unit

**Comment by NielsGeudens** [comment]
For existing ISA Sample Types, I can make the following changes to existing attributes:
- Attribute Name
- Attribute PID
- Attribute Description
- Attribute Unit

However, I cannot change: 
- An Attribute from required to optional
- The Attribute tagged as Title

**Comment by stuzart** [comment]
I'd used this as part of the 1.16.0 release notes, so I've removed that bit of text until it's been clarified - https://github.com/seek4science/seek-documentation/commit/f9df019e60de99495e1b7eb93dca7efbfa4d6873

**Comment by kdp-cloud** [comment]
@NielsGeudens
The changes made for Sample Types did not include the ISA-JSON compliant Sample Types. The idea was to implement it later when it was properly tested for regular Sample Types. In a regular Sample Type you are able to change the title and required attributes, even with samples in it (Just tested it in our test instance).

Explanation why you couldn't do it for ISA-studies / ISA-assays:
An ISA-JSON compliant sample type is derived from an Experiment Sample Template, meaning that the attributes in the Sample Type are 'inherited' from the Template. There is a validation rule that prevents changing the 'required' status of the attribute if it is inherited. If you need to be able to change the required / title attribute, I'd have to remove 1 line of code:
https://github.com/seek4science/seek/blob/ed0d6bdb4ff7fb26280188ee13098ff45726b26f/lib/seek/samples/sample_type_editing_constraints.rb#L25
