### ISSUE TITLE
Projects can't be deleted when SP is enabled

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#1264]
When Single Page is enabled, the Sample Types that are created along with the ISA Studies and the ISA Assaya are hidden, so there's no way to delete them.
The Projects that are dependent on Sample Types can't be deleted.

**Comment by rabuono** [comment]
Triggering the deletion of the Sample Types when trying to delete Study or Assay would solve this.
Samples would have to be deleted before trying to delete Sample Types.

**Comment by floradanna** [comment]
Solved as consequence of solving #1457 #1571
