### ISSUE TITLE
NoMethodError on Sample Type assets_creators

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#1268]
```
A NoMethodError occurred in background at 2022-11-23 20:53:40 UTC :

  undefined method `unregistered' for []:Array
  /seek/lib/seek/acts_as_asset/searching.rb:14:in `block (3 levels) in <module:Searching>'
```
The issue relates to [this](https://github.com/seek4science/seek/blob/9aaa54524bea7e8290a4591bff20e2518a90222e/app/models/sample_type.rb#L137) method

**Comment by stuzart** [comment]
this should now be fixed, it was just dependent on some other changes that have now been merged
