### ISSUE TITLE
Tag container images with patch versions

### ISSUE THREAD

**Issue by talavis** [seek4science/seek#1273]
**Describe the bug**
Currently, the container images on Dockerhub only show major and minor versions (e.g. 1.12). When new patch versions are released, the existing tag is replaced.

The default behaviour in most container runtimes (e.g. docker) is to not download a new image if the requested tag already exists locally. This means that you will miss any new versions unless you explicitly request the download of a new version.

**To Reproduce**
Just look for available container image tags on Dockerhub.

**Expected behavior**
Each version get it's own unique tag, e.g. 1.12.0 or 1.12.1. 

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
Tested using docker, cri-o, and containerd running on Linux, including vms.

**Smartphone (please complete the following information):**
Not applicable.

**Additional context**
The lack of patch version information makes it very difficult to know what the latest version is. This is missed both by external users and apparently also by the developers themselves, as the latest version on Dockerhub is 1.12.2, while the latest on Github is 1.12.3.

Finally, the fact that you replace old images means that it will be a lot more difficult than it should be to return to the last working version if the latest version is not working.

**Comment by stuzart** [comment]
Yes, we plan to do this starting with our next releases. As is common with other containers, there will still be a 1.13 tag, but this will link to more specific tags for each version (1.13.0, 1.13.1 etc)

**Comment by talavis** [comment]
> Yes, we plan to do this starting with our next releases. As is common with other containers, there will still be a 1.13 tag, but this will link to more specific tags for each version (1.13.0, 1.13.1 etc)

Sounds exactly like what I wanted. Thank you.
