### ISSUE TITLE
Gatekeeper function bug:  when an asset is rejected, it still appears in the list of the requested approval assets 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#1275]
we should add `requested_approval_assets.reject!(&:is_rejected?) `

[here](https://github.com/seek4science/seek/blob/d350eba04b2a3e8b7ff13240a2dffb33c175690f/app/models/resource_publish_log.rb#L25)  to exclude all the rejected resources ?

**Comment by floradanna** [comment]
Will the user get a notification about the publication of the asset being rejected by the gatekeeper? Will a message be shown somewhere for the user? If not, I suggest we implement it.

**Comment by whomingbird** [comment]
yes when an asset is approved or rejected the user will receive a notification email.
You can see all type emails sent by SEEK here 
https://github.com/seek4science/seek/tree/master/test/fixtures/mailer

**Comment by fherreazcue** [comment]
The intention is now that the rejected items stay in the list, but collapsed, at the bottom of the page.
Implemented in [this commit](https://github.com/seek4science/seek/commit/30ba6338f09acd0cc1a7c45487c00cb312fce795).
