### ISSUE TITLE
Visualisation of content of *.xlsx files 

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1285]
This is not a new issue - I mentioned it many times and it has been solved in the past...I have been told, this is a configuration issue... but now  e.g. https://fairdomhub.org/documents/3414  page does not allow "view content" . Can this be solved in a sustainable manner?

**Comment by stuzart** [comment]
This seems to be because the exploring of spreadsheets is tied directly to the data files controller & it's views - so requires some refactoring to make more generic, moving behaviour into a shared module, to apply to all assets
