### ISSUE TITLE
RunTimeError after deletion of organisms

### ISSUE THREAD

**Issue by marteber** [seek4science/seek#13]
Dear SEEK team,

I just upgraded our SEEK instance from 1.0.2 to the latest commit (9cd2e9f1) to take advantage of the previously elusive organism browser. I also upgraded ruby with the experimental `rvm upgrade 2.1.7 2.1.8`, recompiled and set up the passenger module, and recompiled the assets as described in the upgrading guide.

I then deleted many of the default bacterial strains that SEEK comes with, as well as a duplicate for organism "Human" that I had set up while oblivious to the fact that there was a pre-defined one with the same name. For the two "Humans", I also switched our only project from the deletion candidate to the other one (which was necessary for the "Delete" button to become available). Afterwards, I added some new organisms. The final state looks like this:
![seek-organisms](https://cloud.githubusercontent.com/assets/8267958/14762679/ede29d48-0980-11e6-97e8-3ffcdbe4e545.png)

Shortly after finishing that work, I received 23 SEEK error notifications that started like this:
```
A RuntimeError occurred in background at 2016-04-23 15:57:13 UTC :

  Strain#ncbi_uri delegated to organism.ncbi_uri, but organism is nil: #<Strain id: 3, title: "168", organism_id: 548322508, created_at: "2016-03-02 18:23:29", updated_at: "2016-03-02 18:23:29", parent_id: nil, synonym: nil, comment: nil, provider_id: nil, provider_name: nil, is_dummy: false, contributor_type: nil, contributor_id: nil, policy_id: 3, uuid: nil, first_letter: nil>
  /home/seek-op/seek/app/models/strain.rb:33:in `rescue in ncbi_uri'
```
The first message with the full backtrace is here:
[SEEK-backtrace.txt](https://github.com/seek4science/seek/files/233055/SEEK-backtrace.txt)

So far nothing bad has come from that, but you might want to investigate. Let me know if you need more details.

**Comment by fbacall** [comment]
Hi, thanks for reporting this.

It looks like it isn't deleting the associated Strains when the Organism is deleted.

I'll try and find out why.

**Comment by fbacall** [comment]
I've added a rake task you can run to delete the dangling Strains:

```bundle exec rake seek:delete_orphaned_strains RAILS_ENV=production```
