### ISSUE TITLE
Keep fully generated swaggerdoc in the code

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#130]
Currently we have some definitions in: `public/2010/json/rest/definitions.json`

Which are pulled in by some scripts in the `gh-pages` branch to generate the full swaggerdoc.

Ideally the full swaggerdoc should be kept in the code repository, so if the API code is changed, the docs can be updated at the same time.

**Comment by alaninmcr** [comment]
This is mainly done. The files have been pulled from gh-pages. After consultation with Stuart, the complete swaggerDoc is not being generated as part of the build. However, the script full.py does create it.
