### ISSUE TITLE
HTMLi at https://testing.sysmo-db.org/search (content injection/spoof html content)

### ISSUE THREAD

**Issue by d3j906** [seek4science/seek#1321]
Penetration testing of our site detected an HTML injection vulnerability was found using the search function at /search (demonstrated below on the testing.sysmo-db.org site):

https://testing.sysmo-db.org/search?utf8=%E2%9C%93&q=Synack%3Ca+href%3D%22https%3A%2F%2Fwww.synack.com%22%3EClick%3C%2Fa%3EHTMLi

"This can be used to embed an attacker-controlled URL or any URL of the attacker's choosing and trick a user into visiting a malicious website."

Paste the link above into a browser, and click on the Click in the returned "No matches found for 'Synack[Click](https://www.synack.com/)HTMLi'."

Discovered on our 1.12 deployment and persists after upgrade to 1.13.

**Comment by stuzart** [comment]
Thanks for reporting this. We have a fix on it's way. 
The text is sanitized so that only certain tags appear, so I can reassure that scripts can be injected, but we will update it to strip out links etc.
