### ISSUE TITLE
Linking to event produces error 

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1333]
Reported by user : Creating new presentation and linking it to the event https://fairdomhub.org/events/257 was able to choose this event from list but finally got an error message  saying this event doesn't exist. I can reproduce this , but 
found a way around: created presentation without link to event and opened event page than and added new presentation to this event. This worked. Please look for the reason causing that error message

**Comment by stuzart** [comment]
@OlgaKrebs I'm afraid I've been unable to reproduce this, and looking at the html it appears to be listing them correctly with the right id's. Do you have any other information? I've tried testing hidden events dont show and that I'm able to link to other peoples events.

The event you link to above is hidden to me, are you able to share it with me (just viewable, no need for edit rights)?
