### ISSUE TITLE
add a new sample attribute type, which could store an array of controlled vocabularies  

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#1334]
This new sample attribute type can be used to create the sample type and the custom metadata attribute type: 

Compared to the "Controlled Vocabulary" sample attribute type,  the new type "Controlled Vocabulary List" is used to store an array of controlled vocabularies (strings).  see the image below : 

![image](https://user-images.githubusercontent.com/42063448/216615052-52e60765-c793-4b6d-b7a3-688ffad8149b.png)

**Comment by whomingbird** [comment]
#1331

**Comment by stuzart** [comment]
The new multi item autocomplete box needs applying to other places for consistency
