### ISSUE TITLE
Empty Programme does not appear in My Items

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1337]
**Describe the bug**
When clicking `My Items` an empty Programme to which the User is an admin does not appear.

**To Reproduce**
1. Create a Programme
2. Create a Project inside the Programme
3. Delete the Project inside of the Programme, thus making the Programme empty
4. The Programme now does not appear in `My Items`, it displays 

**Expected behavior**
A Programme, even if without Projects, should appear in `My Items` of its administrator. The Programme, even if empty, should also be listed under the `Related items` for its admin.

**Screenshots**
Bob is Programme admin
![image](https://user-images.githubusercontent.com/77321541/217023294-43caef0b-1e6c-4186-b429-f5ab39973b27.png)

The Programme is empty
![image](https://user-images.githubusercontent.com/77321541/217023474-fa2bf1b6-936b-480e-912a-b3a691ebafe8.png)

The Programme does not show in `My Items` for Bob
![image](https://user-images.githubusercontent.com/77321541/217023588-35c3cc45-f1f2-4f20-b757-de61c603093c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 109.0.1
 - Version SEEK 1.13.0

**Additional context**

**Comment by fbacall** [comment]
@kdp-cloud following the tech call I looked at the branch, and I would go about this in a different way.

I don't think any changes to the database are needed, SEEK is already storing the link between the person and the programme via the programme administrator role, it just needs some tweaks to expose this relationship.

Check out the "related items" code which is used to populate lists of items related to a resource (and I assume it is used for "My Items"):
https://github.com/seek4science/seek/blob/master/lib/seek/related_items.rb
it's a bit metaprogram-y, but basically it tries to find the correct method through which to get related items to a given resource.

sometimes we implement bespoke methods to get related items where the relationship isn't quite straightforward:
https://github.com/seek4science/seek/blob/master/lib/seek/acts_as_isa/relationships.rb#L6-L18
https://github.com/seek4science/seek/blob/master/app/models/study.rb#L62-L73

This recent commit did something similar:
https://github.com/seek4science/seek/commit/c658564ff8b64917dc4fe44fd4b03968e60edc2d#diff-afb6f8bc3bae71b75743e00882a060863e2430cbe858ec9014e5956504dfc61cR61

**Comment by kdp-cloud** [comment]
@fbacall  Thanks for looking into this!
So if I understand correctly, I would need to add "Programme" to the `RELATED_RESOURCE_TYPES` list and define a method in the Person.rb file named `created_programme_ids` or `contributed_programme_ids`.

I've been trying to implement this but rails complains about an unknown column 'programmes.contributor_id' in 'where clause'.

**Comment by rabuono** [comment]
With the current solution, the empty Programme shows under related items of the person who created it. However, the person does not appear under the related items of the Programme itself.

One observation parallel to this: If an instance admin creates an empty Programme (with no Projects) and adds no one as admin to that Programme, the resulting Programme will also not appear under related items of that instance Admin. This Programme can only be found under Browse>Programmes. This might be by design as the instance Admin can create Programmes for other users.

**Comment by floradanna** [comment]
> With the current solution, the empty Programme shows under related items of the person who created it. However, the person does not appear under the related items of the Programme itself.
> 

Why not? Program admin seems to appear under related items of the Programme itself.

**Comment by rabuono** [comment]
For the empty Programme, Alice can see it as one of her related items:
![image](https://user-images.githubusercontent.com/77321541/227970099-a7eec573-5bec-4cf9-a9bc-8898c7d45b3d.png)

But if one goes directly to the Programme, Alice is not listed there under related items:
![image](https://user-images.githubusercontent.com/77321541/227970363-125a04e4-673c-442d-9cb9-f2c9da2abcc0.png)

But SEEK is aware of the relationship, as Alice does appear as Programme admin under Overview:
![image](https://user-images.githubusercontent.com/77321541/227970665-f40c4b54-ad09-43d1-8f67-bd28bc59b653.png)

**Comment by stuzart** [comment]
> If an instance admin creates an empty Programme (with no Projects) and adds no one as admin to that Programme, the resulting Programme will also not appear under related items of that instance Admin. This Programme can only be found under Browse>Programmes.

If you included programmes that an instance admin can administer, then all programmes would be shown - and be equivalent to the browse programmes view
