### ISSUE TITLE
User guide index has a typo in link

### ISSUE THREAD

**Issue by YvonneKallberg** [seek4science/seek#1345]
**Describe the bug**
In [user-guide/index.html](https://docs.seek4science.org/help/user-guide/index.html) the link in 'File Templates' has a '_' instead of a '-' i.e. the link  https://docs.seek4science.org/help/user-guide/general-attributes.html#file_templates should be https://docs.seek4science.org/help/user-guide/general-attributes.html#file-templates

**To Reproduce**
1. Go to [user-guide/index.html](https://docs.seek4science.org/help/user-guide/index.html)
2. Scroll down to 'File Templates' (under 'General attributes and links')
3.  Click on the link [File Templates](https://docs.seek4science.org/help/user-guide/general-attributes.html#file_templates)
4. End up on top of the [General attributes](https://docs.seek4science.org/help/user-guide/general-attributes.html) page instead of further down at [File Templates](https://docs.seek4science.org/help/user-guide/general-attributes.html#file-templates) heading

**Expected behavior**
I expected to end up further down, at [File Templates](https://docs.seek4science.org/help/user-guide/general-attributes.html#file-templates) heading

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
Irrespective

**Smartphone (please complete the following information):**
Irrespective

**Comment by stuzart** [comment]
fixed, thanks for reporting
