### ISSUE TITLE
Edit ISA Study returns 500

### ISSUE THREAD

**Issue by Hammarn** [seek4science/seek#1355]
**Describe the bug**
It's possible to edit the study under "normal view" but trying to edit the study under "Single Page" `Edit ISA-Study` returns error code 500. `Edit ISA-Study`contains the sample source which we want to access. 

**To Reproduce**

-1 Under Single Page view of Study.
-2 Click edit ISA Study under Actions

**Expected behavior**
Able to edit the 

**Screenshots**
https://files.slack.com/files-pri/T02HT5X58-F04P822U38D/screenshot_2023-02-13_at_13.37.35.png

**Desktop (please complete the following information):**
MacOS
Tested on both 
Firefox 109.0.1  and 
Chrome Version 109.0.5414.119 

Log output:

```
E, [2023-02-13T11:21:36.236968 #766] ERROR -- : [246142700da6ba47c0efa085e0dc70b7] ERROR - NoMethodError (undefined method `can_perform?' for nil:NilClass)
E, [2023-02-13T11:21:36.237100 #766] ERROR -- : [246142700da6ba47c0efa085e0dc70b7] Sending execption ERROR - NoMethodError (undefined method `can_perform?' for nil:NilClass)
I, [2023-02-13T11:21:36.239611 #766]  INFO -- : [246142700da6ba47c0efa085e0dc70b7] method=GET path=/isa_studies/2/edit format=html controller=IsaStudiesController action=edit st\
atus=500 duration=41.94 view=1.97 db=3.99 time=1045999.23 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safa\
ri/537.36

```
Encountered by @parul12

**Comment by floradanna** [comment]
Study created via default view cannot be edited via Single Page. The reverse is possible and might cause problem too (see #1351).

This is because "Create ISA" via default view is different from "Design ISA" in Single Page, since the two processed have different steps and structure.

**Comment by floradanna** [comment]
related to #1570
