### ISSUE TITLE
Make samples extracted from datafile editable

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1357]
Problem: samples extracted from a datafile cannot be edited because they are forever bound to the information provided in the datafile.

Solution: samples extracted from a datafile should be editable after extraction, as any other samples in SEEK.

Process: 
- the user goes to "edit sample",
- if sample has been extracted from a datafile, SEEK shows a warning "Sample has been extracted from a datafile, editing this sample will make the datafile not valid anymore for this sample" or something.
- if user continue editing, the datafile link for that sample will gain the label "not valid anymore"

Process for editing a **sample type** that has a linked datafile: same process as described for the editing of samples

**Comment by stuzart** [comment]
this relates to #1136 and involves decoupling the permissions and projects from the datafile. The datafile could just provide the defaults

**Comment by stuzart** [comment]
also #1356
