### ISSUE TITLE
Update API documentation to OpenAPI Version 3

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#136]
It is currently "out of date".

**Comment by alaninmcr** [comment]
[Attributes review](https://docs.google.com/document/d/12Xd8crfL54sqpUvMoHsatavQbVQH3MPXxNrZ_HZK90w/edit?usp=sharing)

**Comment by alaninmcr** [comment]
We can use https://github.com/Mermade/oas-kit to do the initial conversion.

**Comment by alaninmcr** [comment]
It does not like colons in the descriptions (and possibly elsewhere) so these need to be replaced with the HTML code &#58;

This can probably be done automatically

**Comment by alaninmcr** [comment]
It appears to be objecting to markdown in the descriptions

**Comment by fbacall** [comment]
Can we just convert it by hand?

**Comment by alaninmcr** [comment]
Yes-ish I think we can use the auto-generated version as a skeleton that we fill in.
