### ISSUE TITLE
Revisit custom_input flag for SampleControlledVocab

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1381]
`custom_input` flag allows the user to add custom values, and not locked and validated against the controlled vocab.

currently it sets a `data-is-ontology` attribute on the field, and is then hidden from the available options by javascript

it's not necessarily an ontology based SCV, and am not sure why it is hidden ? (@floradanna / @rabuono ??)

it would also be more appropriate and flexible to apply this flag to the sample attribute where the SCV is used, so that the same SCV can but used with or without custom inputs depending on how the attribute is used.

**Comment by floradanna** [comment]
is it related to #1147 ?

**Comment by stuzart** [comment]
> is it related to #1147 ?

no

**Comment by stuzart** [comment]
initially I will remove `data-is-ontology` and the associated javascript to hide it, and just filter out items from the select field that have `.custom_input?` as true. For datahub the behaviour will be the same.

**Comment by floradanna** [comment]
@kdp-cloud @stuzart is this issue resolved? or not yet?

**Comment by stuzart** [comment]
> @kdp-cloud @stuzart is this issue resolved? or not yet?

yes it has, it was fixed in a duplicate issue #1648 and will be part of 1.15.0. Feel free to close the issue
