### ISSUE TITLE
Add "custom metadata" ability for other resource types.

### ISSUE THREAD

**Issue by fmeineke** [seek4science/seek#1407]
There was a need to enable custom metadata also for non-ISA resources, e.g. for projects. Can this functionality be generalised to all resource types / seek assets?

**Comment by stuzart** [comment]
The Custom Metadata is already fairly generalised and can be dropped into any resource type just by adding a few lines of code, so this is something we have been discussing. It would then be controlled by whether Custom Metadata has been defined for that particular supported type. There could be some other side effects such as the API that would need thinking about, and there were some discussions about whether it would be sensible to provide this level of freedom. @whomingbird is going to look into allowing it for asset types.

**Comment by whomingbird** [comment]
`Custom metadata` has been renamed as `extended metadata`, and this extended metadata feature will be incorporated into the following resource types in SEEK: 

`Collection`, `DataFile`, `Document`, `Event`, `Model`,`Presentation`,`Sop`, `Template`, `Project`
