### ISSUE TITLE
LS RI Service Provider Registration: need for technical details

### ISSUE THREAD

**Issue by jos4uke** [seek4science/seek#1415]
Hi

I recently installed an instance of FAIRDOM-SEEK for a private project.
I didn't find much administration documentation to guide me through configuration of external authentication such as LS Login.

I looked for LS Login instructions for relying parties, and get to their registration form but I am struggling now how to fill in the technical information (https://webapp.aai.lifescience-ri.eu/sp_request?).

Could you provide some guidance on which protocol should be given to register my seek instance?
* SAML2 / SAML2 metadata link  ? or
* OIDC / OIDC supported grants / redirect URLs ?

Thanks in adavance

Jos

#### SAML2 screenshot
![LS-Login_SP_registration_techinfo_SAML2](https://user-images.githubusercontent.com/1325049/230312399-d4a91000-3163-4b6a-9198-dd1df2789095.png)

#### OIDC screenshot
![LS-Login_SP_registration_techinfo_OIDC](https://user-images.githubusercontent.com/1325049/230312424-21017110-4a8b-4ad7-826c-ecc715e6fc5a.png)

**Comment by fbacall** [comment]
Hi Jos. SEEK is using OIDC and the Authorization Code flow (I think that option is scrolled off your screen shot).

Noted that this needs to be described somewhere in the admin page/docs.

**However**, there are a few open issues relating to LS-Login support that you will likely be blocked by, the main one being #1030 :(

If you would like to try working around it (and it would really help us out if you figure it out), I left some details in a comment about where the configuration is currently stored, and where details on the LS-Login settings can be found: 
https://github.com/seek4science/seek/issues/1030#issuecomment-1498742629

**Comment by jos4uke** [comment]
Hi @fbacall 

Thanks for the detailed information, it is very useful ^^

I will register my client and see how it goes. 
I will try to figure out what is blocking, and would be glad to help you debug this issue #1030.
We keep in touch.

Best whishes
