### ISSUE TITLE
500 Seek error on views/download descending sort when a tag has been selected

### ISSUE THREAD

**Issue by CaroleGoble** [seek4science/seek#1417]
**Describe the bug**

**To Reproduce**
1.choose an tag  https://workflowhub.eu/workflows?filter%5Btag%5D=covid-19
2. select views descending or downloads descending for sort
3. 500 error
this always happens. The sort does work if a tag has NOT been selected

**Expected behavior**
Not an error - the results sorted by views!

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox

**Comment by fbacall** [comment]
Error trace is:
```
An ActionView::Template::Error occurred in workflows#index:

  Mysql2::Error: Duplicate column name 'id'
  app/views/general/_index_paged.html.erb:3
  app/views/general/_index.html.erb:35
  app/views/workflows/index.html.erb:1
  app/controllers/application_controller.rb:49:in `block in with_current_user'
  app/models/user.rb:271:in `with_current_user'
  app/controllers/application_controller.rb:48:in `with_current_user'
  lib/rack/settings_cache.rb:9:in `call'
  ```
