### ISSUE TITLE
Existing template when designing a Study

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1424]
**Describe the bug**
I cannot open existing template when creating a Study (button is not responsive), both in Chome and Safari

**To Reproduce**
1. Go to Design Study
2. Click on Existing template
3. See error

**Expected behavior**
Window to choose from existing template should open

**Comment by kdp-cloud** [comment]
I've updated all the templates and the modal form shows again.
I'm closing this issue for now but the user should receive an error message in  a pop up instead of the console.
Another issue has been opened that addresses this: [# 1426](https://github.com/seek4science/seek/issues/1426).
