### ISSUE TITLE
CV List missing in DataHub after update

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1425]
**Describe the bug**
Sample type attribute CV List is missing in DataHub instances even though the software has been updated to the newest release.

**To Reproduce**
1. Go to Sample type attribute type
2. Click on dropdown menu to select CV List
3. See error

**Expected behavior**
Find CV List as attribute type

**Comment by kdp-cloud** [comment]
Updating  the test environment solved this issue.
