### ISSUE TITLE
Error pop up missing templates

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#1426]
When a sample type is created from an existing template in single page, the application looks for templates with level attribute values:
- study source
- study sample
- assay

If the templates in the database don't contain any of these, the modal form just doesn't show and the user gets an error in the console log. It would be better if instead the user gets a message that no suitable templates could be retrieved from the database.

**Comment by floradanna** [comment]
In Single Page when creating ISA:
If there are no templates for sample types, the button "Existing Templates" should be disabled and the following message should appear: "No templates available".

Currently, the button is clickable but nothing happens.

<img width="377" alt="Screenshot 2023-07-24 at 14 00 21" src="https://github.com/seek4science/seek/assets/51486716/f3abe956-c5e5-4f1a-b61f-892a40b1b05a">

**Comment by floradanna** [comment]
@reutenauer since you are working on fixing template upload, maybe it would be efficient to look at this issue as well.

**Comment by reutenauer** [comment]
Sure, I’ll have a look.
