### ISSUE TITLE
Update factories to be compatible with factory_bot 6

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#1428]
factory_bot has changed how factories are defined from our current version (2), so many (all?) factories will need to be updated.

Our current version of factory_girl/bot throws deprecation warnings with Ruby 3.

See guide for current syntax: https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md

An example of a such a change would be to the factory:

```ruby
Factory.define(:saved_search) do |f|
  f.search_query 'cheese'
  f.search_type 'All'
...
```

```ruby
FactoryBot.define do
  factory(:saved_search) do
    search_query { 'cheese' }
    search_type { 'All' }
...
```

Changes noticed so far:
- Definitions are wrapped in a new block
- Definitions now just use `factory(:something)`
- Attributes have to be provided in a block

**Comment by somathias** [comment]
I completed the update to the factories in commit c9ab356. Can this issue be closed?

**Comment by stuzart** [comment]
@somathias I've applied the fix that should now let the tests run ( https://github.com/seek4science/seek/actions/runs/4861953961 ) that may indicate if any have been missed. There will probably be errors but hopefully none that relate to the old factories

**Comment by fbacall** [comment]
Summary of some changes:
* Replace `Factory` with `FactoryBot`.
* Explicitly call `create` (instead of `Factory(:something)`).
* Replace `after_build`/`after_create` with `after(:build)`/`after(:create)`.
* Wrap attributes in {} to fix `KeyError: Trait not registered`
* Use `with_project_contributor` to fix `ActiveRecord::AssociationTypeMismatch: Project(#966920) expected, got nil ...`
* Specify the build/create strategy for associations of various factories: https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#build-strategies-1
