### ISSUE TITLE
Import default template from json fails silently

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#1454]
**Describe the bug**
The mechanism to upload a json file to extract a sample type template from it fails without returning any errors.

**To Reproduce**
1. Go to The admin panel (logged in as system admin)
2. Click on Enable/Disable features
3. Make sure 'Sample type Template enabled' is enabled
4. Click Add default Templates
5. Upload a suitable json file
6. The job finishes and returns the message that the import was successful
7. No Templates were created

**Expected behavior**
Template should be created.

**Screenshots**
![image](https://github.com/seek4science/seek/assets/82407142/bd0db0aa-610f-4072-9c8b-f1c199162496)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox, Chrome

**Comment by kdp-cloud** [comment]
The changes made in [this commit](https://github.com/seek4science/seek/commit/19beb9187ff7284056adef1aa935eb4670f5ac1b) result in the template extractor looping over an empty array of files __every time__. Thus, it doesn't emit any error messages when completing.

To do:
- [ ] Make sure the application doesn't loop over an empty array each time.
- [ ] Make sure the `file_field_tag` can only accept json files by default.
- [ ] If there is an edge case where no files are found to loop over, the application should raise an error.

**Comment by floradanna** [comment]
The templates population task keeps running without completing the task.


![Image](https://github.com/seek4science/seek/assets/51486716/8b5abee0-5519-4685-ab01-32eb096e1bdc)

![Image](https://github.com/seek4science/seek/assets/51486716/05ea8690-0758-4657-8241-a15398f14d0a)

**Comment by floradanna** [comment]
Switching branches can affect the background workers.
Simply restarting them fixes it.
To be checked in testing.sysmo.
