### ISSUE TITLE
Workflow type "PyCOMPSs" not detected when importing from RO-Crate

### ISSUE THREAD

**Issue by rsirvent** [seek4science/seek#1463]
Hi. When I'm trying to import a COMPSs workflow from RO-Crate it does not detect correctly the "workflow type" in workflowhub.eu, while in dev.workflowhub.eu it detects it correctly.

Could you check what is the problem?

For testing, you can download the RO-Crate from workflows:
https://workflowhub.eu/workflows/484
https://workflowhub.eu/workflows/485

Thanks in advance.

**Comment by fbacall** [comment]
Hi Raul,

The problem was that the URL of the COMPs workflow type* did not match what was in the RO-Crate. I've updated it now, can you try again?

* https://workflowhub.eu/workflow_classes

**Comment by rsirvent** [comment]
Yes, it works now. Thanks again.
