### ISSUE TITLE
In Single Page add SOP option when editing ISA Assay

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1466]
When editing an existing Assay in Single Page, the user should be able to remove/add/change the linked SOP. Currently there is no menu item for SOP when editing an Assay.

- The same SOPs menu shown when creating an ISA Assay should be displayed.
- The same options shown when "creating an ISA Assay" should be displayed when "editing an ISA Assay"

Important: this issue was supposed to be solved (#1170) already, but it is not fixed in datahub.test. Need to understand why and what happened. Make sure similar things do not happen systematically and go unnoticed.

**Comment by kdp-cloud** [comment]
On the main branch this has apparently been fixed already but it hasn't been included in one of the releases for some reason.


![Image](https://github.com/seek4science/seek/assets/82407142/2a17aa62-8a57-4b3d-9e07-ec080cd91e37)


I will leave this issue open for now until I get more information

**Comment by kdp-cloud** [comment]
This fix is included in SEEK-1.14
