### ISSUE TITLE
Include in DF.related_samples those that have been linked via a Sample Type data file attribute

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1534]
Currently the related samples only includes those that have originated from the DataFile via extraction.
Datafiles and Samples can also be linked via the Sample Type, "Registered DataFile" attribute but these are not included.

There is a request that these should be included - but is there a need to distinguish between the 2 cases? They are only related, and there are other cases where related items can come from multiple sources

**Comment by floradanna** [comment]
In Single Page, we use 1 sample type for 1 experimental step. Therefore, 1 sample type must have:
- Inputs (which are other SEEK samples, unless it is the first step of the experiment) and 
- Outputs (new SEEK samples).

For instance, 1 sample type to describe the conditions (treatments) of cell culture:
- Inputs = cell lines (existing SEEK samples)
- Outputs = treated cell lines (new SEEK samples)
And 1 sample type to describe the parameters used for taking images (OR for taking any kind of measurements):
- Inputs = treated cell lines (existing SEEK samples)
- Outputs = image data files (new SEEK samples)

I tried to summarise this issue in the following image. It might help with finding appropriate solutions.
![IMG_3393](https://github.com/seek4science/seek/assets/51486716/705670d0-4387-480f-91da-4aef00985832)

**Comment by floradanna** [comment]
If Data Files derived from the analysis of biological samples are treated as SEEK samples as well, we could develop a visualisation tool for "Sample lineage" to visualise all samples --> sub-samples --> etc, including derived Data File(s), for 1 SEEK sample.

For overview, we could use the tabular format applied in "Experiment overview" in Single Page.
