### ISSUE TITLE
Publications are shown multiple times in ISA tree and graph

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1540]
Unlike data files and sops, publications are shown via their related items rather than restricted to direct links. i.e if an Assay has a publication, it is also shown against the Investigation and Study above:

<img width="623" alt="image" src="https://github.com/seek4science/seek/assets/201658/9ca13ac1-60aa-445c-93d0-349f8bd04c2b">

**Comment by stuzart** [comment]
This seems to be easily fixed by changing the precendence in `resolve_association` to check for direct associations before checking for related associations. In most cases (and I can't think of any others) I think this would be the preferred order.

However, this seems to be the same whether defined as `children:` or `related:` and I wonder if they should always check direct associations and related associations respectively.

**Comment by OlgaKrebs** [comment]
I justed checked in FAIRDOMHub - the same (example attached)  Is it new? I can not imagine it was shown this way all the time... also looking for "older" screen shots I see diff picture : link only where it is defined. Not sure, but may be this info helps to find a solution
![Publication_ISA](https://github.com/seek4science/seek/assets/55085007/98bd2e4a-0d18-4514-878f-f27d47baf950)
