### ISSUE TITLE
Add a tag to identify I-S-A that are ISA-JSON compliant

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1570]
Currently, the sole distinction between Creating/Editing a "vanilla seek ISA" and an "ISA-JSON compliant experiment" lies in the source of the request: whether it originates from the default view or a single page.

This is a week system that causes many conflicts, such as allowing users 
- to edit "ISA-JSON compliant experiment" using Editing option available from default view and vice verse
- link "vanilla seek study or assay" to Investigation or Study containing "ISA-JSON compliant experiment", therefore breaking ISA-JSON export at investigation level.

A more optimal solution would involve adding an option (or a tag, a parameter, etc.) during the Investigation creation process when SP advanced is enabled. This option would allow the user to decide whether the Investigation will exclusively contain "vanilla seek ISA" or "ISA-JSON compliant experiments".

Then, the different GUI to create/edit "vanilla seek ISA" or "ISA-JSON compliant experiments" could be shown to the user based on this information.

**Comment by floradanna** [comment]
[RAD Action_1 - Epic 1.8](https://docs.google.com/document/d/1ByETT3mssb_Ng4VYPwSw7MlxfvRefKqsCcCZvgtUCXY/edit#heading=h.jd63gy2wgf0s)

**Comment by somathias** [comment]
This can be done by adding a boolean flag to investigations, called eg. "is_fully_ISA_compliant". 
As Studies and Assays always link to an investigations, they "inherit" the property from their top-level investigation.

If ISA-JSON compliance is enabled, the create investigation form should display a checkbox for tagging the investigation as "fully_ISA_compliant".

**Comment by floradanna** [comment]
Could we implement this in a way that "fully ISA-JSON compliance" would be the ONLY way to create ISA in a specific instance? So, maybe having some instance-specific configuration that makes "fully ISA-JSON compliance" the default.

Instance admin could then configure the instance in 3 possible ways:
- default ISA only
- default ISA and "fully ISA-JSON compliant ISA"
- "fully ISA-JSON compliant ISA" only

Let me know if what I mean is not clear.

**Comment by somathias** [comment]
Assuming that all three configuration options are desired (as opposed to just having either "default ISA only" or "fully ISA-JSON compliant only"):

this could be implemented using an additional subflag/checkbox in the admin panel "Allow only full ISA-JSON compliance", that becomes available when checking "Compliance to ISA-JSON schemas enabled". 
If the additional checkbox is checked, all ISA elements would be created with the "is_ISA_JSON_compliant" flag automatically set to true.
