### ISSUE TITLE
Browse samples by template feature

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1573]
The feature browse samples by template feature is not present in data hub-dev instance (main).
It seems there is no GUI to reach the feature anymore, since the old "[Browse samples by ST](https://datahub-test.elixir-belgium.org/sample_types/select)" has been replaced by a new way to "[Browse samples](https://testing.sysmo-db.org/samples)" ([commit](https://github.com/seek4science/seek/commit/c42d5079c8fcfcbde86596d01996cd5382c51ab7)).

Possible solution: from header menu Browse --> add the option "Samples by template" that leads to https://datahub-test.elixir-belgium.org/samples/query_form.

**Comment by floradanna** [comment]
Better solution is: add a button ("Query by template") on the samples index page, like the "Filter and export" button on the publications index.

Query by template --> Query samples

The choice of "query" is based on the following definitions
- A **query** is a formal request for information, often involving specific criteria or conditions.
- A **filter** is a way to narrow down data by applying specific criteria to exclude certain items.
- **Browsing** is a casual exploration of available content without a specific goal.
- **Searching** is actively looking for specific information within a dataset using search terms or criteria.

**Comment by floradanna** [comment]
In Browse --> Samples view, Sample types created starting from templates (therefore, created via SP) should not be listed for filtering. These sample types are already hidden from adult view when Browsing sample types.

**Comment by kdp-cloud** [comment]
The quick fix was to add an extra button on the samples index page to redirects this to the Sample Query page and treat the filtering as a separate issue.
A new issue for the filtering is made here: [Issue 1576](https://github.com/seek4science/seek/issues/1576)
