### ISSUE TITLE
Template upload not working in docker deployment

### ISSUE THREAD

**Issue by somathias** [seek4science/seek#1581]
**Describe the bug**
Uploading default templates via the admin panel does not add templates to the seek instance when deployed via docker. Moreover, the task is shown as running indefinitely.

**To Reproduce**
0. Have a docker deployment of SEEK using the main docker-compose file. 
1. Go to 'Server admin>Enable/disable features'
2. Click on 'Add default Templates' under the 'Sample type Template enabled' checkbox.
3. Choose a suitable .json file and click upload
4. See that the task is shown as running and remains so. 

**Expected behavior**
Templates are actually uploaded and the task is shown as completed when done. 

**Explanation**
The problem is due to the files involved not being written to a volume shared between the main SEEK container and the SEEK-workers container. 
- The json file is put in `seek/config/default_data/source_types`
- The lock file and the results file are put into `seek/tmp/`
As neither location is in a shared volume the seek-workers do not find the json file and hence do not actually extract the templates. Similarly, the results file from the workers is never seen by the main seek container.

**Comment by somathias** [comment]
One possible solution would be to 
1. add another shared volume for the `source_types` folder and 
2. write lock and result files to `tmp/cache` which is shared among the containers

**Comment by stuzart** [comment]
you should put the file into a directory within the filestore/ which is shared and persisted. Certainly shouldn't be being put into `seek/config/default_data/source_types`

**Comment by reutenauer** [comment]
Thank you, Stuart.  It did seem odd to put the JSON file in that location to start with.  We’ll prepare a pull request.

**Comment by stuzart** [comment]
There are some methods in `Seek::Config` that define certain filestore directories. The filestore location is actually configurable, for cases where people want to point to a separate disk or shared network drive. 

e.g https://github.com/seek4science/seek/blob/main/lib/seek/config.rb#L197

the tmp one might be fine for you, or you might want to to define a new directory and add an appropriate method.
