### ISSUE TITLE
Relation between samples and  ISA-compliant study/assay

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1587]
Issue: samples created in DT are not always shown as samples associated to SEEK assay in default view. Not clear what is the cause of the apparently random and inconsistent behaviour.

Criteria for solution:
1. It must address the epic stories listed in [Epic ID: 11.2](https://docs.google.com/document/d/1pllCMivX9JiSkWsX_yVll1srEHBKNO8Hy2VlWw2bQOg/edit#heading=h.u3jbo9p4b1dp)
2. It must reuse as much as possible existing features in SEEK: the search/browse features in SEEK, related items, etc.
3. Consider if it could easily develop after addressing issue #1570

**Comment by floradanna** [comment]
@somathias @reutenauer 
when implementing the ISA-JSON compliance flag, we should make sure that it propagates to all ISA elements (study, assay, sample types, samples etc).

This might help with the issue above.

**Comment by reutenauer** [comment]
Thank you for your comment.  The flag already propagates to studies and assays, but not to sample types or samples yet.  We’ll look into it.

**Comment by floradanna** [comment]
Another aspect to take into account is that it is not only about GUI.
If the user type the following URL https://datahub-test.elixir-belgium.org/assays/58/edit directly , the user must be always redirect it to the edit page made for ISA-JSON compliant assays
