### ISSUE TITLE
Missing description that a new programme will be requested when creating a project

### ISSUE THREAD

**Issue by somathias** [seek4science/seek#1595]
**Describe the bug**
If programmes are enabled:
When a user who does not have admin rights over a programme creates a project, they will be prompted to put in a title for a programme in the first field on the guided project creation form. However, it is not made clear to the user that this will result in a request for a new programme being sent to the instance administrators (and thus that they cannot use this form to request projects within already existing programmes).

**To Reproduce**
1. Have programmes enabled.
2. Be a user without admin rights for any programme
3. Click "Project" from the Create menu
4. See first field of the form.

**Expected behavior**
A description should be displayed explaining that a new programme will be requested from the instance administrators within which the new project will be placed. 

**Screenshots**
![image](https://github.com/seek4science/seek/assets/18682429/39a71f19-8aa7-448a-b751-b38d1de9192b)

**Comment by floradanna** [comment]
Agree. We could display something similar to what it is shown to programme admin (see screenshot below)

<img width="717" alt="Screenshot 2023-09-28 at 12 30 25" src="https://github.com/seek4science/seek/assets/51486716/1ad648b8-d84d-4834-9624-d54bde2ca9d9">

**Comment by somathias** [comment]
The suggestion at the tech call was to add a description only for now, eg. "Specify a title for a new Programme, which your new Project will be associated with. "

Unifying the interfaces for programme admins and non-admins could then be a next step.
