### ISSUE TITLE
Easier way of specifying permissions for project members and all other users

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#16]
Putting this here since JIRA is down.

Currently you can choose permissions for either:
- Project members & registered users
- All users (registered & anonymous, regardless of project)

need a combo of both, so can easily specify permissions for project members (e.g. view, download, edit) and all users, anonymous or registered, (e.g. view only).

**Comment by stuzart** [comment]
This is being addressed with an improved matrix based way of providing the authorizations
