### ISSUE TITLE
DataHub Configuration - improve single page

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1601]
The single page view must be further decoupled from ISA-compliance related features.

**Comment by somathias** [comment]
I suggest the following: 

If what is currently called "Single Page advanced features" is turned off, then 

1. the single page view should display the same buttons regarding the creation of investigations as the default view. 
This would mean to replace the "Design Investigation" button with the regular "Add new">"Add new investigation" button and should then allow the user to use the single page view without committing to full ISA compliance.

2. the single page view should display a button leading back to the default view.

3. the single page view  should display all assets associated with the project in the tree view

This could of course be implemented step-wise.

**Comment by floradanna** [comment]
After assessing the priorities for the utilisation of the ISA framework in SEEK, it's clear that working on SP as just an alternative view won't benefit the framework's usage. Consequently, this approach isn't beneficial and doesn't align with our priorities in the short term.

Another approach to improve the utilisation of the ISA framework in SEEK could be focusing on allowing access to ISA compliant experiments solely through "SP," which will be renamed as "ISA Experiments & Samples Editor."

How to implement short and long term solutions in this direction needs to be defined.
