### ISSUE TITLE
"Query for Template" button visible for all assets, not only Samples

### ISSUE THREAD

**Issue by somathias** [seek4science/seek#1604]
**Describe the bug**
When browsing any asset or ISA element, the "Query for Template" button that leads to the querying of Samples by Templates is displayed next to the new button.

**To Reproduce**
1. Go to 'Browse' > Investigations
2. See button

**Expected behavior**
The button should only appear on the Samples index page.

**Screenshots**
![image](https://github.com/seek4science/seek/assets/18682429/c162caa0-95c8-4b2d-9abc-0f7af059b500)

**Comment by somathias** [comment]
@floradanna please confirm that this is a bug and that the expected behavior described above is correct.

**Comment by floradanna** [comment]
yes, the expected behavior described above is correct.

**Comment by floradanna** [comment]
All features developed to support compliance to ISA-JSON specifications in SEEK should be grouped into one single optional feature in the admin panel of SEEK.

This feature should be named "**Compliance with ISA-JSON schemas enabled"**. This feature shall include the following functionalities:
- ISA templates (including a seeded template - WIP)
- ISA-JSON export (GUI and API)
- Query samples by ISA templates
- Editing samples via excel upload
- Download of an excel containing samples from a sample type
- Dynamic table and related features (samples batch sharing, copy-paste from clipboard etc)

Some of these functionalities are already grouped under the feature "Single Page advanced". The label "Single Page advanced" can be dismissed.
