### ISSUE TITLE
Button (link) between WFH and LifeMonitor link broken

### ISSUE THREAD

**Issue by hexylena** [seek4science/seek#1611]
**Describe the bug**

E.g. https://workflowhub.eu/workflows/110 clicking the "Tests" button 
![image](https://github.com/seek4science/seek/assets/458683/81c52932-8c9a-4c73-9460-06e246567bde)

results in a 404: https://api.lifemonitor.eu/workflow;uuid=969eb530-6566-0139-90bb-005056ab5db4

The `api` should be `app`. I'd offer to make a PR, but I couldn't figure out where to swap out the `life_monitor_ui_url`

**Comment by fbacall** [comment]
This has been fixed in #1591 but is not live yet
