### ISSUE TITLE
pdf preview loading

### ISSUE THREAD

**Issue by wittigue** [seek4science/seek#1619]
**Describe the bug**
There is a problem with the pdf preview loading.

Tested for Firefox, Chrome and Edge.

Example:
https://fairdomhub.org/presentations/1414
![FAIRDOMHub_pdf_load](https://github.com/seek4science/seek/assets/29859147/42eb1ae8-1617-4690-9810-da0e141a62b1)

**Comment by fbacall** [comment]
Works without the `&disposition=inline`, but not sure why
