### ISSUE TITLE
Deleting samples is slow

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#1628]
Deleting a sample on fairdomhub takes ~7 seconds.

Most of this time is spent selecting auth lookup records to batch delete.

The reason this is slow is because `in_batches` automatically adds an `ORDER BY` clause to order the results by ID.

Without this ordering it would be much faster to select:
```
mysql> SELECT `sample_auth_lookup`.`id` FROM `sample_auth_lookup` WHERE `sample_auth_lookup`.`asset_id` = 12345 LIMIT 1000;
Empty set (0.02 sec)

mysql> SELECT `sample_auth_lookup`.`id` FROM `sample_auth_lookup` WHERE `sample_auth_lookup`.`asset_id` = 12345 ORDER BY `sample_auth_lookup`.`id` ASC LIMIT 1000;
Empty set (5.53 sec)
```

There doesn't seem to be away to avoid this ordering, but perhaps we could change it to order by e.g. `asset_id`, which is indexed:
```
mysql> SELECT `sample_auth_lookup`.`id` FROM `sample_auth_lookup` WHERE `sample_auth_lookup`.`asset_id` = 12345 ORDER BY `sample_auth_lookup`.`asset_id` ASC LIMIT 1000;
Empty set (0.01 sec)
```

**Comment by fbacall** [comment]
Ordering has to be done on the primary key, but `order: :desc` seems to be faster

**Comment by fbacall** [comment]
Actually in reality it seems to be slow regardless:

```
3.1.4 :026 > Benchmark.bm { |x| x.report { s.auth_lookup.in_batches(of: 1000).delete_all } }
       user     system      total        real
   0.022396   0.000557   0.022953 (  6.019083)

3.1.4 :029 > Benchmark.bm { |x| x.report { s.auth_lookup.in_batches(of: 1000, order: :desc).delete_all } }
       user     system      total        real
   0.018162   0.000000   0.018162 (  6.040140)

3.1.4 :032 > Benchmark.bm { |x| x.report { s.auth_lookup.delete_all } }
       user     system      total        real
   0.003310   0.000000   0.003310 ( 22.627145)

3.1.4 :035 > Benchmark.bm { |x| x.report { s.auth_lookup.in_batches.delete_all } }
       user     system      total        real
   0.019610   0.000811   0.020421 (  5.866738)
```

**Comment by fbacall** [comment]
Still quite slow even with jobs to delete auth lookup (~30 seconds on local instance in dev mode with 233 samples) as it still has to delete each sample and queue up several jobs for each.

Consider also deleting the samples in a job.

**Comment by stuzart** [comment]
With the delete auth lookup job, it can still take some time to delete all the samples linked to a data file (I tried with 2000 samples and it took over a minute, albeit in development mode). Seemed to be spending a lot of time deleting profiles and permissions, which wasn't the case previously when linked to the datafile policy.

I think it might be a good a idea to create a job for deleting batches of samples, for the case where they are linked to a data file.

Also noticed that it was creating a SampleTypeUpdateJob for every sample deleted - so by doing in a job this could be supressed and then a single SampleTypeUpdateJob created at the end
