### ISSUE TITLE
Feature suggestion: allow zoom in/out when opening the WorkflowSketch

### ISSUE THREAD

**Issue by rsirvent** [seek4science/seek#1637]
See: https://workflowhub.eu/workflows/614

While in the "Overview" tab you can see the whole workflow, it is too small to read the details. And if you go to "Files" -> "complete_graph.svg" the image is very large and difficult to navigate.

It would be great that you could zoom in/out the WorkflowSketch when it is open, to navigate more easily through complex workflows.

**Comment by rsirvent** [comment]
Any feedback on this would be great, at least to know someone has read it.

**Comment by fbacall** [comment]
Agree some detailed workflows are very difficult to read

We could use the same widget that is used in CWL viewer: https://view.commonwl.org/workflows/github.com/tmooney/cancer-genomics-workflow/blob/downsample_and_recall/definitions/pipelines/panel_of_normals.cwl

**Comment by rsirvent** [comment]
@fbacall not sure if your fix is related, but now I cannot see the diagram when using Files -> complete_graph.svg. It shows the text inside the SVG file, not the diagram.

**Comment by fbacall** [comment]
I believe that will be resolved when the PR is merged and deployed
