### ISSUE TITLE
Bug importing Workflow from RO-Crate: creators are not linked with their corresponding WorkflowHub account

### ISSUE THREAD

**Issue by rsirvent** [seek4science/seek#1638]
**Describe the bug**
When creators of a workflow are added/modified by hand (with the portal), they are linked with their corresponding WorkflowHub users. However, when the workflow is created imported from an RO-Crate, the creators are not linked to their existing WorkflowHub users.

**To Reproduce**
Import a workflow from RO-Crate (for instance this one: https://workflowhub.eu/workflows/614). Creator "Jorge Ejarque" should be linked with his WorkflowHub profile.

**Expected behavior**
When a workflow is imported from an RO-Crate, creators should be matched with existing WorkflowHub users to add al link to their profiles. Matching could be done by ORCID (check if creator exists as a user, add link if it does).

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0
 - Browser: Chrome
 - Version 118.0.5993.117

**Additional context**
You can compare these two workflows:
https://workflowhub.eu/workflows/614
https://workflowhub.eu/workflows/484

In 614, creator Jorge Ejarque is not linked to his WorkflowHub profile. While in 484, once the creator is modified by hand, it links correctly to his account.

Besides, if you search in WorkflowHub for "Jorge Ejarque" it shows he has 3 related Workflows. But if you go to Jorge Ejarque's profile (https://workflowhub.eu/people/556), it only shows one workflow as related item.

**Comment by rsirvent** [comment]
Any feedback on this would be great, at least to know someone has read it.

**Comment by fbacall** [comment]
Right, the RO-Crate extraction does not currently attempt to match to any existing users.

Agree that matching on the ORCID would be a good solution and should be straightforward to implement

**Comment by rsirvent** [comment]
Any chance this could be implemented soon? It would be very useful when importing workflows with many authors. Thanks!

**Comment by rsirvent** [comment]
Thanks guys! Hope to see it deployed soon!!!!
