### ISSUE TITLE
Create an assay between two existing assays

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1656]
Feature that allows the user to create a new assay in between 2 existing assays or 1 assay and 1 study.
Feature can be developed in two stages:
1. Allow creation of new assay only between 2 existing but EMPTY assays (assay without samples)
2. Allow creation of new assay between 2 existing assays with samples: the user must re-establish connections between parents and children samples.

**Comment by NielsGeudens** [comment]
In test-DataHub, v1.15, I cannot add a new assay between two existing (empty) assays, nor between study sample and assay.  

Error message: _"1 error prohibited this isa assay from being saved
There were problems with the following fields:
[Sample type]: Linked sample attributes is invalid"_

To reproduce: starting from a ISA minimal study sample template and a ISA minimal material output assay, a feature button "insert a new assay" is present, which allows to define a new ISA assay, however, the above mentioned error message prevents from making the assay. Same applies to a new assay between two ISA minimal material output assays.
