### ISSUE TITLE
Implementing select2 for sharing permission project list: enhance searchability and ease of selection in lengthy lists

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#1702]
two places needs to be updated:

1. select projects when creating a resource 
![image](https://github.com/seek4science/seek/assets/42063448/527bd0a8-ca55-4870-9c1c-fe29f9951ae4)

2. assign permission to share with a project 
![image](https://github.com/seek4science/seek/assets/42063448/c7aeeb49-392d-429f-b8e3-df628e369fe7)

**Comment by whomingbird** [comment]
this issue is related to https://github.com/seek4science/seek/issues/1695

**Comment by stuzart** [comment]
you don't need to change (1) - that is already limited to the projects you are in. Just the sharing box needs updating, but also where you select the institution.

if (1) needs updating, it's a separate issue.
