### ISSUE TITLE
Store all workflows as RO crates

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#173]
A Workflow's content blob should always be an RO crate.

Ideally it should store them in their extracted state so relative paths can be easily resolved.

**Comment by alaninmcr** [comment]
How will this relate to non-workflow hub SEEKs?

**Comment by fbacall** [comment]
I don't think it will affect them. Although its an open issue about what to extent mainline SEEK should support workflows.

**Comment by fbacall** [comment]
test

**Comment by fbacall** [comment]
test2
