### ISSUE TITLE
ISA tags are editable in sample types with samples

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#1737]
When editing an existing assay, the ISA tag in the sample types are still editable.
- [ ] Users should not be able to change ISA tags in sample types that already have samples.
- [ ] The user should only see a relevant subset of ISA tags, depending on the derived template level.
- [ ] The validation process should be improved

**Comment by floradanna** [comment]
Check this [RAD](https://docs.google.com/document/d/1ByETT3mssb_Ng4VYPwSw7MlxfvRefKqsCcCZvgtUCXY/edit#heading=h.dopy7kwb8h4u) as reference

**Comment by kdp-cloud** [comment]
This issue has been resolved in PR #1749
