### ISSUE TITLE
Template creation

### ISSUE THREAD

**Issue by MichellePrk** [seek4science/seek#1755]
When creating a template that contains attributes using controlled vocabulary an error is given; 

500 We're sorry, but something went wrong with your request.

We've been notified about this issue and will be taking a look at it with some urgency.

**Comment by MichellePrk** [comment]
Related to this issue, I wanted to ask why the controlled vocabulary assigned to an attribute doesn't appear when you create a sample type from a spreadsheet. It seems as if you are only downloading the original spreadsheet when you use the batch upload of samples option. Am I missing something?

**Comment by stuzart** [comment]
Hi, sorry about your problem.
Creating a controlled vocabularly for a sample type directly from a spreadsheet is not something we can currently do, as it won't provide enough information. Although we need to look into the error, as it shouldn't fail but should at least created the attribute with the possibility of defining and associating a controlled vocab through the UI.

How are you defining the controlled vocabularly in your template that you are trying to base you sample type from ?

If you generated a sample type via the UI, including a controlled vocabularly attribute, a template will be generated for you which will contain the controlled vocab as a dropdown, and will support being extracted as a batch - via registering as a datafile and then selecting to extract samples.

**Comment by MichellePrk** [comment]
Apologies for the confusion. I wasn't clear. These are two separate but related problems. 

Firstly, when creating a template you can set the data type to controlled vocabulary, but there isn't an option to select or create a new controlled vocabulary. Trying to create a template using that data type for an attribute gives the error I described above.

So, instead of using the create template option, I tried to create a samples/metadata template by creating a new sample type. Here I am able to create an attribute and select a controlled vocabulary that I have created. This creates the template I expect if I add each attribute manually. 

The problem comes in when I use a spreadsheet template to create the sample type. Importing the template populates the list of attributes for me. I can set the attribute parameters and select a controlled vocabulary, where required. The sample type is created with all attribute parameters set. However, the template file that is downloadable, e.g. when creating samples by batch submission,  seems to simply be the original spreadsheet template I uploaded to create the sample type in the first place. There is no metadata sheet, and columns in the sample sheet don't contain the controlled vocabulary options I specified. Can you tell me why this happens and is there a way to create a SEEK from my own spreadsheet template?

**Comment by stuzart** [comment]
I'm still a little confused by the first scenario. Does this relate to the Templates that are part of the Single Page View, and feature that can be enabled in the admin settings but is off by default ? If so @floradanna may be able to help.

The second point though I understand. Currently, if a sample type has been created from a pre-existing spreadsheet, new templates won't be built even if the sample type subsequently changes. I've created an issue #1766 to give an option to override this and force a template to be built

**Comment by kdp-cloud** [comment]
Hi! Could you perhaps specify which version of SEEK you deployed?
If you are referring to the Templates that are used in the Single Page view, there was indeed [a bug](https://github.com/seek4science/seek/issues/1701) concerning controlled vocabularies that was addressed. It will be included in the next release of SEEK (1.15).

**Comment by MichellePrk** [comment]
Hi! We are using version 1.14.1 so that explains the error. Is there any way to delete templates that give the error after they have been created? They are listed when you browse templates but you can't access them to delete them.

**Comment by kdp-cloud** [comment]
I could reproduce the error and this is unfortunately a bug.

The easiest way to delete these templates, is to wait for the release of SEEK-1.15 and upgrade your installation. This will include the fix, making it possible for you to remove the template through the UI.

Apologies for the inconvenience!
