### ISSUE TITLE
Remove GUI to create ISA-compliant Templates from scratch

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1757]
Remove GUI to create  ISA-compliant Templates from scratch.
User of GUI can only create  ISA-compliant Templates starting from existing ISA-compliant Templates.

**Comment by kdp-cloud** [comment]
At the start of creating a new template, the 'Add new attribute' button is hidden, preventing the user from creating a template from scratch.

![Image](https://github.com/seek4science/seek/assets/82407142/1fb4979f-9285-4aff-a354-c760c5c3ac94)

Applying an existing template, reveals the button again. Users can add new template attributes if they want to!

![Image](https://github.com/seek4science/seek/assets/82407142/9d5a21b0-4954-4589-a702-1c76d7eebddb)

When editing an existing template, the button is also shown as well.

![Image](https://github.com/seek4science/seek/assets/82407142/18a54619-9235-41b1-8c9d-11c771f5f2bd)
