### ISSUE TITLE
Not possible to select project after first try to create a sample type

### ISSUE THREAD

**Issue by somathias** [seek4science/seek#1759]
**Describe the bug**
When creating a sample type and forgetting to select a project in the form on the first go, it becomes impossible to select a project again. 

Also happens for investigations on some instances, but not all. 
On Git revision: [2395946](https://github.com/seek4science/seek/commit/2395946a3f6992fb42923d042fe9054fa5de7847) (branch: main) reproduced for both sample types and investigations

**To Reproduce**
0. Be a member of at least two projects.
1. Go to 'Create' > 'Sample type'
2. Do NOT select a project
3. Click 'Create' and receive error message that project needs to be selected before sample type can be saved
4. Scroll down and see that project field is filled with string '{{ project.title }}'

**Expected behavior**
It should still be possible to select from the list of project titles. 

**Screenshots**
![image](https://github.com/seek4science/seek/assets/18682429/8c024b70-584e-4ccc-95fc-401ea3c5789d)

![image](https://github.com/seek4science/seek/assets/18682429/b6a521d4-a629-448a-8130-e895fd3375d5)

**Comment by stuzart** [comment]
it's being caused by a javascript error at:

```// Auto select projects from params[:project_ids] or params[resource][:project_ids] if this is a new object
          Sharing.projectsSelector.add(, true);
    // Auto select project if there is only one
    if (Sharing.projectsSelector.possibilities.length === 1 &&
        Sharing.projectsSelector.selected.length === 0) {
      Sharing.projectsSelector.add(Sharing.projectsSelector.possibilities[0].id, true);
    }```

the line `Sharing.projectsSelector.add(, true);` should include the project_id, but is blank.

This is generated here: https://github.com/seek4science/seek/blob/main/app/views/projects/_project_selector.html.erb#L125

implying that an empty element is ending up in the `project_ids` params
