### ISSUE TITLE
Deletion of CV term in use as sample title

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#1774]
**Describe the bug**
If sample title is CV term, and the CV term is deleted, the sample cannot be selected and therefore it cannot be deleted nor edit it.

**To Reproduce**
1. Go to DataHub-test

**Expected behavior**
Options:
1. if deletion of CV term "in use" is allowed
2. sample that uses the CV term as title should be editable or deletable

![Image](https://github.com/seek4science/seek/assets/51486716/0661f312-ac24-4f9a-b9ba-c2177b74b0a6)

![Image](https://github.com/seek4science/seek/assets/51486716/3d19af2b-a5b0-4ebd-9447-02db7924da4d)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kdp-cloud** [comment]
@floradanna @NielsGeudens 

I can't reproduce the same behavior on our test instance, based on the information you gave me.
When I delete the term used as a sample title. I can still delete the sample, no problem. I can also edit the sample but I can't save the changes unless I choose a valid CV term as sample title. This looks like correct behavior to me.

Could you point to the resource where this problem occurs?
