### ISSUE TITLE
Issues when mapping Galaxy toolshed to bio.tools

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#1821]
Spaces in tool name:
```json
          {
            "value": "GA4GH Beacon",
            "reftype": "bio.tools"
          }
```
...the actual bio.tools ID is `GA4GH_Beacon`

Comma-separated tools:
```json
          {
            "value": "graphclust, GraphClust2",
            "reftype": "bio.tools"
          }
```
...`graphclust` and `GraphClust2` are both valid bio.tools ID, so we need to link the Galaxy tool to multiple bio.tools entries

**Comment by supernord** [comment]
hey @fbacall 
the first one is a metadata issue - if you haven't already, I can generate a PR against that tool wrapper with the fix?

**Comment by fbacall** [comment]
> hey @fbacall the first one is a metadata issue - if you haven't already, I can generate a PR against that tool wrapper with the fix?
Sounds good!

**Comment by hexylena** [comment]
The second one is also definitely an issue, we've started linting that they're valid identifiers, that's not valid as far as galaxy is concerned. The wrapper should be fixed there too

**Comment by supernord** [comment]
https://github.com/galaxyproject/tools-iuc/pull/5951
