### ISSUE TITLE
Templates appear under related items even if disabled

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1822]
Noticed with a fresh installation ...

![image](https://github.com/seek4science/seek/assets/201658/ee2748be-c111-4deb-98c6-e93feeaf29b2)

shows when `Compliance with ISA-JSON schemas enabled` is disabled. It's probably checking for `templates_enabled`

**Comment by floradanna** [comment]
good catch!

@kdp-cloud why are they still called "templates" instead of "experiment sample templates"?
![Screenshot 2024-04-10 at 16 47 30](https://github.com/seek4science/seek/assets/51486716/582ef6f6-fdc7-4cb0-acdf-38857c35e10d)
