### ISSUE TITLE
Publications in SEEK (licenses)

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#1859]
Almost all (?)   publications in SEEK are uploaded (or just presented) under  this license : "[No license - no permission to use unless the owner grants a licence](https://choosealicense.com/no-permission/)"

, which contradicts the corresponding publisher's original licenses

example  https://fairdomhub.org/publications?filter%5Bproject%5D=99&view=table  or filke attached (screen shot)If one register publication, there is no chance to define license .... at least not if registering PubMed ID or DOI - so where is this shown licence from?

Kind of default? bug?  why do we need to define licence in SEEK for papers published under CC ?

**Comment by OlgaKrebs** [comment]
![JIRA_License_Public](https://github.com/seek4science/seek/assets/55085007/16c81b85-712a-4397-b879-9a7e83cb0bd6)

**Comment by stuzart** [comment]
Generally they don't have licenses, and I think it is a bug that they are listed as a column in the index page.
To support a requirement at HITs there was a need to upload unpublished publications, and in those cases they perhaps should have a licence. That work required some other changes such as permissions and an associated file, so the appearance of license in the table was probably inheretied from there.

License doesn't seem to appear in the general show page or in the API, so looks like it just needs removing from the index page

**Comment by fbacall** [comment]
It's a default, and it's a bug that the license is shown. It should be hidden in all views

**Comment by whomingbird** [comment]
the license is only shown in the "table view", not in the "default" and "condensed" view for publication.
