### ISSUE TITLE
add a button on each asset page to send an email to the contributor to show the interest in the asset

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#188]

**Comment by whomingbird** [comment]
similar to the function below. 
<img width="1522" alt="Testupload 2020-03-18 11-47-17" src="https://user-images.githubusercontent.com/42063448/76953023-4d909100-690e-11ea-8356-57b8d6733a97.png">

**Comment by alaninmcr** [comment]
The purpose of this is not clear to me. Is it only for when the asset is not downloadable?
