### ISSUE TITLE
Template creation if non-administrator

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#1880]
A User cannot create templates unless he administers at least 1 project. Any user should be able to create a template, regardless if the user is administrating anything.

**Comment by kdp-cloud** [comment]
@floradanna I found the cause of this behavior. But it explicitly says you need to be instance admin or a project admin.
https://github.com/seek4science/seek/blob/5cffb9a536f15cd631900353c53c7c78b53c93fe/app/models/template.rb#L28
Do you want me to revert that?

**Comment by floradanna** [comment]
I am checking old notes before I can answer. @NielsGeudens what do you think.
What I can say is that if only admin can create template, they must be admin of that specific project (not admin of any project). So, in case, project admin can create templates only for the projects they administer.
