### ISSUE TITLE
Sample type permissions for project members

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#1890]
The current logic for editing sample types states that only project administrator, instance administrators or its contributors can edit sample types. This is perfect for project sample types but not for the ISA-JSON sample types linked to a study or assay. Even if the user has editing rights to a study or assay, the user will not be able to edit its sample type.

For the ISA-JSON compliant sample types, the logic should be: if the user has editing permissions to the assay or study, he should have the same permissions for editing the linked sample type.

As of today, sample types don't have their own set of permissions. So as an intermediary solution, ISA-JSON compliant sample types should be editable for project members as well, assuming if the user has editing permissions to a study or assay, the user is also a project member.

**Comment by NielsGeudens** [comment]
Current behavior in test-DataHub: 
User can only edit sample types which are associated with a project for which the user is project admin. 
In case the user has managing rights in the project, he/she can still not edit the sample type.
