### ISSUE TITLE
Search Function Issue

### ISSUE THREAD

**Issue by anneelinh** [seek4science/seek#1965]
**Describe the bug**
The search function on the page does not return results when typing and trying to search for "Thy-1". This should give a result as it is a part of the header of this publication (https://seek.lisym.org/publications/431). However, if you copy paste the the word from the publication it can find it. So there seems to be a problem with different hyphens being used.

**To Reproduce**
1. Enter "Thy-1" in the search bar and press enter.
2. Note that no results are returned.
3. Copy/paste "Thy‐1" from the header of the publication (see above) in the search bar and press enter.
4. Note that relevant results are returned.

**Expected behavior**
The search function should return the same results for both typing "Thy-1" and for copy/pasting "Thy‐1" from the publication.

**Screenshots**
![image](https://github.com/user-attachments/assets/f69bb0cc-dd5d-4ccf-9db0-80ee9ceb8b0f)
![image](https://github.com/user-attachments/assets/38eb43ed-58ee-4f56-9c3a-87ba17fc4850)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 126.0.6478.182

**Comment by stuzart** [comment]
The hyphen `-` in the title is not the same character as the '-' you would type, it's a funny unicode character. It's actually `Thy&#x2010;1`
