### ISSUE TITLE
Permissions as project member not applied

### ISSUE THREAD

**Issue by NielsGeudens** [seek4science/seek#1980]
# Short introduction
In the production instance of DataHub, admin grants members of a project viewing permissions for datafile, samples and sample types.  Samples, belonging to a sample type, were extracted from a datafile.
Bug: User cannot view the samples or data files, even though they are registered members of the project. They do have access to the sample types.

# More information
## Applied permissions
 
![image](https://github.com/user-attachments/assets/aebfd9e5-189b-4dae-a9ea-461777d7a777)
Figure 1: Screenshot of the **admin** account, showing that members of the project ("deCYPher Composable Elements") have view + download rights for the datafiles (here shown for datafile "Protein_datafile_072024").

 
![image](https://github.com/user-attachments/assets/0b5a0727-c395-4a66-a6c0-9cc4c7739d9c)
Figure 2: Screenshot of the **admin** account, showing that members of the project ("deCYPher Composable Elements") have viewing rights for the sample(s) (here shown for sample "ug_st0001").
 
![image](https://github.com/user-attachments/assets/70245c05-7a9c-4683-aee1-5d835af70c96)
Figure 3: Screenshot of the **user** account of Flora, showing that they are indeed member of the project ("deCYPher Composable Elements").

## User experience
‘Niels User’ is member of the project. Project members get viewing access to the samples from ‘Niels Admin’:
•	If ‘Niels User’ is member of the project, all sample types and samples are visible 
•	If ‘Niels User’ is removed as a member from the project, everything is hidden 
•	Making a member again, makes everything (data files, sample types, samples) visible again 
•	So => Expected behavior 

With the exact same settings, users Flora and Bert (both member of project) experience the following : 
•	No access to datafiles
•	Access to sample type
•	No access to samples. 
Even when specific permissions are shared with Flora as a person (not just as member of project) for the samples and/or datafiles, the experience remains the same. 
 
![image](https://github.com/user-attachments/assets/7d29cffe-2634-442d-b5fa-6a637280bdfd)
Figure 4: Screenshot of the **user** account, showing the message "there are no samples available to be displayed".

 
![image](https://github.com/user-attachments/assets/e96565b8-c026-41f0-862c-847f62f06c16)
Figure 5: Screenshot of the **user** account, showing that samples types (4 in total) are accessible to the user, but no samples (0+199).

The same behavior could not be reproduced in the sandbox instance of DataHub.

**Comment by stuzart** [comment]
This could be related to the issue @floradanna reported with authlookup jobs failing. It's not mentioned here, but Flora or Bert might be able to access and view the data files and samples indiviudally, but if that job hasn't run successful then list views may not show them

**Comment by NielsGeudens** [comment]
Unfortunately, Flora and Bert cannot view individual samples either..
