### ISSUE TITLE
Add an external_identifier field to all ISA and Asset objects, including samples

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1984]
Using a `has_external_identifier` Concern, add the field to appropriate models. No need to be present in the UI or API for the time being.

the external_identifier should be optional, but if present be uniq within the scope of the associated projects.

Update the import from FAIR Data Station behaviour to also set the appropriate external_identifier's.

Models to update are:

- Investigation
- Study
- Assay
- Observation Unit
- Data file
- Model
- SOP
- Presentation
- Workflow
- Document
- Sample
- Strain

Not currently necessary for Collections or Publications

**Comment by stuzart** [comment]
also add for Publications and Collections afterall, since they should conform to `acts_as_asset` and there is no strong reason to exclude them

**Comment by jjkoehorst** [comment]
Need to create an issue to ensure that the “ontology” in the fairds is in sync with seek requirements. I am thinking of implementing linkml but have to see how well that works out.

**Comment by stuzart** [comment]
> Need to create an issue to ensure that the “ontology” in the fairds is in sync with seek requirements. I am thinking of implementing linkml but have to see how well that works out.

I'm not entirely clear what you're referring to, but perhap something to discuss in our next meeting.
