### ISSUE TITLE
Contact details of a person should be visible on the profile page of the person for all individuals who have permission to see it.

### ISSUE THREAD

**Issue by anneelinh** [seek4science/seek#1988]
**Describe the bug**
Contact details of a person should be visible on the profile page of the person for all individuals who have permission to see it. At the moment this information is only visible to other people with whom you share a Project or Programme. System administrators have access to this information, but cannot view it on the profile page, but only via Actions -> Edit Profile.

**To Reproduce**
1. Have a user which is an administrator.
2. Find another user which does not share a Project or Programme with your user.
3. Visit their profile and see that their contact details are not visible to you.
4. Click Actions -> Edit profile, and see that the information is visible there.

**Expected behavior**
A system administrator and others with the correct permissions should be able to view the contact details of a person directly on their profile page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 128.0.6613.113

**Comment by stuzart** [comment]
so if a user, generally the systems admin, has permissions to edit a profile and therefore see the contact details, then they should automatically be visible on the profile page. 
That should be fairly straight forward to change.

**Comment by stuzart** [comment]
One exception, is that there is a setting to always hide contact details ..

![image](https://github.com/user-attachments/assets/c56d3a23-6dbe-4c23-89a9-5cb57af1b4a1)

if this is set, it should still hide the details for the sys admin even though they could still possibly see them by editing. The reason being is that I think it could be confusing for the sys admin to change this setting, but then also be able to see them - which could lead to thinking the setting doesn't work.
