### ISSUE TITLE
DOI not shown (reported to support by owner Kolodkin)

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#199]
DOI created before not shown on https://fairdomhub.org/models/693?version=1  model page

**Comment by fbacall** [comment]
Will look into this. The DOI was definitely created because there is a log entry:
```
#<AssetDoiLog id: 200, asset_type: "Model", asset_id: 693, asset_version: 1, action: 1, comment: nil, created_at: "2020-03-27 19:46:33", updated_at: "2020-03-27 19:46:33", user_id: 727, doi: "10.15490/fairdomhub.1.model.693.1"> 
```

And the DOI is functional: https://doi.org/10.15490/fairdomhub.1.model.693.1

**Comment by fbacall** [comment]
Can't seem to reproduce this, but I've fixed it for that model.

Will leave the issue open in case it happens again
