### ISSUE TITLE
Enhance UI to Better Display Control Vocabulary Attribute Values with IRI References

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#1991]
![image](https://github.com/user-attachments/assets/e476c43a-b4d6-4c4c-98fc-52ae755bedb7)

The current controlled vocabulary (CV) values associated with ontology terms are displayed as plain text. We would like to enhance these by converting them into hyperlinks, pointing to their respective ontology term URLs. This will improve usability by allowing users to easily access detailed information about the ontology terms.

from Biomedical science (http://edamontology.org/topic_3344)  to [Biomedical science](http://edamontology.org/topic_3344)

**Comment by stuzart** [comment]
bear in mind that the ontology identifiers may not always be resolvable URLs, or may just resolve to an OWL xml file. Might be better to make the hyperlinks point to a reference in the OLS

**Comment by stuzart** [comment]
> Is it currently supported in SEEK to define an `iri` that points to an OWL XML file or non-resolvable URLs? [ reference](https://github.com/seek4science/seek/blob/seek-1.15/config/default_data/data-annotations-controlled-vocab.json)

yes, the iri dependes on the the ontology and what was chosen for the term id iri. An IRI isn't a URL, `fred:blogs` is a valid IRI, as is `chebi:1234` or `taxon:1234`. So you can't rely on the ontology using resolvable urls.

http://edamontology.org/topic_3344 only resolves becomes somebody has taken the effort to setup a redirect to bioportal, but they didn't have to do so.

**Comment by stuzart** [comment]
here is an example of a term that resolves to an owl.xml file: https://www.ebi.ac.uk/ols4/ontologies/enm/classes/http%253A%252F%252Fwww.bioassayontology.org%252Fbao%2523BAO_0000015

( http://www.bioassayontology.org/bao#BAO_0000015 )

**Comment by stuzart** [comment]
> here is an example of a term that resolves to an owl.xml file: https://www.ebi.ac.uk/ols4/ontologies/enm/classes/http%253A%252F%252Fwww.bioassayontology.org%252Fbao%2523BAO_0000015
> 
> ( http://www.bioassayontology.org/bao#BAO_0000015 )

or a better link to the ontology itself, where all terms to: https://www.ebi.ac.uk/ols4/ontologies/bao
