### ISSUE TITLE
 System Admin has right to create, manage (enable, disable), and delete extended metadata types via user interface 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#1999]
related [issue](https://github.com/seek4science/seek/issues/1747): Feature request: Management of Extended Metadata via Frontend #1747

- [x] as a SEEK instance administrator, you have the ability to create, manage (enable, disable), and delete extended metadata types. 

- [x] on the "Manage Extended Metadata Types" page, you will see a list of existing extended metadata types along with relevant resources for creating new ones.

- [x] you can upload a JSON file through the Admin Area UI to create the metadata type.

**Comment by carlosvega** [comment]
I wonder about editing/updating extended metadata types. For instance, what's the recommended procedure if we want to add one new field to a extended metadata template?
