### ISSUE TITLE
Feature request: Additional properties for Investigation/Study/Assay/Data files

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#20]
We have an internal excel sheet to capture information related to samples which map to a study, because we can have multiple assays on the same sample (e.g. DNA/RNA sequencing, proteomics, metabolomics, microscopy, etc..).

In this case a sample has a location (long/lat), environment, country, biosafety level...

It would be nice if we can capture these fields within the SEEK environment so that users can add additional fields to the corresponding studies, which, we think is currently not possible?

**Comment by stuzart** [comment]
We are currently working on a system, that allows user defined custom samples, with arbitrary fields and attribute types. It also allows a sample type to defined with a spreadsheet template, which can later be filled out and automatically extracted into SEEK. 

Is this along the lines of what you are looking for?

**Comment by stuzart** [comment]
I should have added that the samples can also be linked to an Assay in SEEK

**Comment by jjkoehorst** [comment]
I think this should indeed fit our needs. This would allow us to capture and store the information in SEEK which we now capture using the excel sheets.

**Comment by stuzart** [comment]
Sample changes seem to solve the issue, can reopen if they don't
