### ISSUE TITLE
undefined method `label' for nil:NilClass in method `seek_cv_attribute_display`

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#2002]
When sample routes are accessed, this error is thrown:

```
An ActionView::Template::Error occurred in samples#show:

  undefined method `label' for nil:NilClass

      term.label
          ^^^^^^
  app/helpers/samples_helper.rb:185:in `seek_cv_attribute_display'
```
Probably caused by:
https://github.com/seek4science/seek/blob/41337acfefd729435f4329eda12fe428459b433a/app/helpers/samples_helper.rb#L177-L187

**Comment by whomingbird** [comment]
is this bug fix related to your probelm?  https://github.com/seek4science/seek/commit/b8d0d35978c7bd68e16a814750901fca27d79645

**Comment by kdp-cloud** [comment]
@whomingbird The error seems to occur when free text in a controlled vocabulary is allowed. In that case `term` resolves to `Nil` and raises an exception.

If free text is allowed, it should simply return the value. What do you think?
