### ISSUE TITLE
Internal links breaks when running SEEK on suburi

### ISSUE THREAD

**Issue by AndrewWood94** [seek4science/seek#2042]
When running an instance of SEEK through a suburi there are a couple of instance where internal links break as they only reference the root path, without the subdirectory. 
Examples are set up here to demonstrate:
1) [Make a Snapshot of an investigation](https://testing-suburi.fairdomseek.org/seek/investigations/2
)

2) [Navigate to Sample through column 1 when viewing datafile samples](https://testing-suburi.fairdomseek.org/seek/data_files/3/samples?graph_view=tree)

**Comment by fbacall** [comment]
For the sample table case, the relative URLs are being hard-coded in the Javascript. We should either generate the URLs in the Ruby code and pass them into the JS to render directly, or use this variable: https://github.com/seek4science/seek/blob/61bb837a5d649eb922c152cdcd7ffb8b0a78f438/app/assets/javascripts/application_shared.js.erb#L424
