### ISSUE TITLE
Not clear how to reference a Galaxy workflow

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#206]
If you have a Galaxy workflow on a wesbite [example]( https://usegalaxy.org/u/rajithadp/w/braca2---primer-design ) then it is possible to download the workflow to a .ga file. That .ga file can then be uploaded to workflowhub.

However, it is not clear how to reference the workflow. If you simply link to the HTML page, then workflowhub attempts to upload the HTML and (reasonably) fails. You can reference the download link, but then there is no obvious way to see the original workflow.

So it seems workflowhub does not currently support referencing a Galaxy workflow

**Comment by fbacall** [comment]
This is the code that handles GitHub URLs:
https://github.com/seek4science/seek/blob/master/lib/seek/download_handling/github_http_handler.rb

deciding which handler to use:
https://github.com/seek4science/seek/blob/master/app/models/content_blob.rb#L238

deciding which template to use:
https://github.com/seek4science/seek/blob/master/lib/seek/upload_handling/examine_url.rb#L39

the template that is shown to the user:
https://github.com/seek4science/seek/blob/master/app/views/content_blobs/examine_url/_github.html.erb

how it looks:
![image](https://user-images.githubusercontent.com/503373/78650974-8f7e7880-78b7-11ea-9b8b-659b70264e09.png)

**Comment by telukir** [comment]
In the example image under URL field it is not a workflow link right? Should workflowhub expect any kind of link and workflowhub should verify if it is a workflow link or not right?

**Comment by fbacall** [comment]
No, that's just a random file that I chose as an example.

I think checking if it's a workflow or not should happen later.
