### ISSUE TITLE
API returns blank page

### ISSUE THREAD

**Issue by dgslos** [seek4science/seek#2077]
Hi,

I installed seek locally on a server for testing purposes. At first, I got response from the api page, showing the API documentation. After reinstall, the page appears blank without any error (see below).

```
dslos@genomics2:/srv/rails/seek$ bundle exec rails server
=> Booting Unicorn
=> Rails 6.1.7.8 application starting in production http://0.0.0.0:3000
=> Run `bin/rails server --help` for more startup options
I, [2024-11-27T16:57:14.845572 #1924220]  INFO -- : listening on addr=0.0.0.0:3000 fd=11
I, [2024-11-27T16:57:14.845757 #1924220]  INFO -- : worker=0 spawning...
I, [2024-11-27T16:57:14.857298 #1924220]  INFO -- : master process ready
I, [2024-11-27T16:57:14.860509 #1925039]  INFO -- : worker=0 spawned pid=1925039
I, [2024-11-27T16:57:14.861356 #1925039]  INFO -- : worker=0 ready
I, [2024-11-27T16:57:22.628281 #1924220]  INFO -- : SIGWINCH ignored because we're not daemonized
I, [2024-11-27T16:57:26.188992 #1924220]  INFO -- : SIGWINCH ignored because we're not daemonized
I, [2024-11-27T17:02:51.589452 #1924220]  INFO -- : SIGWINCH ignored because we're not daemonized
```

I'm on Ubuntu 22.04.5 LTS, tried both chrome and firefox.

![image](https://github.com/user-attachments/assets/b9eb6cca-477e-4600-a40e-92d421581c37)

Any ideas?

Dieter

**Comment by kdp-cloud** [comment]
Hi @dgslos ,

Do you allow your browser to execute JavaScript? Can you check in your security settings?
In chrome the setting is in Privacy and security > Site settings > JavaScript.
There you should select 'Sites can use JavaScript'.

**Comment by dgslos** [comment]
Hi, that setting is enabled. So that is not the reason.

**Comment by stuzart** [comment]
do you get any javascript errors ?

also, you could check if `public/api/definitions/openapi-v3-resolved.yaml` exists, and if so try deleting it - it will be recreated when restarting the server.

**Comment by dgslos** [comment]
I'm getting these:
GET http://localhost:3000/api/scripts/redoc.standalone.js net::ERR_ABORTED 404 (Not Found)
api:1 Refused to execute script from 'http://localhost:3000/api/scripts/redoc.standalone.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by fbacall** [comment]
What happens if you visit http://localhost:3000/api/scripts/redoc.standalone.js directly in your browser?

**Comment by dgslos** [comment]
![image](https://github.com/user-attachments/assets/bf05f61b-e5bb-4663-9992-ab5c222ae593)

**Comment by fbacall** [comment]
I see you are running in the `production` environment. If this is intentional, and you are not using a web server in front of Rails (apache, nginx etc.) you need to tell Rails to serve static files itself e.g.
```
RAILS_SERVE_STATIC_FILES=true bundle exec rails s
```

**Comment by dgslos** [comment]
Yes! That fixes it :)
