### ISSUE TITLE
Extended metadata with spaces in title

### ISSUE THREAD

**Issue by kdp-cloud** [seek4science/seek#2079]
Currently in SEEK the extended metadata type's title has to be snake case if you are using linked extended metadata attributes. If this is not the case the JavaScript functionalities tied to the 'add new' button do not work.
The extended metadata type's title has to be converted to snake case in order to make it work with the javascript.

**Comment by whomingbird** [comment]
JavaScript will fail to find an ID string containing whitespace. [This](updated.https://github.com/seek4science/seek/blob/main/app/views/extended_metadata/_fancy_linked_extended_metadata_multi_attribute_fields.html.erb#L8) line needs to be updated
