### ISSUE TITLE
Forgot Password Link Not Sending Reset Email

### ISSUE THREAD

**Issue by methi-adt** [seek4science/seek#2098]
Hi, I’m encountering an issue with the “Forgot Password” link on SEEK. When I click it to reset my password, I don’t receive any reset email. As the server admin, I ensured that email notifications are set up and enabled, and tested this with a few different user profiles, but no reset email is received in any case.

**Comment by methi-adt** [comment]
Thanks for the quick response! The immediate test email is received but not the queued one. On checking the job queue I see that there are almost 4000 delayed jobs waiting + ~800 items waiting in queues. They don't have any links associated so I'm not sure how to cancel them or clear the queue. I assume this could be a problem with background tasks - if so, could you briefly guide me on how to restart them safely?

**Comment by stuzart** [comment]
If you are using docker, then just being the containers down and then backup again should get the workers running again.

If you've done a standard installation, then there is a rake task that starts the workers. If running in production mode this would be:

    RAILS_ENV=production bundle exec rake seek:workers:start

if not in production but development mode, just remove the `RAILS_ENV=production`. For a production installation I'd recommend creating a service, are there are some instructions here: https://docs.seek4science.org/tech/install-production.html#delayed-job-background-service

**Comment by methi-adt** [comment]
Stopping and re-starting the workers with the rake task seems to work - thank you!

**Comment by methi-adt** [comment]
Stopping and re-starting the workers with the rake task seems to work - thank you!
