### ISSUE TITLE
Ability to provide links to external discussion forums for an individual asset

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#222]
When registering an asset, allow an optional set of external links to public forums such as a google group or github issues to allow a discussion to be held about that item. Only show the link if it has been provided.

**Comment by stuzart** [comment]
Links should be validated to check they are valid URLs

**Comment by whomingbird** [comment]
add the discussion link to the API of assets.

**Comment by alaninmcr** [comment]
I still do not think that the discussion link should be limited to assets. What is people want to discuss a Project?

**Comment by stuzart** [comment]
the api has been moved to issue #248 to be completed in a separate phase
