### ISSUE TITLE
Sample columns can map to the same data

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#238]
If a sample type's fields are called, for example, A+B, A-B, A&B then those three columns will actually map to the same data in the database. So whichever field is specified last will (appear to) overwrite the other two fields.

This could be extremely dangerous and needs to be fixed

**Comment by alaninmcr** [comment]
The commit works round the issue, rather than solving the fundamental problem.

**Comment by stuzart** [comment]
I agree with @alaninmcr . This commit doesn't really solve the problem. The encoding needs changing to support similar attribute names.

**Comment by stuzart** [comment]
I feel this can be fixed as part of the alignment and refactoring for the Custom Metadata work #240 . The current fix that @fbacall has applied is good for 1.10.0 version
