### ISSUE TITLE
Treeview

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#243]
- [x] Determining the javascript library for the tree view
- [x] Link the Document types to existing Assets
- [x] Being to able to add an existing Asset to a folder
- [x] Being able to add a new item
- [x] Show the existing upload page
- [x] Show the existing box in a Modal dialogue
- [x] Show the file count for a folder
- [x] Look re-using the existing project folders

**Comment by floradanna** [comment]
Done
