### ISSUE TITLE
Support for Markdown in descriptions

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#244]
Ability to format with Markdown, e.g. as used for github README.md

Could have a WYSIWYG preview, there are plugins to support this

Need to be careful not to break text that currently includes simple HTML tags

To start with, just include for item descriptions, but in a generic way that could be applied elsewhere

**Comment by fbacall** [comment]
See also: #430

**Comment by aapaolaza** [comment]
I removed the spell checker, as it doesn't support non-american English. Alternatively, we could consider using another library to highlight spelling mistakes on all form inputs.
