### ISSUE TITLE
Unable to remove myself from the list of Creators

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#246]
I appear in the list of creators for an item I am the contributor for. When I remove myself, and then click update, I still appear in the list when refreshing.

Either the changes aren't being saved, or I am automatically being reinserted.

**Comment by fbacall** [comment]
#176

**Comment by stuzart** [comment]
related but slightly different. This case isn't recording the change even if you remove yourself from list

**Comment by stuzart** [comment]
ok, it does seem to be the same as #176 and refuses to remove the last person, regardless of whether it is yourself or not.

**Comment by alaninmcr** [comment]
Does it refuse even if there are non-registered creators?

**Comment by stuzart** [comment]
no, they aren't affected

**Comment by stuzart** [comment]
It isn't that the last person isn't removed, it is that the creator id's are ignored if the list is empty, so if there are 3 and I remove them all, after the update all 3 remain. the creator_ids param is filtered out if the array is empty.
