### ISSUE TITLE
Single page design for project

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#264]
- [x] Ability to create investigations and studies via the TreeView
- [ ] @stuzart - Revisit how the data file modal box  
- [x] Modal box to create Study
- [x] Modal box to create Investigation
- [x] Display items in the tree view and show details when selected 
- [x] Add data file upload wizard

**Comment by alaninmcr** [comment]
Have you had a look at the spreadsheet populator we are doing for IBISBA?

https://docs.google.com/presentation/d/1j4Iy0s2pVfnme1Dsazkq2Zxg_H1bowPC-8sxfjm8kvc/edit?usp=sharing

**Comment by vdkkia** [comment]
Bulk Investigation/Study/Assay creation. Nice idea.
Have you made use of the API for bulk creation?

**Comment by alaninmcr** [comment]
No - it uses the Rails/Ruby classes directly
