### ISSUE TITLE
Condensed view for asset lists

### ISSUE THREAD

**Issue by Golebiewski** [seek4science/seek#269]
Improvement of the user interface: A condensed view for the assets (only title, project and creators, contributors or authors) when listed (e.g. https://fairdomhub.org/data_files, https://fairdomhub.org/models, https://fairdomhub.org/sops, https://fairdomhub.org/publications, etc.) would be helpful for the users to neatly arrange the lists. The condensed view then could be expanded by the user (+/- for each single asset, as well as for all assets shown on a page).

**Comment by OlgaKrebs** [comment]
yes, very agree - most common user requirements - to improve views/lists if navigating

suggest to remove creators/contributors fotos from lists

**Comment by alaninmcr** [comment]
Also supported by IBISBA users

**Comment by aapaolaza** [comment]
Trying to get a clear understanding of this issue. You mean give an option for a condensed version of the current list of "result cards" for each of the items (publications, models, sops...).

So we would have:
- the current option including creator images
- a condensed list (that would allow the user to see more elements at once, and give the "+" option for more details)
- a table view of all the results, as described in #271 

We would use a view switcher as in the current "ISA Overview" (https://fairdomhub.org/data_files/3853) where you can switch between Tree and Graph views.

**Comment by aapaolaza** [comment]
Summary of suggestions:
- [ ] Column ordering:
    - [ ] Change default ordering (when available title should go first)
    - [ ] Add custom sorting for users (drag and drop sorting for the dropdown column selection?)
- [ ] Change default limit for number of records when in condensed and table view
