### ISSUE TITLE
A nil error when attempting to get data files for a project, using the 'include' parameter

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#277]
e.g when attempting to get /projects/12.json?include=data_files an error is triggered:

> A NoMethodError occurred in projects#show:
> 
>   undefined method `[]' for nil:NilClass
>   app/serializers/contributed_resource_serializer.rb:80:in `version_number'
>

**Comment by alaninmcr** [comment]
What machine is this on? I tried on fairdomhub and cannot replicate.
