### ISSUE TITLE
Combine Request Contact and Request Resource buttons and use MessageLog

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#280]
They are so close to doing the same thing, they could be combined. 
Requesting access to a resource could be acheived by requesting contact, and asking.

The Request Contact should also be integrated with MessageLog and a time frequency applied.

**Comment by whomingbird** [comment]
have a look at how the project join request uses the MessageLog to restrict the frequency of requests to every 12 hours

**Comment by stuzart** [comment]
I gave it a test at https://testing.fair-dom.org - and my only comments are that

- The user provided text isn't easily distinguished from the rest of the email body. Perhaps could be quoted, or indented slightly
- At first I found it odd I could request contact with myself and was going to suggest hiding the button if the current user would be one of the recipients; but with further thought maybe useful for contacting the other creators or submitter.
