### ISSUE TITLE
Date/Time selection boxes appear at the bottom of the page

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#348]
This affects the Events and Announcement page. When selecting the date field, a selection box pops up to help select the date and time in the right format, but the box now appears at the bottom of the page and is invisible unless you scroll down

**Comment by fbacall** [comment]
There is this error in the console:
 `Error: datetimepicker component should be placed within a non-static positioned container`

**Comment by stuzart** [comment]
fixed by wrapping in a non-static position:relative block, and also updated some unaffected input elements. slight puzzle why some cases are effected now, but not others.

**Comment by stuzart** [comment]
sample attributes are still affected
