### ISSUE TITLE
"Submitter" shown more prominently than "other creators"

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#350]
The submitter always has an account in SEEK, so their avatar is shown on the right-hand side panel at the top, with the list of "other creators" below. This might give the impression that the submitter is more important.

![image](https://user-images.githubusercontent.com/503373/85391419-0d126600-b542-11ea-81a0-a57bc3102d73.png)

It should maybe be moved underneath.

**Comment by fbacall** [comment]
Possible change:
![image](https://user-images.githubusercontent.com/503373/85559616-c72ccf00-b621-11ea-9012-0e9a0b458897.png)

**Comment by stuzart** [comment]
I like the suggested change above

**Comment by whomingbird** [comment]
I really like the new layout, it is much clearer.
