### ISSUE TITLE
Duplication of code for name normalization

### ISSUE THREAD

**Issue by nwoetzel** [seek4science/seek#36]
In 'lib/seek/grouped_pagination.rb' and 'app/controllers/publications_controller.rb' there is some code for string normalization/transliterate:

``` ruby
        #handle the characters that can't be handled through normalization
        %w[ØO].each do |s|
          text.gsub!(/[#{s[0..-2]}]/, s[-1..-1])
        end

        codepoints = text.mb_chars.normalize(:d).split(//u)
        ascii=codepoints.map(&:to_s).reject{|e| e.length > 1}.join
```

There are some post on the internet discussing some normalization, first of all [active_support's transliterate](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-transliterate)
also this [normalization article](https://makandracards.com/makandra/9483-normalize-characters-in-ruby) which suggests

``` ruby
string.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
```

One could discuss if for names of Persons (or authors) some canonical name (first, last) could be stored in addition to the actual name, so that active_record queries would have more hits.

**Comment by stuzart** [comment]
Moved to JIRA: https://jira-bsse.ethz.ch/browse/OPSK-1018
