### ISSUE TITLE
Add and edit attributes

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#362]
**User Story ID: 12.0**
As PhD student, I want to add and edit attributes to my Study and Assays any time I need to, so that I can edit attributes that were wrong or add attributes that I forgot because they were not important before.

**Acceptance Criteria**

**Definition of Done**

**Comment by kdp-cloud** [comment]
Description of feature:
[RAD 6 - Epic 6.5](https://docs.google.com/document/d/1vuuvGqAO2mPlSa7-IDa57awcC86eMrlQ38FAy0zicro/edit#heading=h.u3jbo9p4b1dp)
