### ISSUE TITLE
Option to export spreadsheet as template or use dynamic table

### ISSUE THREAD

**Issue by floradanna** [seek4science/seek#369]
**User Story ID: 14.0**
As PhD student, I want to choose whether export my metadata template as spreadsheet or fill it in online, so that I can copy paste data from other spreadsheets.

**Acceptance Criteria**

**Definition of Done**

**Comment by alaninmcr** [comment]
The online spreadsheet editing was also requested by IBISBA, in particular for the population spreadsheet that specifies a project's ISA structure (for IBISBA).

**Comment by floradanna** [comment]
I actually mean spreadsheet or dynamic table online in SEEK for describing/creating samples, specifically.

**Comment by floradanna** [comment]
Exporting sample type as spreadsheet template.xls containing CV list is possible in default view. It is not possible in Single Page because sample type created via Single Page are hidden in the GUI.

Work on implementing excel export for Single Page dynamic tables.

**Comment by rabuono** [comment]
Being tackled in issue #1359
