### ISSUE TITLE
Model.find_each preferred over Model.all.each

### ISSUE THREAD

**Issue by nwoetzel** [seek4science/seek#37]
It seems that Model.all.each is used quite often (29 matches in current master)
Since this retrieves all rows in that table at once and converts that into model objects that need to be kept in memory, this does not scale well
[find_each](http://apidock.com/rails/v2.3.8/ActiveRecord/Batches/ClassMethods/find_each) might be a better choice in respect to scale-ability
It is well discussed here: http://guides.rubyonrails.org/active_record_querying.html#retrieving-multiple-objects-in-batches

**Comment by stuzart** [comment]
Moved to JIRA: https://jira-bsse.ethz.ch/browse/OPSK-1017
