### ISSUE TITLE
Cookie warning popup when google analytics or piwik is enabled. 

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#378]
There are a number of 3rd party libraries and javascript plugins available.
For piwik, there should be an additional option to turn off the popup if you are running your own local instance.

**Comment by aapaolaza** [comment]
Branch https://github.com/seek4science/seek/tree/378 tackles this issue.
The current text is a placeholder, and I will change to the following unless there is a better suggestion:
_We use cookies to make your experience on this website better_

I don't think we are going to add a detailed page explaining the use of cookies, and there is only a single "I agree" button.
![image](https://user-images.githubusercontent.com/15800656/107367602-6c27e980-6ad7-11eb-8ba8-3bcdf0b334a4.png)

**Comment by fbacall** [comment]
Does this actually prevent cookies being set until "I agree" is clicked?

**Comment by aapaolaza** [comment]
No. If we want to do that, we could implement a an agree/deny functionality, so users can still use the platform without tracking.

**Comment by fbacall** [comment]
I think that is the best solution unless it is too much effort

**Comment by stuzart** [comment]
Is it enough to say words to the effect: "By continuing to use this site you agree to the use of cookies?" I see this on other sites

Also, it will need switching on/off with a configuration regardless of piwik being enabled, as it isn't always required to have the popup

**Comment by aapaolaza** [comment]
I've added an additional option specific to Piwik to switch off the popup in the admin panel:
'Tracking notice', "Warn users about the use of analytics software."

I will change the text to the one you suggested. I can add the agree/deny functionality, but then we might have to account for users who want to stop/resume the tracking later on (add an option in the account panel?).
