### ISSUE TITLE
can not delete the association between an assay and some assets 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#379]
Suspect that it effects all the items which render  `<%= render :partial => "assays/associate_assays" -%>` in `edit.html.erb`
including Sop, Document,Model,Datafile, Node,Workflow

![image](https://user-images.githubusercontent.com/42063448/86128783-1ec7b080-bae2-11ea-8ef3-b875e778ca1e.png)

**Comment by stuzart** [comment]
Do you mean that when you click the X to remove the item, nothing happens - or that after removing and submitting the item is still there ?

**Comment by whomingbird** [comment]
after removing and submitting the item is still there

**Comment by stuzart** [comment]
There was a similar problem with removing Creators. It was caused by a missing null item, to identify an empty array being submitted - without this the change was not picked up and ignored.

**Comment by stuzart** [comment]
see #246
