### ISSUE TITLE
jumping to default place if deleting  asset

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#380]
this is request for improvement - mainly from curators and project managers: e.g. I go to "my project" site and than to documents related (https://fairdomhub.org/projects/99#documents)  and I open one of the documents to delete it - after deliting I get to full list of  FAIRDOMHUb documents - but I would like to get to the place I was a step before - in this case to     https://fairdomhub.org/projects/99#documents

**Comment by smza** [comment]
I know this issue has been raised previously but I wanted to get the attention back to this as it has also been requested explicitly by an IBISBA user.

**Comment by aapaolaza** [comment]
ea9d0fc changes the default behaviour to return to the page before the content being deleted.

**Comment by aapaolaza** [comment]
Branch issue#380 has been merged into master, adding this functionality
