### ISSUE TITLE
Is it possible to delete a project? 

### ISSUE THREAD

**Issue by smza** [seek4science/seek#383]
As of now I'm not allowed to delete a project even though I'm the creator. This is very limiting as it leaves no scope for mistake and doesn't allow to start over.

**Comment by alaninmcr** [comment]
I identified the blocker was that the project still had members. I do not understand why this should prevent deletion though.

**Comment by stuzart** [comment]
It was intended as a safety net to protect against accidently, but I see no harm in removing this and replacing with a big warning - perhaps a step to type the name of the project into a box like github.
If @alaninmcr would like to look at this, it could be done on the 1.10 branch for speedy delivery

**Comment by fbacall** [comment]
See also: #213

**Comment by vcellmike** [comment]
Any progress with project deletion? Right now even en empty project (and as an admin I can remove myself and related institution from the project) can not be deleted. It's really a pain if someone accidentally (or for testing) creates a project. It looks that neither user nor site admin can delete it.

The same issue is with programs - it can not be deleted, even by admin?

**Comment by stuzart** [comment]
as an admin you should be able to delete if it has no people within it

**Comment by vcellmike** [comment]
Both projects and programs?

**Comment by stuzart** [comment]
I've double checked, and as an admin you should able to:
* delete a project if it has no people or items associated with it. (https://github.com/seek4science/seek/blob/master/app/models/project.rb#L229)
* delete a programme if it has no projects associated with it ( https://github.com/seek4science/seek/blob/master/app/models/programme.rb#L81 )

**Comment by alaninmcr** [comment]
Ready for merge

**Comment by alaninmcr** [comment]
Done

**Comment by stuzart** [comment]
There is a bug with deleting projects with members in it, even it is only yourself

**Comment by stuzart** [comment]
An Exception occurred in projects#destroy:

  You can not delete the blah at School of Computer Science, University of Manchester. This Work Group has 1 people associated with it. Please disassociate first the people from this Work Group
  app/models/work_group.rb:18:in `destroy'

**Comment by alaninmcr** [comment]
Munazah also wants to be able to delete a project, even if it does have ISA and/or assets.

**Comment by stuzart** [comment]
We agreed that "Purging" a project of assets before deletion of  a project should be treated as a separate issue

**Comment by stuzart** [comment]
see #581 for purging
