### ISSUE TITLE
Recognise csv and tsv as spreadsheets

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#385]
In some cases csv and tsv files are effectively spreadsheets. SEEK should have some way of treating them as such.

**Comment by aapaolaza** [comment]
I can take this over, do you mean adding a preview of a portion of the file, in a table format?

**Comment by alaninmcr** [comment]
No. It is much more than that. There is code to "understand" xlsx files as spreadsheets and to extract data from them. This capability needs to be done for csv and tsv as well.

**Comment by stuzart** [comment]
e.g. https://testing.sysmo-db.org/data_files/187/explore?version=1 when "exploring" the spreadsheet at https://testing.sysmo-db.org/data_files/187

**Comment by aapaolaza** [comment]
Fixed in dcfa22d5cf090e96f28eb2cd51e34ba853ead212
