### ISSUE TITLE
Can not search for the text in the spreadsheet 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#393]
When you search for a term for example “creatinin” in SEEK,
https://fairdomhub.org/search?utf8=%E2%9C%93&q=creatinin

You can get the items which contents include “creatinin” 
https://fairdomhub.org/data_files/1807/content_blobs/3849/view_content 

![image (4)](https://user-images.githubusercontent.com/42063448/87770197-fd273280-c81e-11ea-9e43-6719a4857e63.png)

But you can not find the items which the term is in the spreadsheet. 
https://fairdomhub.org/data_files/3756/explore?version=1 

![image (5)](https://user-images.githubusercontent.com/42063448/87770297-234cd280-c81f-11ea-97e2-5451596f1b6e.png)

**Comment by whomingbird** [comment]
the spreadsheet is converted to text, and then included in the indexing. It should be findable.  
this is where the text is extracted - https://github.com/seek4science/seek/blob/18ddf206bfb36d47e4f590a6c2ca4bf53b6d4913/lib/seek/content_extraction.rb#L33

**Comment by stuzart** [comment]
I'm closing this, as it was found to be a problem with the server and the text being converted
