### ISSUE TITLE
Profile pictures (avatars) completely blurred

### ISSUE THREAD

**Issue by matthiaskoenig** [seek4science/seek#401]
The SEEK avatars are extremely blurred. I upload a high quality image and avatars on top right and on the profile page (middle right) are very blurred (same picture works as avatar on every other platform/site). There is clearly a bug in your image resize or how you display images on SEEK.

![SEEK_image_blur](https://user-images.githubusercontent.com/900538/88475824-a95dcd00-cf33-11ea-8193-63eaf26c9ccf.png)

Using a 4k monitor here.
Best Matthias

**Comment by matthiaskoenig** [comment]
You have to open the attached image in original size to see the effect. The downsizing in github makes it look much better then it is. Just click on the image to see the effect.

**Comment by fbacall** [comment]
Looks like you are using some kind of high pixel density display that is displaying all images 2x bigger than their actual size

You can see the same effect on the icons

**Comment by matthiaskoenig** [comment]
Yes, this is the default behavior on all retina displays and high end monitors. Consequently, it is necessary to provide images on the web in sizes and resolutions which support these pixel densities.
Still many frameworks resize the images to resolutions which are too low for current devices. Basically SEEK will look blurred on all 4K monitors (which is around 2% of user base right now, but will get much larger).

**Comment by alaninmcr** [comment]
I agree with Matthias. It is better to deal with this sooner rather than later.

**Comment by fbacall** [comment]
I've made a new issue for this: #408
