### ISSUE TITLE
Upload Project Picture not working

### ISSUE THREAD

**Issue by matthiaskoenig** [seek4science/seek#402]
When trying to upload a project picture, the browse button does not open any file dialog, so no picture can be uploaded.
SEEK LiSyM v1.10.0 (https://seek.lisym.org/projects/10/avatars)

**Comment by whomingbird** [comment]
I can not reproduce the problem in LiSyM and other SEEK instances, could it be a browser issue? I have tested with chrome and firefox, which are both working.

**Comment by matthiaskoenig** [comment]
Yes, was browser issue. Solved now. Thanks.
