### ISSUE TITLE
Error creating new investigation with associated publications

### ISSUE THREAD

**Issue by matthiaskoenig** [seek4science/seek#404]
I just tried to create a new investigation with two associated publications, but get the following error:

```
1 error prohibited this investigation from being saved
There were problems with the following fields:
Publications is invalid
``` 
See screenshot attached

![Screenshot_2020-07-26 Reproducible and Exchangeable Computational Models (Standardization)](https://user-images.githubusercontent.com/900538/88489091-7696f180-cf92-11ea-956f-7086269c1cc2.png)

**Comment by whomingbird** [comment]
I have fixed the bug and updated LiSyM SEEK.

**Comment by matthiaskoenig** [comment]
@whomingbird thanks.
