### ISSUE TITLE
errors if adding publication type to old publications registered in FAIRDOMHub

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#412]
I manually (one-by-one) added  publication type to  publications registered by me in FAIRDOMHub

after editing about 10 of them I got "something went wrong" trying to add type to https://fairdomhub.org/publications/214

closed window, opened again - error again

same for https://fairdomhub.org/publications/329

**Comment by whomingbird** [comment]
The reason is that **Mysql2::Error: Data too long for column 'editor' at row 1:**
Need to change "editor" field type from varchar to text
