### ISSUE TITLE
error registerin model as remote URL to Biomodels

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#415]
try with several models e.g https://www.ebi.ac.uk/biomodels/BIOMD0000000505  or https://www.ebi.ac.uk/biomodels/BIOMD0000000835  

in all cases error message " We can't find out information about this URL - unhandled response code: 415"   

seems to be  general problem with creating new model as remote URL

**Comment by OlgaKrebs** [comment]
sorry, closed by mistake

**Comment by OlgaKrebs** [comment]
problem with fetching URL solved by Xiaoming, but I still can't finish creation this (and any other remote URL) model having error 
"Please specify at least a file/image to upload or provide a URL."   This may be should be another issue, but it only appear when choosing "remote URL" option, not if one upload local model file - so I keep it part of this issue

**Comment by whomingbird** [comment]
<img width="813" alt="Models 2020-08-19 14-41-03" src="https://user-images.githubusercontent.com/42063448/90636033-51607080-e22a-11ea-9a27-fffeff38e8e4.png">
you need to click "Add" button to add the link to the list.
