### ISSUE TITLE
Active Job

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#419]
Migrate from Delayed::Job to ActiveJob with Delayed::Job backend, with a view to move to Sidekiq.

- [x] Implement dedicated queue table for RdfGeneration instead of using jobs table.
- [x] For periodic jobs (email digests), find a gem to do scheduling.
- [x] For jobs that are linked to a record, use an explicit join table instead of LIKE query on `handler`.

**Comment by fbacall** [comment]
For checkbox 3, perhaps create a `Task` class with:
- A polymorphic `belongs_to` that links to the SEEK resource
- A key to identify the type of task (e.g. `sample_extraction`, `remote_content_fetch`...)
- The status of the task

The `Task` instance is passed to the Job, which will update the status appropriately through the various callbacks that are available.

The task status can be polled (have a generic action e.g. `TaskController#status` ?) to display spinners/loading bars in the UI.

**Comment by fbacall** [comment]
Overview of the different types of jobs we have: https://gist.github.com/fbacall/afaedfda4c219850237cca434c100ce5

**Comment by fbacall** [comment]
ActiveJob does not provide a way to query for failed jobs. It does provide a callback that triggers when a job fails, so maybe we can create a table to store these errors.

**Comment by fbacall** [comment]
It's also not straightforward how to provide the functionality where if a project is edited multiple times in a short space of time, only 1 notification email is sent.

**Comment by stuzart** [comment]
have you tried looking at https://github.com/inkstak/activejob-status - it provides information about the status of a job and whether it is queued, running or failed, along with giving progress amongst other things.
