### ISSUE TITLE
Word "Default" is misleading

### ISSUE THREAD

**Issue by smza** [seek4science/seek#423]
Why do we use: "Default License" Or "Default Sharing Policy"? Why is it NOT just: "License"  and  "Sharing Policy"?
Given that we keep these assets Blank and let the user choose the options the word "Default" seems misleading.

**Comment by fbacall** [comment]
It refers to the license and policy that are given to assets (by default) that are created in that project.

**Comment by smza** [comment]
> It refers to the license and policy that are given to assets (by default) that are created in that project.

But we don't have a default option ( for e.g we don't use "all private" or "all public" )

**Comment by stuzart** [comment]
they are the defaults for that project. For example, the project may have a policy where there entries default to all private, or all public

**Comment by alaninmcr** [comment]
I further confused things by mentioning that there are defaults that can be configured by admins for the default. Under "Policy and license settings" of Administration > Settings
