### ISSUE TITLE
Markdown not rendering lists correctly

### ISSUE THREAD

**Issue by longr** [seek4science/seek#430]
**Describe the bug**
Markdown, when used in the description, does not render lists correctly. Requires a newline between list items to display them as a bullet point

**Comment by fbacall** [comment]
Maybe something @aapaolaza could look at?

I think this case specifically applies to workflows, but might happen with other things

**Comment by aapaolaza** [comment]
I have tried replicating the bug but I couldn't. We might experience some issues with the way the widget and seek's markdown renderer work, as markdown can be ambiguous.

The following example will leave some gaps in the widget's preview, and it will render three normal looking lists when rendered by seek.

```md
## First list

* first item

* Second item

## second list
* another list
* another item

## Third list
* item 1
* Item 2

* Item 3
```

**Comment by fbacall** [comment]
This is what I get on dev.workflowhub.org (maybe not up to date?)

![image](https://user-images.githubusercontent.com/503373/94857404-591a5400-0429-11eb-9ab3-7bd77f7c8a7a.png)

renders as:

![image](https://user-images.githubusercontent.com/503373/94857428-620b2580-0429-11eb-8ce8-f886dc31e6fe.png)

**Comment by aapaolaza** [comment]
Thanks for the example, I got it to break. Now I know it's definitely the way the text is prepared for the Redcarpet renderer in the text_or_not_specified function. I will look into it, thanks.

**Comment by aapaolaza** [comment]
It's fixed now. However, there is still some ambiguity in the use of markdown between the editor and the viewer as they use different render engines. This is expected as the differences are quite extreme cases.

For example, the following will create two separate lists on the editor preview, but a single 4 itemed list as a description.
```
1. item 1
1. Item 2



1. Item 1
1. item 2
```
