### ISSUE TITLE
Wrong results shown in Preview of sharing settings

### ISSUE THREAD

**Issue by maja-HITS** [seek4science/seek#434]
Directly after changing the sharing permissions of a given item (e.g. study) the preview does still show partially the old sharing permission.
When I start again to manage study the sharing permission is the new one, so OK.

![grafik](https://user-images.githubusercontent.com/71636293/93753509-8cc2d600-fc00-11ea-8f92-1e6c21f9c033.png)
![grafik](https://user-images.githubusercontent.com/71636293/93753544-96e4d480-fc00-11ea-8094-d2a5064fc3e1.png)
![grafik](https://user-images.githubusercontent.com/71636293/93753560-a19f6980-fc00-11ea-8d86-25e8f0bb2204.png)

**Comment by alaninmcr** [comment]
Is this still true?

**Comment by maja-HITS** [comment]
Hi Alan,
no, it’s working now (on FairdomHub and sandbox7). Issue can be closed.
Best,
Maja

Von: Alan R Williams ***@***.***>
Gesendet: Sonntag, 8. Mai 2022 18:57
An: seek4science/seek ***@***.***>
Cc: Rey, Maja ***@***.***>; Author ***@***.***>
Betreff: Re: [seek4science/seek] Wrong results shown in Preview of sharing settings (#434)


Is this still true?

**Comment by alaninmcr** [comment]
Fixed

**Comment by alaninmcr** [comment]
Thanks.

I have closed the issue

Alan

________________________________________

**Comment by maja-HITS** [comment]
Thank you!
Best,
Maja

Von: Alan R Williams ***@***.***>
Gesendet: Montag, 9. Mai 2022 11:40
An: seek4science/seek ***@***.***>
Cc: Rey, Maja ***@***.***>; Author ***@***.***>
Betreff: Re: [seek4science/seek] Wrong results shown in Preview of sharing settings (#434)

Thanks.

I have closed the issue

Alan

________________________________________
