### ISSUE TITLE
Snapshot button still highlighted after changing sharing settings

### ISSUE THREAD

**Issue by maja-HITS** [seek4science/seek#435]
Maybe this bug has the same cause like bug #434 ?
After setting a public study/assay... to non public the create snapshot button is still highlighted, but it's not possible to take a snapshot (what is correct). When I update again the sharing (without changing anything), the snapshot option is not highlighted any more.

![grafik](https://user-images.githubusercontent.com/71636293/93755113-107dc200-fc03-11ea-85c7-0865ac15fe11.png)
![grafik](https://user-images.githubusercontent.com/71636293/93755143-170c3980-fc03-11ea-9ed2-5e331a13267d.png)
![grafik](https://user-images.githubusercontent.com/71636293/93755161-1d021a80-fc03-11ea-82c1-3a4109562d88.png)
![grafik](https://user-images.githubusercontent.com/71636293/93755184-22f7fb80-fc03-11ea-812a-b7b0eec71917.png)
![grafik](https://user-images.githubusercontent.com/71636293/93755196-29867300-fc03-11ea-947c-bad62bfd4cf6.png)
![grafik](https://user-images.githubusercontent.com/71636293/93755216-31461780-fc03-11ea-9d34-7d2750213925.png)

**Comment by whomingbird** [comment]
I reproduced the error and recorded a video. 
https://www.dropbox.com/s/7lp4ae1cqsldq1t/snapshot%20button%20issue%20.mp4?dl=0

**Comment by whomingbird** [comment]
The error is caused by the delay of updating the `study_auth_lookup` table.  After updating a sharing permission ( from viewable by public to not viewable), the job of updating `study_auth_lookup` table is not triggered. 

I also noticed, after reloading the `study` page, the job is triggered.

**Comment by stuzart** [comment]
If the button state doesn't change for the same user that updated the permissiosn, then it is unlikely to be an auth job problem, as the table should be updated instantly for the current user.

**Comment by whomingbird** [comment]
but if `make a snapshot` button is enabled or disabled depends on `can_view?`, which looks up in `study_auth_lookup` table. 
https://github.com/seek4science/seek/blob/45528fcc6244cdb8df30731a49b1f28eb5f44d28/app/views/snapshots/_new_snapshot_link.html.erb#L1
https://github.com/seek4science/seek/blob/ea661d05de8fccf95fab6fb0d1de928fd078cde2/lib/seek/research_objects/packaging.rb#L35

**Comment by fbacall** [comment]
It looks like the code to update immediately for anonymous users is only called on create: https://github.com/seek4science/seek/blob/master/lib/seek/permissions/policy_based_authorization.rb#L22

maybe this should be on save?

**Comment by stuzart** [comment]
yes it should be on save. It used to do it whenever the job was queued, both for the current and anonymous users
