### ISSUE TITLE
Inconsistent API documentation

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#436]
The documentation page https://docs.seek4science.org/help/user-guide/api.html links to 2 locations for API documentation, neither of which are regularly kept up to date

- https://docs.seek4science.org/tech/api/index.html
- https://app.swaggerhub.com/apis/FAIRDOM/SEEK/0.1

The most up to date documentation is now included with the seek source code, in _public/api_ which is served through http://<host>:<port>/api

The suggestion is to remove the link to swagger, and point to the documentation served by the FAIRDOMHub - https://fairdomhub.org/api . Or ideally, and if possible, point the documentation within the source code, via github, for the current release branch, identified by _current_seek_version_

There are also 2 sets of examples that could be linked to:

- https://github.com/fairdom/api-workshop - which is a walk-through designed for training exercises
- https://github.com/seek4science/seekAPIexamples - which are more general examples

I'm not sure if the 2nd examples are being maintained, and are both needed?

**Comment by alaninmcr** [comment]
I tried loading the updated yaml into SwaggerHub and it showed several issues. I think these need to be sorted out first.

**Comment by alaninmcr** [comment]
There are duplicated entries (mainly for collections) and the descriptions should not be $ref. Also it complained about basePath but I am not sure if that is just a cascade error
