### ISSUE TITLE
Using special characters in sample type attribute name leads to error when creating sample

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#442]
As an example, creating a sample for a sample type containing **size range (bp)** as an attribute will fail.

**Comment by stuzart** [comment]
is this through the api, or thought the user interface ?

**Comment by stuzart** [comment]
I can reproduce in a test instance. There are test cases for this, so something different it happening in the controller to what is expected. I will take a look tomorrow

**Comment by vdkkia** [comment]
I got an error through the API, then I reproduced it through the user interface.

**Comment by stuzart** [comment]
I think I've identified the problem, due to how attribute assignment handles parentheses and am thinking about a solution.
what does the body of your api call look like ?

**Comment by alaninmcr** [comment]
> I think I've identified the problem, due to how attribute assignment handles parentheses and am thinking about a solution.
> what does the body of your api call look like ?

That sounds intriguing.

**Comment by vdkkia** [comment]
Here is the body of the API call:
```
{
    "data": {
        "type": "samples",
        "attributes": {
            "title": "sample",
            "attribute_map": {
                "library layout": "a",
                "library source": "a",
                "library strategy": "a",
                "library selection": "a",
                "library strand": "",
                "plant id": "",
                "orientation": "",
                "size range (bp)": "",
                "molarity": "",
                "barcode p5": "",
                "barcode p7": "",
                "link_id": "hd1qmaiy"
            },
            "tags": null
        },
        "relationships": {
            "sample_type": {
                "data": {
                    "id": sample.sampleTypeId,
                    "type": "sample_types"
                }
            },
            "projects": {
                "data": [
                    {
                        "id": pid,
                        "type": "projects"
                    }
                ]
            }
        }
    }
}
```

**Comment by stuzart** [comment]
@vdkkia I think there may be a simple solution for your api
If you change https://github.com/seek4science/seek/blob/bbf6123dcc24bb7359358f19ca36b4a62785ef6e/app/controllers/samples_controller.rb#L134 
to just rename the 'attribute_map' key to 'data' - no need to manipulate the keys by prepending the method prefix, just rename the key
