### ISSUE TITLE
versioning: comment on document version doesn't show or isn't saved

### ISSUE THREAD

**Issue by lieserml** [seek4science/seek#446]
Hi SEEK-Dev-Team,
I've uploaded a local file as a document to FAIRDOM-Hub, then I changed it locally and uploaded the new version commenting on what I did. The versions of the document show up, but the comment is not saved or found. Any idea ?
cheers, Michael

**Comment by fbacall** [comment]
Hi @lieserml , thanks for reporting this. It will be fixed in the next release.

In the meantime, you can scroll down to "Version History" on the document's page and click "Edit comment" to re-add the comment

**Comment by lieserml** [comment]
Hi Finn,

thanks for the hint on the work-around and for fixing this in the next release.

cheers, Michael

________________________________
Von: Finn Bacall <notifications@github.com>
Gesendet: Donnerstag, 22. Oktober 2020 11:40
An: seek4science/seek
Cc: Lieser, Michael; Mention
Betreff: Re: [seek4science/seek] versioning: comment on document version doesn't show or isn't saved (#446)


Hi @lieserml<https://github.com/lieserml> , thanks for reporting this. It will be fixed in the next release.

In the meantime, you can scroll down to "Version History" on the document's page and click "Edit comment" to re-add the comment

-
