### ISSUE TITLE
Workflowhub: name and description parsing of an update in the workflow

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#454]
I have been updating the workflow in https://workflowhub.eu/workflows/64 but I noticed that the name and description fields are not updated. Am I missing something or doing something wrong?

In addition the figure has disconnected boxes such as Quast workflow but according to the CWL file it is connected if I am not mistaken. Is this a parsing issue?

**Comment by fbacall** [comment]
Can you check the title/description again? There was a bug with the rendering that was recently fixed.

Regarding the diagram, WorkflowHub currently does not currently parse files are referenced by the main CWL file unless they are uploaded as part of an RO-Crate zip file. This is something that is being worked on

**Comment by jjkoehorst** [comment]
I have updated https://git.wur.nl/unlock/cwl/-/raw/master/cwl/workflows/workflow_metagenomics.cwl and uploaded it as a new version and just by checking the gzip 

  gzip:
    type:
    - "null"
    - boolean
    doc: input data is gzip compressed
    label: gzip compression
    default: false

It does not update the entry:

gzip | n/a | input data is gzip compressed | boolean (Optional)
-- | -- | -- | --

**Comment by fbacall** [comment]
Thanks for reporting this. Should be fixed now.

I also updated your latest workflow version with the correct metadata
