### ISSUE TITLE
Incorrect title for some pages

### ISSUE THREAD

**Issue by aapaolaza** [seek4science/seek#460]
The title for these two pages is incorrect:
https://fairdomhub.org/documents
https://fairdomhub.org/sample_types

**Comment by fbacall** [comment]
Looks like they're all kept in a hash for some reason:
https://github.com/seek4science/seek/blob/75a76f1b27d144d0611be1c15e9b937034dd65d1/app/helpers/application_helper.rb#L488

should probably be changed to only keep exceptions in the hash, or infer from the controller name otherwise
