### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#463]
Migrate from travis to GitHub actions.

Outstanding issues:
- [x] Cannot seem to set MySQL to use unicode 
- [x] Broken `check-isa` test
- [ ] Starts both MySQL and Postgres even if suite doesn't need them

**Comment by floradanna** [comment]
About the mandatory/optional metadata fields in ISA format, I copy here the answer from Philippe Rocca-Serra.

Hi Flora,
Thank you for following up. Regarding the question, I would need a clarification about the type of metadata we are discussing.

1. I assume you are refering strictly to any Object and Attribute defined by the ISA specifications and formalized in the ISA JSON schema 1.0 ?

So I understand your question as: for the Study Object, which are the fields which should be minimally supplied?

If that's the case, then for most objects, the required information is Name and Identifier (if not autogenerated by the API). 

For specific objects such as ISA.Protocol, ISA.Factor, ISA.Assay , the associated 'types' must be provided. so `ISA.Protocol.type` and `ISA.StudyFactor.type`

For ISA.Assay, `ISA.Assay.measurement_type` must be provided, and `ISA.Assay.technology_type` is strongly recommended but not mandatory.

2. If "metadata" refers to descriptors outside the ISA syntax 

I am talking about things such as 'Disease', 'Instrument Temperature', 'Organism Part', then one may define ISA.Configurations/metadata profiles but such requirements are not to be found in the ISA schema itself

Let me know if this helps and if more information is needed.

Also, let me know about any mapping FAIRDOM-SEEK is making so I can review it and possibly advise.
