### ISSUE TITLE
Check sub-URI support

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#464]
i.e. deploying SEEK at `http://notarealhost.golf/seek/`

Known issues:
- [ ] Password reset link does not include sub-URI

**Comment by fbacall** [comment]
Setting `config.relative_url_root` sorts a lot of issues.

Maybe this should be set automatically if the user sets `site_base_host` to something with a path

**Comment by stuzart** [comment]
There are some docs on running under a sub-uri, including setting the `config.relative_url_root` @ https://docs.seek4science.org/tech/install-on-suburi.html
This worked when the docs were written, but needs updating for nginx

**Comment by stuzart** [comment]
though, needs updating for docker, so we could have a script or part of the upgrade task, that sets relative_url_root but would also need to recomplile the assets

**Comment by markwilkinson** [comment]
hi Stuart.  Inside of the "seek" container I have both the relative_url_root config set, as well as the RAILS_RELATIVE_ROOT_URL environment variable.  If I recompile the assets, then do compose down/up, they still do not point at the correct URL... is there an additional step?

**Comment by markwilkinson** [comment]
(b.t.w. inside of my version of the container it's running puma)  (seek:1.9)
