### ISSUE TITLE
Install `cwltool` from pip via requirements.txt

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#469]
Currently its installed as a package via apt, but this gets a very old version (~2018).

**Comment by stuzart** [comment]
I'm a little confused by this, as there already is an existing requirements.txt which references a version of cwltool. This is used by the travis build to install cwltool for testing, https://github.com/seek4science/seek/blob/master/requirements.txt

**Comment by fbacall** [comment]
Hmm... I'd not noticed that. 

I think this may not be installed on the production server, or if it is, the one from the Ubuntu repositories is being used instead.

**Comment by stuzart** [comment]
This may explain why the ISA tools test works with travis but not the github actions. I think it also needs incorporating into the docker build

**Comment by fbacall** [comment]
I ran `pip3 install ...` and now it seems to be using the newer version of `cwltool` 👍
