### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#47]
Hello Seek team,

first thank you for this new release and your work. It's a pleasure to see your active development.

Then, on my SEEK instance, I've seen some troubles during permissions (new UI) when I want to add "members of a project" in an assay or a study. It works good for an investigation.

When I valid the form with a project, there is no new entry in the table and I've a javascript error: 

> Uncaught TypeError: Cannot read property 'selected' of undefined
    at Object.addPermission (application-724beab00326adf1fdb0972c7d0c139d.js:301)
    at HTMLAnchorElement.<anonymous> (new:476)
    at HTMLAnchorElement.dispatch (application-724beab00326adf1fdb0972c7d0c139d.js:60)
    at HTMLAnchorElement.g.handle (application-724beab00326adf1fdb0972c7d0c139d.js:59)

It works when I add a project associated with an institution or just an institution.

I work on my own branch (https://github.com/seek4science/seek/pull/41) so maybe it's because of that.

Thanks,
Cyril

**Comment by fbacall** [comment]
Hi Cyril,

This should be fixed on the latest commit on the seek-1.3 branch.

Could you merge this branch and see if you still have problems?

Cheers!

**Comment by cmonjeau** [comment]
Hi,

thanks for your answer. 

I've merge your changes and I've the same issues. When I link an investigation to anstudy : 

> Uncaught TypeError: Sharing.removeMandatoryProjectPermissions is not a function
>     at HTMLSelectElement.<anonymous> (new:661)
>     at HTMLSelectElement.dispatch (application-724beab….js:60)
>     at HTMLSelectElement.g.handle (application-724beab….js:59)

When I link a study to an assay: 

> Uncaught TypeError: Sharing.removeMandatoryProjectPermissions is not a function
>     at HTMLSelectElement.<anonymous> (new?class=experimental:1163)
>     at HTMLSelectElement.dispatch (application-724beab….js:60)
>     at HTMLSelectElement.g.handle (application-724beab….js:59)

When I add a specific project via the new UI permission table :

> Uncaught TypeError: Cannot read property 'selected' of undefined
>     at Object.addPermission (application-724beab….js:301)
>     at HTMLAnchorElement.<anonymous> (new:474)
>     at HTMLAnchorElement.dispatch (application-724beab….js:60)
>     at HTMLAnchorElement.g.handle (application-724beab….js:59)

Cheers

**Comment by fbacall** [comment]
Can you run: `bundle exec rake assets:precompile RAILS_ENV=production` and try rebooting the server?

**Comment by cmonjeau** [comment]
Hey it works great :).

Thanks a lot for your work and your time!!

Cheers

**Comment by fbacall** [comment]
No problem
