### ISSUE TITLE
Install docs don't mention Java 8 switch

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#476]
The install docs mention you need to install the Java 8 SDK, but on recent Ubuntu versions, Java 11 is installed by default, and will be used instead. This breaks solr.

Need to run e.g.
`sudo update-alternatives --list java` ...

to switch to use the Java 8 SDK

**Comment by stuzart** [comment]
I wonder if a newer version of the gem would work with Java 11.

**Comment by fbacall** [comment]
At one point I did try installing the latest gem, regenerating all the configs etc. but kept running into all kinds of different issues (usually solr immediately exiting without any kind of error) so I just gave up in the end.
