### ISSUE TITLE
Big problems of default policies

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#49]
Hello all,

I've observed a bad issue on my instance.

1. Only the administrator of the instance can modify the default policy for a project. The administrator of the project can't.

2. When we change permissions on investigation / study / assays / etc. , there are no changes after update. I've observed that the behavior is very weard:

- try to update (Bio-imarie project have been added on a previous update but not appears in the table)
![policy_weard](https://cloud.githubusercontent.com/assets/1289992/24794768/33e7b4e0-1b87-11e7-9703-97f18662bbea.PNG)

- and  just after, when I try to watch my changes:

![policy_weard2](https://cloud.githubusercontent.com/assets/1289992/24794812/53230580-1b87-11e7-9826-d5e6edcd57cd.PNG)

Thanks

**Comment by cmonjeau** [comment]
ping @fbacall

**Comment by fbacall** [comment]
Very strange, I will look into it

**Comment by fbacall** [comment]
Thanks for reporting these issues. The second one was very obscure to track down!

They should be fixed now, let me know if you still have problems.

**Comment by cmonjeau** [comment]
Seems to be great. 

Thanks for your speed!!!
