### ISSUE TITLE
Error if creating file as remote URL

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#499]
I already had such case (and reported), but it was "labeled" as  "un-reproducible" as far as I remember. So I've created new data file as URL link and got error message at the end (see screen shot attached) saying:
1 error prohibited this data from being saved
There were problems with following fields: 
The file uploaded doen't match "  
this message blocked the window, I could not go back or correct or continue somehow...I closed browser and opened another one and saw , that my file has been successfully created

I hope one can check why that happened

**Comment by OlgaKrebs** [comment]
![file_creating_asRemote](https://user-images.githubusercontent.com/55085007/105229809-c979ec00-5b64-11eb-938d-67742bcc57c9.jpg)

**Comment by stuzart** [comment]
do you remember if you got an error previous to this one - e.g. missing title or no projects defined?

**Comment by stuzart** [comment]
I can only reproduce this setting a very short session lifetime, and allowing the session to timeout during the process. It may be possible that this is what is happening.
I've added the sending of a notification email when it happens again, that will help confirm this. And in the meantime look at another approach that doesn't require the session.
