### ISSUE TITLE
Crash when creating a new sample type

### ISSUE THREAD

**Issue by mboudet** [seek4science/seek#502]
**Describe the bug**
Crash when accessing "/sample_types/new" (sample type creation page)

**To Reproduce**
Git pull the repository
Edit the docker-compose.yaml to uncomment #build: for the seek container
docker-compose up
In the UI, click on "Create - Sample type" 

**Additional context**
Server logs : 
```
E, [2021-01-27T17:17:18.504053 #72] ERROR -- : ERROR - ActionView::Template::Error (undefined method `source_ontology' for #<SampleControlledVocab:0x0000558875424bb0>)
E, [2021-01-27T17:17:18.504157 #72] ERROR -- : Sending execption ERROR - ActionView::Template::Error (undefined method `source_ontology' for #<SampleControlledVocab:0x0000558875424bb0>
```

**Comment by fbacall** [comment]
Which version/branch/commit of SEEK is this?

**Comment by mboudet** [comment]
My bad, forgot to specify.

This is on a docker built from the master branch (should be up-to-date)

**Comment by fbacall** [comment]
Is it a new container using fresh volumes, or did you upgrade from a previous version?

**Comment by mboudet** [comment]
The volumes should be a bit older (I think from 10 days ago?)
I will try on new volumes.

**Comment by fbacall** [comment]
We've recently merged some database changes into `master`. You can try running:
```
docker exec -it seek docker/upgrade.sh
```

to upgrade your existing SEEK container (run database migrations etc.)

**Comment by mboudet** [comment]
Creating fresh volumes fixed it, so it was a migration issue on my end. Thanks! Will keep the upgrade in mind for the future.
