### ISSUE TITLE
Investigation appear 4 times in a list of Investigations to link to

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#504]
This issue has been reported by Kolodkin https://fairdomhub.org/people/260. trying to link an asset to own Investigation https://fairdomhub.org/investigations/399 he realised that Investigation he needs appears in the list 4 times .  Assumption: may be it is caused by 4 snapshots existing for this investigation

**Comment by OlgaKrebs** [comment]
![Kolodkin_4Investigations](https://user-images.githubusercontent.com/55085007/106457656-9520fc80-648f-11eb-967b-378a4f03bd87.png)

**Comment by stuzart** [comment]
I'm a bit confused by the screenshot - as it says Edit Investigation at the top, and seems to show a list of publications.
Is it the list of publications which contains duplicates?

**Comment by stuzart** [comment]
Regardless of the above, I think I've found the problems relates to the code at https://github.com/seek4science/seek/blob/d4051ba0fdd5a4e5e425839677afbb3bda43c20e/app/helpers/assets_helper.rb#L179

If the item is in more than one project, it could appear twice. I this case, the Investigation is associated with 3 projects

**Comment by stuzart** [comment]
this is fixed and applied directly to the fairdomhub
