### ISSUE TITLE
Empty descriptions should have default text

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#513]
It is strongly recommended for IBISBA that empty description should default to some configurable default e.g. 'Description withheld'

**Comment by alaninmcr** [comment]
Descriptions should be Description withheld
Webpages should be omitted if not specified
Organisms is OK as it is, but may be amended later.

**Comment by stuzart** [comment]
we could have a simple yaml file that contains the text that should be shown, and those attributes that should be hidden (or hidden if not in the yaml file). this would then be an easy way to configure between different deployments, and make future refinements

the view helper method could be replaced with something that firsts looks up for the attribute

**Comment by alaninmcr** [comment]
Neat idea

**Comment by alaninmcr** [comment]
assets_helper has item_description
application_helper has text_or_not_specified
resource_list_item_helper has list_item_description and small_list_item_description but both call text_or_not_specified

**Comment by alaninmcr** [comment]
Also i_s_a_graph_helper has cytoscape_node_elements
