### ISSUE TITLE
Refactor views

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#514]
There are many parts of views that are duplicated, for example the specification of the description. It would be better if the code was extracted into a reused file. This would give one, identifiable, place to change the appearance of description etc,.

**Comment by stuzart** [comment]
this is done through view helper methods to keep things consistent, for example for descriptions there is `item_description `

**Comment by alaninmcr** [comment]
Yes. I've found the helper method and am making it based on a locale entry.
