### ISSUE TITLE
grammar typo

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#516]
When hovering over the users involved in a project under "Administering the project members" I noticed a grammar issue.

![image](https://user-images.githubusercontent.com/4471699/108852431-e41d0600-75e5-11eb-8894-4e6640c7ec23.png)

**Comment by stuzart** [comment]
thanks, that should be an easy fix

**Comment by alaninmcr** [comment]
Fixed in commit 848590ad0a34380f46ffb7a442d5bab868e36379

**Comment by alaninmcr** [comment]
and so I close
