### ISSUE TITLE
bioschemas markup should specify conformsTo

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#528]
This applies to Workflow, Person and Event.

**Comment by alaninmcr** [comment]
This is done in the rocrate-jsonld branch. Needs merging across

**Comment by stuzart** [comment]
needs transferring to the seek 1.11 branch, and Workflow needs double checking (doesn't show up on workflowhub)

**Comment by alaninmcr** [comment]
Also need to do for DataCatalog and DataSet
