### ISSUE TITLE
Wrong list for person responsible in study creation

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#53]
Hi Seek team,

I've found an issue on my Seek instance when I want to create a study.

In the form, when I choose my investigation, it's not the list of my project users but it seems to be another users from a different project.

![seek_study_person_responible_1](https://user-images.githubusercontent.com/1289992/30103905-5863a5ba-92f4-11e7-974f-ebabd681deaf.PNG)

When I save my study (with a wrong user) and I edit it, there is the good list of users in the field.

![seek_study_person_responible_2](https://user-images.githubusercontent.com/1289992/30103940-6fbe8914-92f4-11e7-89ec-5563cabcc540.PNG)

Thanks a lot

**Comment by fbacall** [comment]
Thanks for the reporting this.

It should be fixed on both the `seek-1.4` branch and `master`

**Comment by cmonjeau** [comment]
You're welcome.

Thanks for the fixes!!
