### ISSUE TITLE
Extra hashes in JSON-LD

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#533]
The JSON-LD for a ComputationalWorkflow has hashes on ids, for example:

  "input": [
    {
      "@type": "FormalParameter",
      "@id": "#metagenomics_workflow-inputs-filter_rrna",  **-- extra hash**
      "name": "rRNA filtering",
      "dct:conformsTo": "https://bioschemas.org/profiles/FormalParameter/1.0-RELEASE/"
    },

and

  "creator": [
    {
      "@type": "Person",
      "@id": "#Bert%20Bloggs", **-- extra hash**
      "name": "Bert Bloggs"
    }
  ],

The hashes do not seem correct to me

**Comment by fbacall** [comment]
see: https://www.researchobject.org/ro-crate/1.1/appendix/jsonld.html#describing-entities-in-json-ld

**Comment by alaninmcr** [comment]
The documentation referenced by Finn says the hashes are correct. I will close the issue
