### ISSUE TITLE
can not remove all samples, which are involved in an Assay. 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#538]
see https://testing.sysmo-db.org/assays/185

**Comment by stuzart** [comment]
I'm unclear what this means, it needs a some more information

**Comment by whomingbird** [comment]
![image](https://user-images.githubusercontent.com/42063448/110611770-d2179780-818f-11eb-8f21-39d7b5f7e3f1.png)

If there are more than 2 samples involved in the assay, you can remove some of them. 
But the last sample can not be removed with update.

**Comment by fbacall** [comment]
It is probably this again #379

**Comment by fbacall** [comment]
I think I can fix this in associations.js to save having to manually add hidden fields to all the views.
