### ISSUE TITLE
GIT access from FAIRDOMHub help documentation

### ISSUE THREAD

**Issue by jjkoehorst** [seek4science/seek#546]
I wanted to raise an issue about another topic but when I go from the fairdomhub to help I end up in https://docs.seek4science.org/help/ which as far as I can tell does not have a link to the git issue tracker to create new issues?

Could this perhaps be added?

**Comment by stuzart** [comment]
we have it on https://docs.seek4science.org/contacting-us.html and also https://docs.seek4science.org/tech/reporting-bugs-and-features.html in more detail, but yes it would be good to link to the latter directly from the user-guide. 
I also intend adding this link to the Help menu directly  in fairdomhub
