### ISSUE TITLE
Proposal: "Join" / "Create new" buttons for projects

### ISSUE THREAD

**Issue by mboudet** [seek4science/seek#55]
Hi all,

Currently, a user not in any project might be at a loss as to how to join / ask to create a new one.

The current way is to directly contact the seek admin or a project admin by mail, which might not be the most evident way for a new user.

Would it be possible to add a "join" request on each project page? (Basically sending a mail to the project admin for validation).
It might also be good to add a "Create new project" button, leading to a form where the user must fill out the details. The seek admin will then be able to validate/deny the request.

**Comment by stuzart** [comment]
Sorry, I hadn't missed this but had thought I'd replied.
This request has come up before, and is something we are now working on: https://jira-bsse.ethz.ch/browse/OPSK-1451
It's not likely to be in our next (imminent) release, but should follow shortly afterwards.

**Comment by mboudet** [comment]
Great, thank you very much.
