### ISSUE TITLE
Character limits in Excel data validation for sample types

### ISSUE THREAD

**Issue by mboudet** [seek4science/seek#551]
**Describe the bug**
Data validation using lists in Excel seems to be limited to 255 characters (including comma to separate the values)
The limitation appears to be 1000 characters in LibreOffice

**To Reproduce**
* Launch dockers using the default docker file (fairdom/seek:master)
`docker-compose up -d`
* Create a sample controlled vocabulary (to simplify, import a big ontology -> ex: Brassica ontology with root "http://www.cropontology.org/rdf/CO_348:ROOT")
* Create a sample type using this CV
* Open the generated template and check the validation -> If there are too many characters, Excel throws an error when opening the sheet.
* When force-opening the sheet, Excel will empty the validation cell.

LibreOffice will open it anyway, but if there are more than 1000 characters, the validation will be recognized as a cell and not a list (and will not works)

LibreOffice (> 1000 chars)
![image](https://user-images.githubusercontent.com/17642511/112327517-c8288500-8cb5-11eb-8a00-179bf5ac2b07.png)

Excel (> 255 chars)
![image](https://user-images.githubusercontent.com/17642511/112332791-569f0580-8cba-11eb-9cd7-a35745081c19.png)

**Comment by stuzart** [comment]
I think this may have been fixed through another change to how the lists are declared in the Excel spreadsheet (using full data validations instead of comma separated lists) ( #550 ). Are you able to double check with version 1.11.0 ?
