### ISSUE TITLE
Possibility to hide SEEK login form when using only LDAP

### ISSUE THREAD

**Issue by thopico** [seek4science/seek#558]
Hi, this is not a bug but a feature request.

**Describe the issue**
Our organization is only using LDAP as main authentication mechanism, and we don't want our users to use the « SEEK login » form to log in. In order to make it less confusing, we would like to have the possibility to hide the classic « SEEK login » form.

**Expected solution**
Have a setting which when set to false hides the « SEEK login » form.

**Screenshots**
![2021-04-01_11-01](https://user-images.githubusercontent.com/56619719/113270398-b78d9580-92d9-11eb-8dfc-fdd283174b0e.png)

Thank you for your time.

**Comment by Linus4** [comment]
We're using the normal SEEK login for administration and LDAP for our users, so we need both. It would be nice if we could make LDAP login the default option because many users don't know about this and try to authenticate using the normal login.

![Screenshot 2022-04-26 at 13-42-20 The SEEK](https://user-images.githubusercontent.com/20419033/165292591-471d2fc6-b305-4808-b9ca-d95e7eb42942.png)

**Comment by thopico** [comment]
Eventually we went after the same configuration and we managed to solve it with this change :
```diff
diff --git a/app/views/gadgets/_sign_in.html.erb b/app/views/gadgets/_sign_in.html.erb
index 2a704bbae4..9f4ada5145 100644
--- a/app/views/gadgets/_sign_in.html.erb
+++ b/app/views/gadgets/_sign_in.html.erb
@@ -1,5 +1,5 @@
 <% original_path ||= request.original_fullpath %>
-<% strategy = params[:strategy] || 'password' %>
+<% strategy = params[:strategy] || 'ldap' %>
 
 <% unless logged_in_and_registered? -%>
     <div class="panel panel-default" id="login-panel">
```

I'm not sure this custom feature should be generalized as is (because normal Seek login should stay the norm).
The perfect solution would be to have a button in the admin panel to select the preferred login mode, but I understand if it's too much detail for now.

So for now we are good with this manual change for our organization.
I will close the issue but feel free to reopen it if you want to address this 'login mode button' matter.
