### ISSUE TITLE
Review which other SEEK resources should be allowed in collections

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#560]
- [ ] Programme
- [ ] Project
- [ ] Institution
- [ ] Person
- [ ] Investigation
- [ ] Study
- [ ] Assay
- [x] Publication
- [x] Event
- [ ] Sample Type
- [x] Sample

**Comment by alaninmcr** [comment]
File Templates and Placeholders? I think templates would be OK.

**Comment by floradanna** [comment]
@rabuono and I would like to propose the Templates that we are developing as well, if @vdkkia thinks that it is possible of course. Enabling collection of templates would be useful for our use cases.

"Our templates" are basically sets of attributes (or metadata schemes) that the user can choose to apply to describe samples. Templates are always without samples (empty) and they are not editable by the user. 

When a user apply a template to describe samples, a sample type is created.
