### ISSUE TITLE
Replace Sample type create page with Template create

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#568]
Since the sample types are supposed to be hidden from the users, there should be a place for the users to add and share templates.

**Comment by floradanna** [comment]
Datahub TEMPLATES are sets of attributes (or metadata schemes) that the user can choose to apply to describe samples, over and over. Templates are always without samples (empty). Every time a user chooses and applies a template to describe samples, a new related sample type (a copy of template attributes) is created.
Templates can be provided by instance admin and be created by users (project members).

**Comment by vdkkia** [comment]
Now the Sample Type creation page is hidden when `Single_Page` is enabled.
