### ISSUE TITLE
Administer project members: Users are not displayed to administer

### ISSUE THREAD

**Issue by Golebiewski** [seek4science/seek#575]
Even when you have the rights to manage a project and administer project members, there are no project members displayed in FAIRDOMHub: 

e.g. https://fairdomhub.org/projects/191/admin_members or https://fairdomhub.org/projects/190/admin_members
(see screenshots  @attached)

Expected behavior:
Full list of project members should be displayed for all users having the managing rights on these projects.

Desktop (please complete the following information):
 - OS:  MacOS Mojave 10.14.6
 - Browsers Safari 14.0.3 and Firefox 88.0

**Comment by Golebiewski** [comment]
<img width="1188" alt="Bildschirmfoto 2021-04-21 um 11 32 52" src="https://user-images.githubusercontent.com/10076270/115541884-edea7f00-a29f-11eb-9e4a-fbe00577a370.png">

**Comment by Golebiewski** [comment]
<img width="1202" alt="Bildschirmfoto 2021-04-21 um 11 31 22" src="https://user-images.githubusercontent.com/10076270/115542723-da8be380-a2a0-11eb-88e1-b274b8f3dcb3.png">

**Comment by alaninmcr** [comment]
It is only listing the first institution.

The console log (for Chrome) has

application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18 Uncaught nÂ {description: undefined, fileName: undefined, lineNumber: undefined, message: "**Missing helper: "I18n**"", name: "Error",Â â€¦}description: undefinedfileName: undefinedlineNumber: undefinedmessage: "Missing helper: "I18n""name: "Error"number: undefinedstack: "Error: Missing helper: "I18n"â†µ    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:20804)â†µ    at 6 (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:48:30398)â†µ    at Object.o [as inverse] (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:26344)â†µ    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:21106)â†µ    at 3 (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:48:29569)â†µ    at Object.o [as inverse] (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:26344)â†µ    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:21106)â†µ    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:21196)â†µ    at Object.main (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:48:31437)â†µ    at n (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:24471)"__proto__: Error
    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:18927)
    at t (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15032)
    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:16183)
    at t (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15032)
    at Object.<anonymous> (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15440)
    at t (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15032)
    at https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15119
    at https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:15124
    at zenodoExport.creatorList (https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:14899)
    at https://fairdomhub.org/assets/application-134b97e61bc022e4ed389852de6f94732ef765401007967483ede83873e56b79.js:18:14903

**Comment by alaninmcr** [comment]
So it looks (to me) like it is due to a missing internationalization

**Comment by fbacall** [comment]
This should be fixed by a75407ba1025285d3cbcd7c45e9be7d9ed514b5b

@Golebiewski can you check it is working?

**Comment by Golebiewski** [comment]
Works now on FAIRDOMHub. Thanks a lot for the ultra-fast fixing :-)
