### ISSUE TITLE
Missing context extension in downloaded RO-Crate

### ISSUE THREAD

**Issue by simleo** [seek4science/seek#576]
**Describe the bug**

When a workflow that was uploaded as an RO-Crate is subsequently downloaded as an RO-Crate, the metadata file is missing any [context extensions](https://simleo.github.io/ro-crate/1.1/appendix/jsonld.html#extending-ro-crate) from the original one.

**To Reproduce**

Upload [this crate](https://github.com/ResearchObject/ro-crate-py/tree/08647d9bb522008da60b3a7762bdb40cd3a0fa30/test/test-data/ro-crate-galaxy-sortchangecase) to WorkflowHub (tested on https://dev.workflowhub.eu), then download it as an RO-Crate.

**Details**

The above example is a [Workflow Testing RO-Crate](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate), which uses context extensions defined in the [ro-terms test namespace](https://github.com/ResearchObject/ro-terms/blob/master/test).

The crate's original context was:

```json
    "@context": [
        "https://w3id.org/ro/crate/1.1/context",
        {
            "GithubService": "https://w3id.org/ro/terms/test#GithubService",
            "JenkinsService": "https://w3id.org/ro/terms/test#JenkinsService",
            "PlanemoEngine": "https://w3id.org/ro/terms/test#PlanemoEngine",
            "TestDefinition": "https://w3id.org/ro/terms/test#TestDefinition",
            "TestInstance": "https://w3id.org/ro/terms/test#TestInstance",
            "TestService": "https://w3id.org/ro/terms/test#TestService",
            "TestSuite": "https://w3id.org/ro/terms/test#TestSuite",
            "TravisService": "https://w3id.org/ro/terms/test#TravisService",
            "definition": "https://w3id.org/ro/terms/test#definition",
            "engineVersion": "https://w3id.org/ro/terms/test#engineVersion",
            "instance": "https://w3id.org/ro/terms/test#instance",
            "resource": "https://w3id.org/ro/terms/test#resource",
            "runsOn": "https://w3id.org/ro/terms/test#runsOn"
        }
    ]
```

While the context in the downloaded crate is:

```json
    "@context": "https://w3id.org/ro/crate/1.1/context"
```

**Comment by fbacall** [comment]
This is a current limitation of the library, so I've raised an issue in that repository.

Does the python library handle this case?

**Comment by simleo** [comment]
> This is a current limitation of the library, so I've raised an issue in that repository.

Thanks!

> Does the python library handle this case?

There is some [initial support](https://github.com/ResearchObject/ro-crate-py/pull/53), but it's not finished yet. I just opened https://github.com/ResearchObject/ro-crate-py/issues/61 to keep track of what's missing.
