### ISSUE TITLE
DOI creation in SEEK: Sequence of authors wrong and incomplete

### ISSUE THREAD

**Issue by Golebiewski** [seek4science/seek#579]
**Describe the bug**
When creating a DOI for an asset (e.g. datafile or document) the list of authors in the created DOI only contain authors with SEEK account, but lack the ones without account. Also the sequence of authors is different in the DOI citation (seems to be based on the ascending order of user/profile IDs), compared to the original sequence of creators.

**Expected behavior**
Complete list of authors (creators) in the original order is expected listing all creators (also the ones without SEEK account).

**Screenshots**
Screenshot with example from FAIRDOMHub is attached: 
<img width="278" alt="FAIRDOMHub problem DOI author sequence" src="https://user-images.githubusercontent.com/10076270/115889638-66923c80-a454-11eb-81d5-662b57a79a48.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Safari
 - Version 14.0.3

**Comment by stuzart** [comment]
Another fix should have fixed this but needs double checking before closing. @whomingbird
