### ISSUE TITLE
DOI in Citation box should not be upper-case

### ISSUE THREAD

**Issue by stain** [seek4science/seek#590]
The DOIs work great - but in the citation box it is shown as http://doi.org/10.48546/WORKFLOWHUB.WORKFLOW.56.2 when it should be with https and lower-case  https://doi.org/10.48546/workflowhub.workflow.56.2  - compare with https://api.datacite.org/dois/10.48546/WORKFLOWHUB.WORKFLOW.56.1 which shows they have been correctly registered in lower case.

![image](https://user-images.githubusercontent.com/253413/117481593-1ab6bb80-af5b-11eb-864c-2d1804054916.png)

the DOI: link on the left below SEEK ID is correct lower-case and links to the https version correctly.

This may be related to the perhaps odd default choice of citation style _American Psychological Association 5th edition_.

Note that some citation styles don't show the DOI at all:

![image](https://user-images.githubusercontent.com/253413/117481783-5f425700-af5b-11eb-8854-d5924d6a720f.png)

Some overflow:

![image](https://user-images.githubusercontent.com/253413/117481868-7bde8f00-af5b-11eb-996a-851579578c51.png)

**Comment by fbacall** [comment]
Is there a more appropriate default citation style?

**Comment by fbacall** [comment]
Actually, in the CSL metadata that we generate the citations from, it is capitalized:
```curl -L -H "Accept: application/vnd.citationstyles.csl+json" https://doi.org/10.48546/workflowhub.workflow.56.2```
```json
{
  "type": "article",
  "id": "https://doi.org/10.48546/workflowhub.workflow.56.2",
  "author": [
    {
      "family": "Lowe",
      "given": "Douglas"
    },
    {
      "family": "Bayarri",
      "given": "Genís"
    }
  ],
  "issued": {
    "date-parts": [
      [
        2021
      ]
    ]
  },
  "abstract": "# Summary This tutorial aims to illustrate the process of setting up a simulation system containing a protein in complex with a ligand, step by step, using the BioExcel Building Blocks library (biobb). The particular example used is the T4 lysozyme L99A/M102Q protein (PDB code 3HTB), in complex with the 2-propylphenol small molecule (3-letter Code JZ4). Workflow engine is a jupyter notebook. It can be run in binder, following the link given, or locally. Auxiliar libraries used are: nb\\_conda_kernels, nglview, ipywidgets, os, plotly, and simpletraj. Environment can be setup using the included environment.yml file. # Parameters ## Inputs Parameters needed to configure the workflow: * **pdbCode**: PDB code of the protein-ligand complex structure (e.g. 3HTB) * **ligandCode**: Small molecule 3-letter code for the ligand structure (e.g. JZ4) * **mol\\_charge**: Charge of the small molecule, needed to add hydrogen atoms. ## Outputs Output files generated (named according to the input parameters given above): * **output\\_md\\_gro**: final structure of the MD setup protocol * **output\\_md\\_trr**: final trajectory of the MD setup protocol * **output\\_md\\_cpt**: final checkpoint file * **output\\_gppmd\\_tpr**: final tpr file * **output\\_genion\\_top\\_zip**: final topology of the MD system",
  "DOI": "10.48546/WORKFLOWHUB.WORKFLOW.56.2",
  "publisher": "WorkflowHub",
  "title": "Protein Ligand Complex MD Setup tutorial using BioExcel Building Blocks (biobb) (jupyter notebook)",
  "URL": "https://workflowhub.eu/workflows/56?version=2"
}
```

**Comment by fbacall** [comment]
This appears to be a DataCite feature:
https://support.datacite.org/docs/doi-basics#suffix

>All DOIs are converted to upper case upon registration and DOI resolution, but DOIs are not consistently displayed in such a way.

**Comment by stain** [comment]
It seems the convention is that the `https://doi.org/` URL is in lower-case, while DOI separately is in uppercase. The styles do use without the `https://` prefix. Will close issue.
