### ISSUE TITLE
Ability to export Sample View table as a file

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#594]
As discussed in the Staff Exchange (May 6th 2021)
Upon selection of “View samples” of one Sample Type, it would be nice if it was possible to export the table with all contained Samples as a file.
Suggested export formats were: csv, xls, json.

**Comment by vdkkia** [comment]
The **CSV** button is placed on top of the table.

![image](https://user-images.githubusercontent.com/4618481/173533473-599a55c1-c448-4ae3-acef-ccdaf12423ce.png)

**Comment by rabuono** [comment]
In my opinion, yes. If this could be generalized to most tables, it would be nice. Being able to export the table in view was mentioned before in other meetings.
