### ISSUE TITLE
Detect duplicate samples upon file upload

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#598]
- Add the ability to detect duplicate samples within a project on upload in case all sample_attributes are the same.
- Let the user select what to do with the duplicate samples (skip, update)

**Comment by floradanna** [comment]
Testing document: [Samples download and upload - DataHub](https://docs.google.com/document/d/1Lrx9H_8V0PtL7QpjSkR1aiqlrmb3AhbQRhAM4QXk9PI/edit#heading=h.8d3zondjbjmm)
