### ISSUE TITLE
Information buttons on index pages to describe what that type is

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#599]
Description can go in the locale to be configurable per instance if needed.

Similar to this on TeSS:
![image](https://user-images.githubusercontent.com/503373/117823173-15ac8180-b265-11eb-8c66-92c22d74fac9.png)

**Comment by stuzart** [comment]
relates to #850

**Comment by abecam** [comment]
Document to complete: https://docs.google.com/document/d/1FYwkpRwrgcfICUjnEOph78Hn6ITsyZbJkQ8UCaUC_50/edit?usp=sharing

**Comment by abecam** [comment]
Fixed by #1208
