### ISSUE TITLE
Subscription issue

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#60]
Hi Seek team,

there is a problem when I want to subscribe to any content (assay, data, etc.). 

I've a internal error with message :

`ActiveModel::ForbiddenAttributesError in SubscriptionsController#create`

I tried on your seek-1.5 branch and I've the same issue. Maybe something is broken on my instance?

Best regards,
Cyril

**Comment by fbacall** [comment]
Hi Cyril,

Yes, I get the same problem. I can see the cause and will push a fix to `seek-1.5`.

Cheers,
Finn

**Comment by cmonjeau** [comment]
Very fast :)

Thanks for your work!

Cheers, 
Cyril

**Comment by fbacall** [comment]
No problem!

You can merge either `seek-1.5` or `master` for the fix.

**Comment by cmonjeau** [comment]
Ok thanks!

**Comment by fbacall** [comment]
This change broke a lot of tests... will re-open this issue until they are fixed.
