### ISSUE TITLE
DOI "identifier" in RO-Crate metadata is not full URI

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#618]
Should include `https://doi...` or `doi:` scheme

**Comment by stain** [comment]
While 'doi:' is a [registered (provisional) URI scheme](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) the recommendation is now to use 'https://doi.org/' as URI prefix. 

See also:
* https://www.researchobject.org/ro-crate/1.1/metadata.html#recommended-identifiers
* https://www.researchobject.org/ro-crate/1.1/contextual-entities.html#publications-via-citation-property

**Comment by fbacall** [comment]
It uses the full URI now

```json
...
      "identifier": "https://doi.org/10.48546/workflowhub.workflow.56.1",
      "url": "https://workflowhub.eu/workflows/56/ro_crate?version=1",
      "name": "Research Object Crate for Protein Ligand Complex MD Setup tutorial using BioExcel Building Blocks (biobb) (jupyter notebook)",
...
```
