### ISSUE TITLE
Link version in related items

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#62]
Hi (again),

I have new users in my SEEK instance and they touch everything. This explains all my issues ;)

Thus, we observed that there are no version link concerning a data or a sop item. It's hard to explain so I'll describe it :

1. create a SOP
2. link the SOP to an assay
3. upload a new version of the SOP
4. in the related items and in the graph, it's the latest version (v2) of the SOP, and not the true SOP (v1)

I think this can be a real problem for the data reproductibility.

**Comment by fbacall** [comment]
Hi Cyril. 

In previous versions of SEEK it was possible to link to a particular version of a resource from an assay, however we found that users were often confused as to why existing assays would not link to the latest version of the SOP/data that they had just uploaded.

The intent of the versioning system was to allow users to correct minor mistakes, and we say on the upload form:

> You are about to upload a new version of this Sop. You should only upload a new version if you have made minor modifications, such as tidying up or fixing errors, that do not change the original purpose of the file. If you think this new version changes the original purpose or meaning of the Sop, then you should upload it as a new item rather than create a new version. 

If you would like to capture the exact version of resources used at a specific time point (for publication etc.), maybe the snapshot feature would suit your needs?

Cheers

**Comment by cmonjeau** [comment]
Hi Finn,

I understand that you have chosen to remove it in order to avoid any confusion, and that sounds good to me. I will propose to my users to use the snapshot function if necessary.

Thank you for your response!!
