### ISSUE TITLE
Support for extendedGA4GH possible ?

### ISSUE THREAD

**Issue by mvdbeek** [seek4science/seek#637]
It would be great if https://dockstore.org/api/static/swagger-ui/index.html#/extendedGA4GH was implemented in workflowhub. If this was in place we could let users browse organizations directly from within Galaxy.

**Comment by bgruening** [comment]
@stuzart this is blocking currently the Galaxy side of things. Is it possible to prioritize that? Thanks!

**Comment by fbacall** [comment]
which specific endpoints did you need? The docs on some of those are pretty sparse so I'm not entirely sure how we can implement them all.

**Comment by mvdbeek** [comment]
​/api​/ga4gh​/v2​/extended​/workflows​/{organization} and /api/ga4gh/v2/extended/organizations would be the most important one for us

**Comment by bgruening** [comment]
This API is badly defined I assume, so a safe way is to do what Dockstore has done, at least then WfH and Dockstore would be equally wrong :)

**Comment by fbacall** [comment]
This is deployed on WorkflowHub now if you want to test it out

**Comment by mvdbeek** [comment]
Wow, that was fast!

**Comment by mvdbeek** [comment]
Yes, that looks good, we can work with this!
