### ISSUE TITLE
Zenodo connection

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#64]
Hi seek team,

first, happy new year with many seek successes :)

I have a question concerning Zenodo connection with snapshots. I configured with sandbox.zenodo.org in the admin panel but nothing append when I create a snapshot. The Zenodo URL is always "None". 

Maybe I made mistakes during Zenodo or Seek configuration. Do you have a documentation?

Thanks,
Cyril

**Comment by fbacall** [comment]
Hi Cyril,

Unfortunately the SEEK - Zenodo integration is rather poorly supported and documented :(

The way it is currently coded requires you to also have an account with DataCite, capable of generating DOIs. Once you have a Snapshot, you must create a DataCite DOI for it, then a button "Export to Zenodo" appears. I think it was coded this way due to certain restrictions on the Zenodo API that were present at the time...

**However**,  I also discovered last week that this feature seems to not work against Zenodo's sandbox API. I didn't have much time to look into it, but from what I could tell, after uploading the file to Zenodo, the Zenodo sandbox API would not allow SEEK to perform a "publish" action, and so the Zenodo deposition is not given a URL.

We have recently had other interest in using this feature, so may rework it in a future development sprint.

**Comment by cmonjeau** [comment]
Ok,

We are beginning to take an interest in the DOI allocation. 

If we can allocate DOIs, i'll try directly with Zenodo.

Thanks for your reply.

**Comment by fbacall** [comment]
I think if we revisit this feature, we would just allow SEEK to export directly to Zenodo, then use the DOI that Zenodo provides.

**Comment by cmonjeau** [comment]
Thank you very much. I'll test this in the next release :)

**Comment by cmonjeau** [comment]
Hi seek team,

First of all, congratulation on your 1.6.2 release, it works like a charm. 

I reopen this issue to get more information about zenodo exportation for snapshots.

I've tried to using this feature with sandbox.zenodo.org and I think I'm missing something because I have a permission problem. 

Below my steps:

1. I create an application in Zenodo and I get a client ID and Secret. I'm not sure about Redirect URI content.
2. I put them in my seek instance with zenodo urls : https://sandbox.zenodo.org/api/ & https://sandbox.zenodo.org/oauth/
3. I'm trying to export and I have an invalid resquest : 

> Invalid authorization request The service that redirected your here made an invalid authorization request (error code: invalid_request).

Do you have an idea what I did wrong?

**Comment by fbacall** [comment]
Hi @cmonjeau 

I just checked this on my local instance and it seemed to work OK. One thing I did notice though, is when copying and pasting my Client Secret from Zenodo into SEEK there was a blank space at the end. Maybe check this?

**Comment by cmonjeau** [comment]
Hi @fbacall ,

thanks for your answer.

I've already checked that kind of mistake but unfortunately it's not that.

Below two screenshot about my configuration on Zenodo and Seek, maybe there are errors I didn't see or fields are filled in wrong (especially Redirect URIs).

**Zenodo configuration**

![zenodo_1](https://user-images.githubusercontent.com/1289992/43075812-327bf520-8e82-11e8-95d6-4a123cbe9052.png)

**Seek configuration**

![zenodo_2](https://user-images.githubusercontent.com/1289992/43075815-3570b748-8e82-11e8-886c-ee43b946d36b.png)

Thanks,
Cyril

**Comment by fbacall** [comment]
Here are my settings:
![z_zenodo_settings](https://user-images.githubusercontent.com/503373/43077687-1571dd3e-8e80-11e8-9e2c-e2370b572bb8.png)

![z_seek_settings](https://user-images.githubusercontent.com/503373/43077676-11357abe-8e80-11e8-8659-d0868fcf5e24.png)

A few differences:
* I am specifying the `/zenodo_oauth_callback` endpoint on the Zenodo redirect URI.
* I have trailing `/` on the Zenodo API and OAuth URLs

Another point, did you create your client on the sandbox ( https://sandbox.zenodo.org/account/settings/applications/clients/ ) ?

**Comment by fbacall** [comment]
Does the error occur immediately after you click the "Export to Zenodo" button?

Can you check the URL in your browser?

Mine is:
```
https://sandbox.zenodo.org/oauth/authorize?client_id=<my_client_id>&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fzenodo_oauth_callback&response_type=code&scope=deposit%3Awrite+deposit%3Aactions&state=%2Fassays%2F75%2Fsnapshots%2F1%2Fexport
```

**Comment by cmonjeau** [comment]
Hi,

When I click on Export to Zenodo, the URL sent is : 

`https://sandbox.zenodo.org/oauth/authorize?client_id=<my_client_id>&redirect_uri=http%3A%2F%2Fresearch-sharing.cesgo.org%2Fzenodo_oauth_callback&response_type=code&scope=deposit%3Awrite+deposit%3Aactions&state=%2Finvestigations%2F1%2Fsnapshots%2F3%2Fexport`

A first problem is the redirect_uri is not in https. When I change the URL manually, I have the authorization page. And when I click on 'Authorize apllication', I have a SEEK error:

> E, [2018-10-05T08:51:38.809522 #85] ERROR -- : ERROR - RestClient::BadRequest (400 Bad Request)
I, [2018-10-05T08:51:38.811575 #85]  INFO -- : method=GET path=/zenodo_oauth_callback format=html controller=Zenodo::Oauth2::CallbacksController action=callback status=500 duration=125.81 view=0.79 db=1.98 time=2018-10-05 08:51:38 +0000 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
F, [2018-10-05T08:51:39.151252 #85] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/lograge-0.4.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `call'
  vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by fbacall** [comment]
Right, so it is getting a 400 error from Zenodo when attempting to get the auth token...

This is the code where that happens: https://github.com/seek4science/seek/blob/master/lib/zenodo/oauth2/client.rb#L35

`@client_id`, `@client_secret` and `@redirect_uri` all come from your SEEK settings, and `code` should be a parameter on the redirect.

My guess is that the `@client_secret` is maybe malformed, or the `code` param has been mangled by some web server settings. Maybe you could add some logging to that part of the code to check if everything is correct?

**Comment by cmonjeau** [comment]
It seems one of the problems is the @redirect_uri parameter. I use docker to deploy Seek and we have a webproxy to run app through https. I add in the nginx config the line: 

> proxy_set_header   X-Forwarded-Proto https;

With this line, I have the good authentification page and the application is now in the authorizated application field. 

![image](https://user-images.githubusercontent.com/1289992/46534680-553eb000-c8a9-11e8-8d57-bea5419b3ac8.png)

But I have another error after this step : 

> I, [2018-10-05T12:10:15.834698 #46]  INFO -- : method=GET path=/zenodo_oauth_callback format=html controller=Zenodo::Oauth2::CallbacksController action=callback status=302 duration=223.87 view=0.00 db=8.67 location=https://research-sharing.cesgo.org/investigations/1/snapshots/1/export time=2018-10-05 12:10:15 +0000 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
E, [2018-10-05T12:10:15.882708 #46] ERROR -- : ERROR - ArgumentError (comparison of Hash with Hash failed)

@client_id and @client_secret are good.

**Comment by fbacall** [comment]
Ah! I get the same problem now... I will push a fix to `master`.

You can probably `git cherry-pick` the commit if you don't want to merge the entire branch.

**Comment by cmonjeau** [comment]
Thanks a lot, it works now.

Have a good day,
Cyril
