### ISSUE TITLE
Add time zone information to Events

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#640]
As a user I would like to be able to add time zone information when creating Events.
When not entering any time zone information, Event defaults to UTC.
Time zone would be recorded as difference to UTC.
Agreement needed on how to present time zone choices to user.

**Comment by floradanna** [comment]
Could it be fixed as part of maintenance work?

**Comment by stuzart** [comment]
> Could it be fixed as part of maintenance work?

No, the maintenance work is ending anyway. But we can plan to include this in the next set of tasks

**Comment by alaninmcr** [comment]
As Stuart said, the maintenance sprint is coming to an end.

One solution could be would be to keep the time in UTC in the database, and to use Javascript to convert to the browser's local time zone when the event is displayed. Other calendar systems seem to do something similar.

When the event is created, you could specify the timezone and it would be converted to UTC for storage.

That's just a quick idea though.


________________________________________

**Comment by fbacall** [comment]
@stuzart did you mean to move this from "Done" to "In progress"?
