### ISSUE TITLE
cwltool 3.0.20201203173111 not compatible with Docker container 20201203173111

### ISSUE THREAD

**Issue by stain** [seek4science/seek#646]
7f9ae90 bumped the cwltool version in `requirements.txt` to `3.0.20201203173111` - however as the Debian 9 base image of `Dockerfile` (via `ruby:2.6-stretch`) is based on Python 3.5, building it will fail with:

```
Collecting cwltool==3.0.20201203173111 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement cwltool==3.0.20201203173111 (from -r requirements.txt (line 1)) (from versions: 0.1.20141118163626.cbb1b06, 0.1.20141118185349.d594c3e, 0.1.20141119031726.8dcd753, 0.1.20141125184103.2d72b5c
```

The last known Python 3.5 compatible `cwltool` is `3.0.20200807132242`.

Python 3.5 was deprecated with 5 Sept 2020 which is around the same time.

Suggestion: Change `Dockerfile` with `sed` to force use of older `cwltool==3.0.20200807132242` – or update  to `FROM ruby:2.6-buster` ?

**Comment by stain** [comment]
Workaround in 8e37ef5d63d3ca824520115b775d5438c345b49b but given that Debian 10 was released in 2019-07-06 perhaps it's rather time to update the base image..

**Comment by stain** [comment]
@simleo point out:

> The catch is that stretch does not support python 3.6, but switching to buster does not work either because it does not support openjdk 8
> You get openjdk 11, which breaks Solr

**Comment by stuzart** [comment]
There is now a new Dockerfile on the master branch which uses buster and should solve the problems.

**Comment by stuzart** [comment]
> $> docker run -it --rm fairdom/seek:workflow bash
> $> python --version
> Python 3.7.3
