### ISSUE TITLE
Remove solr dependency from Dockerfile

### ISSUE THREAD

**Issue by stain** [seek4science/seek#648]
See #647 – as Solr is started separately by `docker-compose.yml` through the [seek-solr](https://github.com/FAIRdom/solr-seek-docker/blob/master/Dockerfile) image which (if rebuilt) indirectly now will start [solr 8.9 using openjdk 11](https://github.com/docker-solr/docker-solr/blob/a1a59aa9d3ef286fe1e046ddfd168c3c34720660/8.9/Dockerfile).

This avoids the need for openjdk 8 workarounds for Debian 10 base image. 

I don't see a need for this `Dockerfile` to play double-duty as both `seek` and `seek-solr`. If this was needed for users unable to run Docker Compose, that should be a third dockerfile.

**Comment by stain** [comment]
Java itself is also needed by Rightfield, 

```
./lib/rightfield/rightfield.rb:  JAR_PATH = File.dirname(__FILE__) + '/rightfield-bin.jar
```

...but that should hopefully work fine with `openjdk-11-jdk` (possibly even `openjdk-11-jre-headless`).

**Comment by stuzart** [comment]
The solr is bundled as part of the rails dependencies, it isn't a separate dependency within the Dockerfile. It is often useful to be able to run as a single container for a quick evaluation or for testing, and the only different is in the startup. 
The real issue here is the problem of running rails-solr with openjdk 11, which also effects users installing and running without Docker

**Comment by stuzart** [comment]
I've been digging into this a bit closer, and it does seem that removing the [sunspot_solr](https://github.com/sunspot/sunspot/tree/master/sunspot_solr) gem is no longer maintained, even the latest version doesn't seem to work with Java 11. There are no other dependencies on this gem, and is simple used as a convenience for starting solr ( I previously thought it was tied to the sunspot_rails gem)
So I now agree, and think the only sensible solution is to remove this and document an alternative way of running solr including for those users that are unable to use docker
