### ISSUE TITLE
Sample-data file assocation

### ISSUE THREAD

**Issue by DanBerrios** [seek4science/seek#67]
Trying to use seek for RNA-Seq data. How can I give the assocation between a list or individual sample and individual data file or set of files (with assay results)? I can't see any field on Sample to link to data files...and I can't see any field on Data Files to link to individual samples.  I am starting with ISATab files...

**Comment by stuzart** [comment]
Hi. Sorry for the long time replying.
You can't currently directly link Samples to Data Files, except in the case that Samples have originated from a Samples template. The way to link Samples and Data is to do so through an Assay, which describes the process that resulted in the association.

**Comment by alaninmcr** [comment]
I think Stuart's answer covers the question
