### ISSUE TITLE
KNIME workflow cannot be imported

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#677]
If a KNIME workflow lacks a name or a description, then the import fails. This is because it tried to get the value of a node that does not exist.

The code should use &. rather than .

The relevant file seems to be lib/seek/workflow_extractors/knime.rb

**Comment by fbacall** [comment]
Can you include an example of a workflow that causes this to happen?

**Comment by alaninmcr** [comment]
[w.knime.txt](https://github.com/seek4science/seek/files/6917305/w.knime.txt)
