### ISSUE TITLE
Branding admin page has wrong text

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#679]
The text talks about Project. This follows https://github.com/seek4science/seek/blob/master/app/views/admin/rebrand.html.erb

This seems to assume there is one Project in a SEEK installation. It needs to be reworded,

**Comment by stuzart** [comment]
some additional tasks spotted so far

- [ ] About page link, and the About in the footer use different settings
- [ ] Fix cases where application_name is used, where project_name should be
- [ ] Rename settings to match the new descriptions

**Comment by aapaolaza** [comment]
Regarding the about page link, can we remove "Data management Project link", and just reuse the "About link" option from Information links, with an added _(shown in footer as well)_ warning?

**Comment by stuzart** [comment]
> Regarding the about page link, can we remove "Data management Project link", and just reuse the "About link" option from Information links, with an added _(shown in footer as well)_ warning?

We can't remove dm_project_link, as this is used elsewhere such as describing the Organization that runs the service in the bioschemas. However, in this case It would be project_link that would be used, which could become instance_about_link when renamed. I was thinking of using this, and replace the about link setting to be flag to turn the menu item on or off
