### ISSUE TITLE
Log in problem with recent Firefox

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#68]
Hi, 

I observed a connection problem with Firefox 59.0.1 and SEEK v1.5.2 (and 1.6.0-dev).

After completing the fields, the user is redirected to the required page but is not logged in.

There are no error messages in the console or in the search logs.

It works when the "Remember me" button is checked.

Have you observed this problem?

**Comment by fbacall** [comment]
Hi Cyril,

I've not had this particular problem, although we did make a change in February to expire sessions after 15 minutes of inactivity: https://github.com/seek4science/seek/commit/c3dff3d34ee18400cc29266b2dcb2adf3c326eb6

If this is on a development instance, maybe you could try clearing out all sessions from the database and trying again:
`bundle exec rake db:sessions:clear`

**Comment by cmonjeau** [comment]
Hi, Finn,

it's definitely related to this change.

The clear session does nothing. 

But it works when I delete your changes in config/initializers/session_store.rb.

When I increase the time to 30 minutes or with a higher value, it also works.

I don't know why you don't see that on your side and why only the new version of Firefox is affected. (it's ok with Chrome)

**Comment by fbacall** [comment]
Hi,

I have spent some time looking into the sessions code of Rails, and cannot see how session expiration is handled for `active_record_store` ... I am using Firefox for development and for me it seems that it correctly expires after 15 minutes.

If you set it to 30 minutes does it correctly expire the session after 30 minutes? Or sooner? Could it be an issue with system clocks being out of sync?!

Not really sure what else to suggest, sorry :(

**Comment by cmonjeau** [comment]
Hi, Finn,

Thank you very much for your answer. Actually, the time of my development machine and my production machine was not correct... weird. 

I'm really sorry you wasted your time. We now know that Firefox is more sensitive to this than other browsers.
