### ISSUE TITLE
Add the description or help text for custom metadata attributes 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#684]
The description can help users to understand the meaning of the metadata and what they need to enter here.

E.g.
![image](https://user-images.githubusercontent.com/42063448/129190917-0eef1523-e512-4648-a9e1-7caad3991ced.png)

**Comment by rabuono** [comment]
This looks similar to #627 
A description of attributes in general would be useful, in Custom Metadata attributes and in Sample Type attributes. Can this be also applied to Sample Type attributes?

**Comment by stuzart** [comment]
yes they are very similar, and the changes can be transferred across as they share a lot of behaviour.
Thanks for tagging the related issue, I was about to do so myself :)
