### ISSUE TITLE
Upgrade documentation: Mention "gem install bundler" after switching ruby versions

### ISSUE THREAD

**Issue by marteber** [seek4science/seek#7]
Hello everyone,

I have recently tried to upgrade our SEEK instance from 0.21 to 1.0.2 by following the commands listed in the docs at:
http://docs.seek4science.org/tech/earlier-upgrades.html 
http://docs.seek4science.org/tech/upgrading.html
When I failed to get `bundle` registered as a command upon installing a newer ruby version with `rvm install ruby-2.1.x`, I (no ruby experience at all) realized after some time that I needed to run `gem install bundler` before continuing. Could you change the docs to mention that?

**Comment by stuzart** [comment]
Many thanks for pointing this out to us.
