### ISSUE TITLE
Can't import Knime workflow as knwf 

### ISSUE THREAD

**Issue by stain** [seek4science/seek#720]
**Describe the bug**

When attempting to upload a KNIME workflow as a `.knwf` file and workflow type as "KNIME", WorkflowHub fails with an error.

**To Reproduce**
1. Upload the `.knwf` file within https://workflowhub.eu/workflows/201 as "Basic workflow upload"
2. Set workflow type as KNIME

**Workaround**

Upload as "Other", then change to "KNIME" to edit description manually.

**Additional context**

KNIME workflows used to be XML files within a workspace folder, but it is now possible to save a `knwf` archive our of KNIME, which is basically a ZIP file of that folder and its data at that point.

WorkflowHub seems to try to parse upload as XML independent of filename - the XML file would be located within the `.knwf` ZIP file.

**Comment by fbacall** [comment]
Are `.knwf` always zip files? The structure seems to be: `<zip>/<directory>/workflow.knime`, where `workflow.knime` contains the XML that can be parsed.

There is also `.knar`.

Would be good to read a spec about the various KNIME formats.
