### ISSUE TITLE
R package using the API to access SEEK

### ISSUE THREAD

**Issue by jcolomb** [seek4science/seek#73]
I am no specialist, but is there a package one can use? the API seems to be quite general...

**Comment by stuzart** [comment]
Actually, sorry I may be mistaken. Having taken a closer look, I don't see R listed. I'm afraid I'm not aware any other R packages. Perhaps one of the other available packages will suit you?

**Comment by jcolomb** [comment]
I will dig into it, it seems rapiclient might be a good start, and that ropensci is already working on openapi integration...
