### ISSUE TITLE
Tables broken in workflow description markdown

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#733]
Affected file: https://github.com/Sydney-Informatics-Hub/Germline-ShortV/blob/cdef7e93d6c5e660ae5e1bd863c0c3bb95b794b6/README.md

Need to enable some setting in renderer?

![image](https://user-images.githubusercontent.com/503373/136758022-8980cc6a-3db6-4f94-87f0-757e0b74b062.png)

**Comment by stuzart** [comment]
would this work with the description preview ?

**Comment by fbacall** [comment]
No, that uses some other JS renderer
