### ISSUE TITLE
project creation requests table

### ISSUE THREAD

**Issue by wittigue** [seek4science/seek#748]
The table for pending project creation requests doesn't disappear if project was rejected.

A project was rejected by me because the project title was invalid ("tst" was already used in another programme).
Now the table and info banner about project creation request is still there but empty.

![Screenshot 2021-10-13 143450](https://user-images.githubusercontent.com/29859147/137134137-cd5828f1-4b78-4e3a-9e66-9d8fddd8da30.png)

**Comment by stuzart** [comment]
are you sure you rejected it? It seems like it was accepted but there was an error with an invalid URL that occurred (which we think may have been a cause by a space). The institution got rejected

**Comment by stuzart** [comment]
not been able to duplicate and it hasn't occurred again
