### ISSUE TITLE
SSL cert expired for https://demo.seek4science.org

### ISSUE THREAD

**Issue by mathuaerknedam** [seek4science/seek#75]
From Chrome: 

> Your connection is not private
> Attackers might be trying to steal your information from demo.seek4science.org (for example, passwords, messages, or credit cards).
> NET::ERR_CERT_DATE_INVALID
> 
> This server could not prove that it is demo.seek4science.org; its security certificate expired 27 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Monday, January 28, 2019. Does that look right? If not, you should correct your system's clock and then refresh this page.
>

**Comment by fbacall** [comment]
This is fixed now, thanks for reporting.
