### ISSUE TITLE
Provide easy access to ids in web interface (tree & folder view)

### ISSUE THREAD

**Issue by matthiaskoenig** [seek4science/seek#77]
Currently the ids of assets are very cumbersome to find. The only way is to click on an asset and than look in the url of the web browser.

It would be great if the ids are easily accessible via the tree and folder view. For instance in the screenshot attached I want via `hover over items` or `select` getting the id & type of the respective asset. So for instance on mouse over display something like `data_files/205` or `assays/17`

![SEEK_screenshot](https://user-images.githubusercontent.com/900538/55973548-1b020100-5c86-11e9-8e28-6903835a8557.png)

I often work via scripts with the REST API with SEEK, finding out the ids of things (which are required to make the REST calls) is a big challenge. 

In addition: I really like the split tree/graph view, but unfortunately the tree part is not usable in split screen because most of the labels are not visible (also see screenshot). The tree should have more space, or it should be possible to change how much space the tree and graph get by moving the separator.

**Comment by stuzart** [comment]
the ID is available on the page of the current item (SEEK ID). For your other case, we could include it in the panel at the top of the graph (that shows the title and description) for the selected node.
I'll also look into making the tree view wider.
thanks.

**Comment by matthiaskoenig** [comment]
Yes, the id of the current item is easily accesible via the url. The difficult part is to get an overview of the ids of the objects in the graph. 
For instance I want to delete all the images associated in the graph.
Currently I have to click on every image and navigate to the asset page to get the respective id. This is very cumbersome. If the ids could be directly accessible in the tree view this would make things much easier. 
Possible solutions:
- provide Id information on mouse hover in the graph and tree view
- add id to the graph labels and trees, e.g. display `[138] CSV (Tanaka2014)` instead of just ` CSV (Tanaka2014)`

**Comment by matthiaskoenig** [comment]
Hi all, 
I tried today the SEEK 1.9 via the fairdomhub. The ids are now easily accessible. Thanks so much.
This issue can be closed.
Best Matthias
