### ISSUE TITLE
Server upgrade: NoMethod error

### ISSUE THREAD

**Issue by Linus4** [seek4science/seek#770]
**Describe the bug**
When executing the `docker/upgrade.sh` scripg (version `1.10.3` to `1.11.2`) I get an error. 

**To Reproduce**
1. Follow [instructions](https://docs.seek4science.org/tech/docker/docker-compose.html) (Upgrading between versions)
2. `docker exec -it seek docker/upgrade.sh` fails with `NoMethod error`

**Expected behavior**
Upgrade should complete successfully.

**Logs**

```
$ docker exec -it seek docker/upgrade.sh
... Setting version visibility...
  Updating 230 DataFile::Version's visibilityrake aborted!
NoMethodError: undefined method `latest_version' for nil:NilClass
/seek/lib/seek/explicit_versioning.rb:69:in `latest_version?'
/seek/lib/tasks/seek_upgrades.rake:140:in `block (5 levels) in <top (required)>'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:70:in `each'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:70:in `block in find_each'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:222:in `loop'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:222:in `in_batches'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/seek/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/batches.rb:69:in `find_each'
/seek/lib/tasks/seek_upgrades.rake:139:in `block (4 levels) in <top (required)>'
/seek/lib/tasks/seek_upgrades.rake:127:in `each'
/seek/lib/tasks/seek_upgrades.rake:127:in `block (3 levels) in <top (required)>'
/seek/lib/object_extensions.rb:24:in `disable_authorization_checks'
/seek/lib/tasks/seek_upgrades.rake:126:in `block (2 levels) in <top (required)>'
/seek/lib/tasks/seek_upgrades.rake:47:in `block (2 levels) in <top (required)>'
/seek/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => seek:upgrade_version_tasks => seek:set_version_visibility
(See full trace by running task with --trace)
```

**Server:**
 - OS: CentOS7
 - Dockerized? Yes
 - SEEK version: 1.10.3 -> 1.11.2

**Comment by stuzart** [comment]
there seems to be a problem with old DataFile::Version references being around with no parent. The versions should be destroyed when the parent is, but is possible from the past there was a bug that prevented this happening cleanly. 
Do you remember which version, or a rough idea of when, you originally installed you first version of SEEK ?

**Comment by Linus4** [comment]
The server was set up in March 2017, I think. I found an upgrade announcement to version 1.3.0 from June 2017. This was before I joined the institute.

**Comment by stuzart** [comment]
I've pushed a new image which should overcome the problem. Can you try doing the upgrade steps again. You can just re-run it again over the previous upgrade without needing to restore your backup again (although there is no harm if you do). To save going to the docs, they are:

> docker-compose down
> docker-compose pull
> docker-compose up -d seek db solr                
> docker exec -it seek docker/upgrade.sh
> docker-compose down
> docker-compose up -d

**Comment by stuzart** [comment]
OK. Try again. I think I made a mis-assumption that the parent id was nil rather than referencing an id that doesn't exist anymore.

**Comment by Linus4** [comment]
:tada: It worked! `Upgrade completed successfully` Thanks a lot @stuzart !

**Comment by stuzart** [comment]
yay. thanks for reporting it, along with the other problem
