### ISSUE TITLE
Ability to tag with EDAM ontologies

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#780]
this currently refers to being able to tag a Workflow, but could also include other cases such as templates.

The Ontology CV's can be used for this, and be preloaded through the database seeding.

- [x] Decide the root node
- [x] Preload edam ontology from OLS through the UI
- [x] Add a specific EDAM annotation to asset
- [x] Reuse / Refactor UI element from samples/custom metadata to select the tag
- [x] Do we need to support multiple tags?
- [x] Support multiple tags
- [x] display the tags
- [x] Generate a DB SEED for the Ontology CV
- [x] Add ability to use EDAM Operations
- [x] Prevent the Ontology CV being edited by others
- [ ] ~~Add the tags to the schema.org~~ _the bioschema profile needs updating_
- [x] Generalize and pull into Concerns & partials
- [x] Include in search indexing and filtering

**Comment by fbacall** [comment]
Relates to #182
