### ISSUE TITLE
Visibility of reports at the project level

### ISSUE THREAD

**Issue by smza** [seek4science/seek#788]
**Describe the bug**
If a datafile is only linked to a project and not linked to an assay it is not visible in the tree view. In IBISBA we have the final project reports and it is logical to assign them ONLY to the project and not any assay. Is it possible to make reports and related documents viewable in the tree view?

**Expected behavior**
A file that is not linked to an assay should be seen under the project in tree view

**Comment by alaninmcr** [comment]
This could be achieved by changing the code of ISAGraphGenerator associations method. Need fuller specification though. Alternatively it could be made configurable (maybe)

**Comment by alaninmcr** [comment]
There is a proposal to revisit the current ISA tree generation. This could be done as part of that

**Comment by alaninmcr** [comment]
Alan to raise with tech team

**Comment by stuzart** [comment]
@alaninmcr lets include this in 1.12.0 then, I've updated the milestone and put on the 1.12 todo list

**Comment by floradanna** [comment]
If assets related to a project will be shown under a project in the Overview, what would be the difference with the Organise page? Both will show assets related to project and ISA.
- [Overview](https://testing.sysmo-db.org/projects/12/overview)
- [Organise](https://testing.sysmo-db.org/projects/12/folders)

**Comment by fbacall** [comment]
Overview is visible to all, Organise is project-internal

**Comment by alaninmcr** [comment]
Stuart has also said that Organise can be ignored.

**Comment by floradanna** [comment]
I see. I was not aware that IBISBA reports and documents needed to be seen by people that are not part of the project.

I am a bit concern because I believe that when files start accumulating under a project, people would want to be able to group/organise them. This would them mean to have "folders", as in Organise.

**Comment by stuzart** [comment]
@alaninmcr there was a task to make the folders lockable by the project admins

**Comment by alaninmcr** [comment]
It shows collections. I made a new method for Project that returns the assets filtering out the ones that are associated with an investigation (which covers studies and assays). Collections are assets.
