### ISSUE TITLE
Being able to add contributors with edit rights to a publication

### ISSUE THREAD

**Issue by saharhas** [seek4science/seek#79]
Adding publication to the SEEK is very helpful both for the people involved in a project and everyone else. It seems that it is not possible to add people (rather than authors) with edit rights to the publication. For example, it is important to be able to link the data manager to a publication so that he/she can edit the publication if needed. I hope this option can be added to SEEK :-)

**Comment by whomingbird** [comment]
Thanks for your suggestion, which makes sense.  We will discuss it within our SEEK development team and let you know if we want to add this as a new feature in the near future.

**Comment by alaninmcr** [comment]
@whomingbird Do you know the status of this?

**Comment by whomingbird** [comment]
Currently publications which are manually registered and imported via BibTex can be edited by contributors. 
The publications registered by DOI can not manually change the publication metadata, can "refetch" the metadata from DOI service again.

**Comment by alaninmcr** [comment]
I think it can be closed.
