### ISSUE TITLE
Error while deleting a project

### ISSUE THREAD

**Issue by smza** [seek4science/seek#790]
I was trying to delete a test project from the IBISBAHub after deleting all the files but encountered the following error (image attached)
<img width="1228" alt="Screenshot 2021-11-17 at 11 16 51" src="https://user-images.githubusercontent.com/20230281/142191046-f4686aab-ad16-4d43-94af-a1e13bf427a6.png">

**Comment by alaninmcr** [comment]
Cannot replicate
