### ISSUE TITLE
Display Data Type and Format Selected for Data files

### ISSUE THREAD

**Issue by smza** [seek4science/seek#795]
When we assign format and data type to a data file,  we cannot see what format/type has been chosen after collapsing the menu. It’ll be useful to display the user selected format and type.

**Comment by stuzart** [comment]
can you explain what you mean by format and data type. Could you provide a screenshot.

The format is automatically detected, and displayed on the main page and indicated by the icon, e.g.

![image](https://user-images.githubusercontent.com/201658/142391661-b44cba4b-802a-4683-a188-3107477206a2.png)

**Comment by smza** [comment]
<img width="904" alt="Screenshot 2021-11-18 at 11 32 53" src="https://user-images.githubusercontent.com/20230281/142407803-95c86940-7acd-4724-9abc-67addd9bbd8e.png">

For e.g. In the image I've selected the data type "Secondary Structure Alignment" but once we collapse the Data menu we can no longer see the selection that was made.

**Comment by alaninmcr** [comment]
Can be quick fix now

**Comment by alaninmcr** [comment]
Doesn't this apply to License ?

**Comment by alaninmcr** [comment]
Munazah says yes - should be consistent.

**Comment by alaninmcr** [comment]
Now looks like:
![type_selection](https://user-images.githubusercontent.com/349232/144845752-f321a581-1114-488e-8bb2-9ae6a25094ec.PNG)

**Comment by smza** [comment]
Thanks Alan. Why do we have a "Current Format"  and a "Selected Format". Shouldn't it just be the Selected Format?

**Comment by alaninmcr** [comment]
The current format is what the resource (e.g. data file) currently has. The selected format has been chosen from the tree. It hasn't yet actually been assigned to the data file. That only happens when you press Update.

It's easy to change the text

**Comment by smza** [comment]
that would confuse people. I would just display the *Selected Format*, because that will be the relevant information, once the update button is pressed.

**Comment by alaninmcr** [comment]
So do not show the current format?

**Comment by stuzart** [comment]
do you not need a different name. As @alaninmcr is indicating, there is already the file format that is automatically detected and set, but what you are wanting to select here seems to be something different, like the semantic format (but don't use that!).

How does it display the 2 different uses of Format on the items page?

**Comment by smza** [comment]
So if I understand correctly, *current format* means the automatically detected/assigned format by SEEK?
@alaninmcr @stuzart

**Comment by alaninmcr** [comment]
I think Stuart is correct. The EDAM format type may be different to the detected format of the file.

**Comment by smza** [comment]
> I think Stuart is correct. The EDAM format type may be different to the detected format of the file.

Yes. So even more confusing.... if there is already a default being selected why are we giving the EDAM option? Either we make the default selection defunct or the default should also use the EDAM ontology.

**Comment by alaninmcr** [comment]
This is changed because of harmonisation with the main SEEK branch. Would be good if comments were made on the EDAM annotation of workflows

**Comment by alaninmcr** [comment]
Done
