### ISSUE TITLE
View registered organisms/Remove a registered organism

### ISSUE THREAD

**Issue by marteber** [seek4science/seek#8]
Hello again,

as a follow-up to my problems with upgrading (see #7), I ended up reinitializing our (mostly empty anyway) SEEK instance at 1.0.2. As an administrator, I can now add organisms, but I cannot remove them or even find any way to see which organism are already registered. I have noticed that organisms is the only category for which browsing is not possible - is that by design?

**Comment by eilidh-t** [comment]
The organisms used to be listed on the home page in a box on the right hand side. 
https://groups.google.com/forum/#!searchin/seek-developers/organisms/seek-developers/Bh5ryHcLlZ8/co92UcbMJ4MJ <https://groups.google.com/forum/#!searchin/seek-developers/organisms/seek-developers/Bh5ryHcLlZ8/co92UcbMJ4MJ>

On 3 Mar 2016, at 09:47, marteber <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Hello again,
> 
> as a follow-up to my problems with upgrading (see #1 <https://github.com/seek4science/seek/pull/1>), I ended up reinitializing our (mostly empty anyway) SEEK instance at 1.0.2. As an administrator, I can now add organisms, but I cannot remove them or even find any way to see which organism are already registered. I have noticed that organisms is the only category for which browsing is not possible - is that by design?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/seek4science/seek/issues/8>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by fbacall** [comment]
We recently removed the organisms box from the front page, but I now realise that leaves nowhere where the full list of organisms can be browsed and managed!
