### ISSUE TITLE
SEEK mixes up "Title" ontology terms from different classes

### ISSUE THREAD

**Issue by saharhas** [seek4science/seek#80]
Trying to import a RightFielded data file into SEEK that will be linked to an existing assay (by assay SEEIK ID), will work perfectly unless there are cells with both "Asset>Data (include a property) Title" and "Person (include a property) title". Uploading such data file into SEEK leads to both linking the data file to the correct assay, as well as creating a new assay using the person title as its title. 
An example data file with the above-mentioned properties is attached.    
[TestTitle.xlsx](https://github.com/seek4science/seek/files/3212040/TestTitle.xlsx)

**Comment by alaninmcr** [comment]
Cannot reproduce. Please reopen if you think this is still an issue
