### ISSUE TITLE
Precompile assets during upgrade

### ISSUE THREAD

**Issue by johannes-darms** [seek4science/seek#800]
**Describe the bug**
To upgrade an existing seek installation (database and volume), the guidelines suggest running `./docker/upgrade.sh` inside the newly created container. This will upgrade the seek instance (database and volume). However, after the upgrade, the assets are not deployed correctly when running in a subpath environment. Restarting the container solved the problem as `assets:precompile` is executed at startup. I suggest adding the rake task to the upgrade script to simplify the upgrade process.

**Comment by stuzart** [comment]
this has now been resolved along with other subpath related fixes
