### ISSUE TITLE
Searching / accessing users emails and login through API for administrators

### ISSUE THREAD

**Issue by mboudet** [seek4science/seek#803]
Hello,

We are currently hosting a Seek instance linked to our ldap. We sometimes need to delete an user from the ldap, and would like to automate the user deletion from Seek.

As far as I know, the only way to delete an user through the API is to search his name (or iterate on all users) to get his seek ID, and then delete it with an api call.

Is there any way to search for, or access, either the user login or email through the api (restricting the option to administrators of course)? The login is displayed in the user page for administrators, but it does not seems to be accessible through the /people/id route.

**Comment by alaninmcr** [comment]
You can search for the user with a call similar to:

curl -X 'GET'   'https://myseek,org/search?q=user_name&search_type=people'   -H 'accept: application/json'

That should return a JSON document containing a (possibly empty) list of people that include the user_name

**Comment by mboudet** [comment]
Hmm, it does not seems to work on my instance. (Built using the 1.11 docker image)

My username being 'mboudet'

```
root@seek-test:~# curl -H 'Authorization: Token XXXX' -H 'Accept: application/json' 'http://0.0.0.0:80/search?q=mboudet&search_type=people' | jq .
{
  "data": [],
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/search?q=mboudet&search_type=people"
  },
  "meta": {
    "base_url": "https://research-sharing.cesgo.org",
    "api_version": "0.3"
  }
}
```
(Using my name for the search works fine)

**Comment by alaninmcr** [comment]
Aha SEEK distinguishes between a User and a Person. Objects are owned by a Person. There may be multiple user accounts (or none) that map to the same Person. The login name is associated with a User, not a Person.

The search only looks at the Person information, so does not find what is being looked for.,

**Comment by mboudet** [comment]
So, is there any way of doing it? I'd rather not use the name/surname, in case they are not unique..

**Comment by stuzart** [comment]
we discussed this in a recent meeting, and feel it is unsafe to include the username in the search indexing, but we could include the email address. We will include this change in our next version

**Comment by mboudet** [comment]
Great! This will help for the scripting.

However, I realized that in our case (LDAP login only), there can be a desync between the user's currently registered mail in our database, and Seek's email (especially since an user can modify the email by themselves).

If indexing the login name is unsafe, would it be possible to access it by directly getting the user information through the _/people/id_  route? Of course, restricting this information to administators. (I'm fine with looping over all users if there is no matches for the email address).

Since the login name is already displayed on an user page when using the UI (just not when using the API), I feel like this should be fine security-wise

**Comment by stuzart** [comment]
Including the login when accessing the api with an admin authentication should be OK, I think. 

Another idea I had, before I read your suggestion, is something like the http://xmlns.com/foaf/doc/mbox_sha1sum.en property we use in the api, that allows matching to an email address without exposing it. We could perhaps do that same with the login - but I think I prefer your suggestion

**Comment by stuzart** [comment]
a new attribute `login` will be available in the API for Person, but only available to administrators
