### ISSUE TITLE
Abstract is not extracted from publication registered via DOI

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#804]
https://github.com/seek4science/seek/blob/master/app/models/publication.rb#L221-L234

**Comment by fbacall** [comment]
^ is possibly not the source of the problem

Problematic DOI is: `10.12688/f1000research.54159.1`

**Comment by whomingbird** [comment]
the link to fetch the metadata
https://doi.crossref.org/openurl?format=unixref&id=doi%3A10.12688%2Ff1000research.54159.1&pid=sowen%40cs.man.ac.uk&noredirect=true

the place to parse the abstract
https://github.com/seek4science/DOI-query-tool/blob/e7a8790f666b9b20e22149d6a450ed85e60504d3/lib/doi/query.rb#L67
