### ISSUE TITLE
Configure oauth via ldap

### ISSUE THREAD

**Issue by CFGrote** [seek4science/seek#82]
Dear Seek developers,
How would I (as admin of a seek instance) setup oauth via ldap?  I can't find it in the Admin panels, nor in any of the documentation.

Thanks!

**Comment by CFGrote** [comment]
just noting that #41 is related.

**Comment by CFGrote** [comment]
After fiddling with the ldap config in config/initializers/seek_configuration.rb, I'm now at a state where I get a

    No route matches [POST] "/auth/ldap/callback"

Can anyone tell me what that means?

From observing the logs on the ldap server, the authentication seems to be successful, so my current hypothesis is that something goes wrong on the ldap client side.

**Comment by fbacall** [comment]
Hi. This looks like a bug - SEEK is expecting an HTTP `GET` request for the LDAP callback, not a `POST`.

Apologies for the lack of documentation/support around LDAP. We are currently improving the authentication system in SEEK (to allow it to connect to a variety of providers etc.).

**Comment by CFGrote** [comment]
aah, this makes sense now.  attached patch fixes the issue and i can login via ldap.

thanks a bunch!
[patch.txt](https://github.com/seek4science/seek/files/3350191/patch.txt)

**Comment by fbacall** [comment]
Great!

Another way would be to change this line: https://github.com/seek4science/seek/blob/master/config/routes.rb#L790 from "get" to "post". I think there may be some security issues around using GET requests for authentication.

**Comment by CFGrote** [comment]
@fbacall , your solution also works. 
would it make sense to make a PR or will this be fixed in branch "merge_AAI" anyway?

**Comment by fbacall** [comment]
I think it *should* be fixed in that branch, although I'll leave this issue open just in case.

**Comment by stuzart** [comment]
this was fixed with #90
