### ISSUE TITLE
Add documentation: how to configure session timeout

### ISSUE THREAD

**Issue by johannes-darms** [seek4science/seek#820]
**Describe the error**
While users are filling out a form, the user is logged out without notification. As a result, the data entered is lost. It would be nice if there was a) notification of the end of the session, b) a feature that allows the user to pick up where they left off, and c) documentation on how to increase this expiration timer. The latter is what is requested in this ticket.

I believe it is configured by [1] and I can change the value via the `session_store_timeout` configuration value. However, it took me some time to find this information.
[1]https://github.com/seek4science/seek/blob/7a6b9528222c211d221c265061643eacb3cec37a/config/initializers/session_store.rb

**Comment by stuzart** [comment]
updated to be changed through the admin settings UI, but not yet documented
