### ISSUE TITLE
Empty drop-down for sample-type-block after redirect

### ISSUE THREAD

**Issue by vdkkia** [seek4science/seek#822]
**Describe the bug**
The _sample-type-block_ drop-down is empty after redirect (in case of any error in the form) if the selected type is **seek_sample** or **seek_sample_multi** and if the selected value was **self** (_this_sample_type_)

**To Reproduce**
1. Go to the new sample type form
2. Add an attribute of type seek_sample or seek_sample_multi
3. Select this_sample_type from the drop-down menu
4. Leave some required fields blank to make sure about redirection to the current page/form

**Screenshots**
![image](https://user-images.githubusercontent.com/4618481/146194070-eb483ede-36c3-4be3-971c-60c294fd24fb.png)

**Comment by vdkkia** [comment]
I think setting the value to `0` for `<This sample type>` option instead of 'self' will solve the issue.
[This](https://github.com/seek4science/seek/blob/bf33c73b14be7404d778a7d615df5e62663d76de/app/models/sample_attribute.rb#L26) also needs to be changed in this case.

**Comment by fbacall** [comment]
You could also check `sample_attribute.deferred_link_to_self` and if true, set the `linked_sample_type_id` to `self` in the form:

https://github.com/seek4science/seek/blob/85cdb92a1804b88729f03339153749b3efebe70b/app/views/sample_types/_sample_attribute_form.html.erb#L10

**Comment by vdkkia** [comment]
This solution seems much simpler. Thanks
