### ISSUE TITLE
Wrong Journal link if registering publication as DOI

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#829]
I have registered new publication https://fairdomhub.org/publications/638 using DOI , at the end under "Citation" field wrong journal is in the list (screen shot attached)

**Comment by OlgaKrebs** [comment]
![JIRA_journal](https://user-images.githubusercontent.com/55085007/148913175-5065d314-f1e6-4047-87da-fc4a09733d24.jpg)

**Comment by OlgaKrebs** [comment]
correct one would be  Analytical and Bioanalytical Chemistry, but it is not in the drop down list

**Comment by stuzart** [comment]
This is the citation format, not the journal that the item was published in.
Do you recommend a default citation format ?

**Comment by OlgaKrebs** [comment]
I see, may be it is good to label somehow the field e.g. "citation format", otherwise confusing.
I don't think we have to assign any format, may be "empty" as default and ask user to define.

**Comment by OlgaKrebs** [comment]
some formats produce crazy looking results - see screen shot

**Comment by OlgaKrebs** [comment]
![JIRA_journal2](https://user-images.githubusercontent.com/55085007/148935769-28a09cac-b627-4877-8eba-0f7a51704f73.jpg)

**Comment by OlgaKrebs** [comment]
Stuart, do you know why abstract by this publication is looking so strange? not as in original, different font and that strange frame.... and I can't edit it.

**Comment by OlgaKrebs** [comment]
there is another " Citation: Anal Bioanal Chem 413(30):7333-7340" field on the left, under abstract.... just to many citations?
