### ISSUE TITLE
Documentation reference to outdated compose file

### ISSUE THREAD

**Issue by Linus4** [seek4science/seek#841]
The SEEK [documentation for docker-compose](https://docs.seek4science.org/tech/docker/docker-compose.html) links to an outdated [raw compose file](https://raw.githubusercontent.com/seek4science/seek/seek-1.11/docker-compose.yml) which probably includes an old and vulnerable version of solr.

**Comment by stuzart** [comment]
The documentation points to the docker compose for the current stable release branch. The version of SOLR isn't affected as it uses and older version of log4j

**Comment by Linus4** [comment]
I see, thanks for the clarification!
