### ISSUE TITLE
Describe what Collections are for

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#850]
On the new collection page, add some brief text describing what Collections are, and link to the help page in the documentation

**Comment by abecam** [comment]
Got something working and generic (would allow solving #599). Feedback welcome:

<img width="884" alt="Screenshot 2022-02-16 at 10 08 29" src="https://user-images.githubusercontent.com/11572491/154249794-60af4d37-e5f4-4a6a-9409-2c18ad6b31f8.png">
<img width="884" alt="Screenshot 2022-02-16 at 10 08 48" src="https://user-images.githubusercontent.com/11572491/154249801-85469adf-14b6-4dfb-942e-bf057a8dd551.png">
<img width="748" alt="Screenshot 2022-02-16 at 10 12 17" src="https://user-images.githubusercontent.com/11572491/154249809-753fad7c-535f-4dfb-aba8-f9c72c25e9c7.png">

**Comment by OlgaKrebs** [comment]
I suggest to replace "things" by "assets" . Also " that don't belong to any other kind of hierarchy"   sounds like "put the rests toghether"  and is misleading, cause one can add to collection assets linked to ISA.  Can it be expressed in a positive way? like " to group assets which belongs together in users' eyes" -

**Comment by OlgaKrebs** [comment]
in a documentation we could write examples like e.g. "collection of project's SOPs ", "collection of project's templates"

**Comment by abecam** [comment]
The problem with asset us that assets are some specific elements in Seek, while collections accept others as well. A positive way would be great indeed. Any suggestion would be welcome. Maybe discuss it with the other CWs?

> I suggest to replace "things" by "assets" . Also " that don't belong to any other kind of hierarchy" sounds like "put the rests toghether" and is misleading, cause one can add to collection assets linked to ISA. Can it be expressed in a positive way? like " to group assets which belongs together in users' eyes" -

**Comment by floradanna** [comment]
**What is a Collection? _(info icon)_**
A collection is a group of SEEK items that are conceptually related to each other.

**Collections _(in the user guide page)_**
A collection is a group of SEEK items that are conceptually related to each other. Items within a collection can be ordered. 

SEEK items that can be part of a collection are:
- Assets (except other collections)
- Activities
- Samples

SEEK items that cannot be part of a collection are:
- Yellow pages
- Experiments
- Other collections

**Comment by OlgaKrebs** [comment]
sounds very good

**Comment by abecam** [comment]
Both updated.
