### ISSUE TITLE
Move the Add to Collection button to the Actions menu

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#852]
For this version, based on feedback, the Add to Collecton should be moved to the Actions menu

**Comment by abecam** [comment]
Actually the button lists the available collections, so it's not really replaceable by an item in the menu (or it will probably be less easy to use).

**Comment by abecam** [comment]
It is also not a privileged option, so should be there anyway (it's available also to anyone who can view).

**Comment by abecam** [comment]
Will need further investigations if we want to change.
