### ISSUE TITLE
Citation style selector improvements

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#88]
- [x] Show actual title for citation style/journal rather than the string ID.
- [x] Remember users selection and use that as the default when rendering future citations.
- [x] Allow searching the list, instead of having to scroll through all 1000+ styles.
- [ ] Add export formats: BibTeX, EndNote & .ris (maybe ?) with a button

**Comment by alaninmcr** [comment]
@fbacall What is the status of this?
