### ISSUE TITLE
Hide buttons in the Project overview that allow switching to Graph view

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#902]
The Graph overview is not useful for a Project. It would be better if the three options (Tree, Split and Graph) were hidden.

**Comment by floradanna** [comment]
Do you want to hide the "Overview" button (which by default brings you to Tree)?
I thought that files associated with project will be shown in the Overview-Tree for IBISBA (https://github.com/seek4science/seek/issues/788#issuecomment-1041541826). Aren't you gonna need the Overview button? Or maybe is this about something else?

**Comment by alaninmcr** [comment]
No. When you click Overview it would just show the Tree and not allow switching to the Graph nor splitting,

**Comment by stuzart** [comment]
I've clarified the title.
Don't hide the Full Screen button though
