### ISSUE TITLE
table view/data files - date of creation needed

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#920]
Please add "date of creation" to the list of attributes to choose to be shown in a table view for data files . I can sort them by date of creation, but can't see this date.  Is really important attribute to view

**Comment by stuzart** [comment]
completely agree - updated_at and created_at should be available on all items

**Comment by OlgaKrebs** [comment]
is there any progress with this? and other issues about table view attributes (reported more than year ago)?

**Comment by fbacall** [comment]
I think this was fixed in #1063 merged yesterday

**Comment by stuzart** [comment]
yes it's been fixed. I will close this
