### ISSUE TITLE
JS error on ISA graph

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#935]
Seems to happen on every show page
```
TypeError: ISA.originNode is null
```

```js
...
        }).on('dblclick.jstree', function (event) {
            var id = $j(event.target).closest('li').data('nodeId');
            var node = ISA.getNode(id);
            ISA.visitNode(node);
        }).on('redraw.jstree', function (event) {
            $j('li[data-node-id=' + ISA.originNode.data('id') + ']').each(function () {
                $j(this).addClass('isa-highlight');
            });
        });
```

**Comment by stuzart** [comment]
I can't reproduce this on the fairdomhub, trying out a few show pages including some Investigations with large trees. So I think this is post 1.12?

**Comment by alaninmcr** [comment]
This bug seems to have appeared in code that has not changed in four years. Any idea why?

**Comment by fbacall** [comment]
I've been seeing it a while. It happens if you view a page with the ISA tree view as the default view.
