### ISSUE TITLE
Segfault in tests

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#94]
Always seem to be to do with mailers.

https://travis-ci.org/seek4science/seek/jobs/604865639
https://travis-ci.org/seek4science/seek/jobs/595084416
https://travis-ci.org/seek4science/seek/jobs/591896619
https://travis-ci.org/seek4science/seek/jobs/591982667

From me on slack:
> https://github.com/mikel/mail/blob/master/lib/mail/parsers.rb#L3 this line triggers it
and the backtrace in the segfault mentions /home/travis/.rvm/rubies/ruby-2.4.9/bin/../lib/libruby.so.2.4(compile_array_+0x120) [0x7fcfc32b9310]
and if you look at the code for https://raw.githubusercontent.com/mikel/mail/master/lib/mail/parsers/address_lists_parser.rb it is full of huge arrays

**Comment by alaninmcr** [comment]
Good grief. What on Earth is that array for?

--
Alan

The University of Manchester belongs to the European R&D infrastructure IBISBA 1.0
The project has received funding from the European Union’s Horizon 2020
Research and Innovation Programme under grant agreement No 730976.
To find out more visit https://www.ibisba.eu
________________________________
