### ISSUE TITLE
Sample serialization has policy as a relationship

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#956]
In the JSON sample serialization, the policy is listed both as an attribute (which is correct) and as a relationship (which is not).

For example:

{
    "data": {
        "id": "109",
        "type": "samples",
        "attributes": {
            **"policy": {
                "access": "no_access",
                "permissions": [
                    {
                        "resource": {
                            "id": "76",
                            "type": "projects"
                        },
                        "access": "edit"
                    }
                ]
            }**,
            "discussion_links": null,
            "title": "The title",
            "attribute_map": {
                "a": "The title",
                "b": "A field"
            },
            "tags": null
        },
        "relationships": {
            "creators": {
                "data": [
                    {
                        "id": "1",
                        "type": "people"
                    }
                ]
            },
            "submitter": {
                "data": [
                    {
                        "id": "1",
                        "type": "people"
                    }
                ]
            },
            "projects": {
                "data": [
                    {
                        "id": "76",
                        "type": "projects"
                    }
                ]
            },
            "sample_type": {
                "data": {
                    "id": "9",
                    "type": "sample_types"
                }
            },
            "data_files": {
                "data": []
            },
            **"policy": {
                "data": {
                    "access": "no_access",
                    "permissions": [
                        {
                            "resource": {
                                "id": "76",
                                "type": "projects"
                            },
                            "access": "edit"
                        }
                    ]
                }
            },**
            "people": {
                "data": [
                    {
                        "id": "1",
                        "type": "people"
                    }
                ]
            }
        },
        "links": {
            "self": "/samples/109"
        },
        "meta": {
            "created": "2022-04-07T16:03:52.000Z",
            "modified": "2022-04-07T16:03:52.000Z",
            "api_version": "0.3",
            "uuid": "3e7c3050-98ba-013a-4fae-005056a4f69b",
            "base_url": "https://hub.ibisba.eu/"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}

**Comment by stuzart** [comment]
this doesn't appear to affect 1.12. May be caused by some refactoring, so moved to the maintenance board
