### ISSUE TITLE
Harmonize search, browse

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#972]
Browsing has filtering. This is not available for search. So a search limited to investigations gives a different result to browsing for investigations. This is confusing and unhelpful.

Similarly, the (for example) studies related to an investigation is a different interface to browsing studies and restricting to be in that investigation. This again is confusing and unhelpful.

We must rationalize the browsing, search, relate features.

**Comment by alaninmcr** [comment]
See https://docs.google.com/document/d/1BxQPakgebNs5ssrASHMbEVbPSQczUWey7nJviaFc9Ck/edit?usp=sharing

**Comment by rabuono** [comment]
Would be good to extend the harmonization to the DataHub Templates pages.
Templates show in the "Browse"menu:
![image](https://user-images.githubusercontent.com/77321541/174792499-fea7bfe9-0463-4154-af07-10cfe2e008d9.png)

**Comment by floradanna** [comment]
In FAIRDOMHub, I searched "gene" in Sample Types and I got 21 sample types as results, but
1. I don't see the word "gene" anywhere in the resulting sample types.
2. When I click "View all" I get "404 - The requested page or resource does not exist. You may have mistyped the address or the item may have been deleted."

<img width="1424" alt="Screenshot 2022-08-02 at 14 09 37" src="https://user-images.githubusercontent.com/51486716/182371239-a0c151fc-dcd0-47fd-be19-d7611384ffbc.png">

**Comment by alaninmcr** [comment]
I only got four sample types for gene. Three of them have gene(s) in the description. The other one has Genes as a field of the sample type. It looks OK for me.

**Comment by alaninmcr** [comment]
It affects more than sample types. Do a search for gene. I see 71 studies and when I click on View All, I get a 404. Same for Investigations, assays, data files, models, sops, presentations and documents.

It is *very* broken
