### ISSUE TITLE
Project join request with emails disabled

### ISSUE THREAD

**Issue by Linus4** [seek4science/seek#983]
**Describe the bug**

When you're not in a project, you land on `/home/create_or_join_project` and can request to join a project. If emails are disabled in admin settings a generic error page is displayed. (The button to request access to a project on the project page is hidden if emails are disabled.)

**Expected behavior**

The join request should go through without trying to send an email and project admins should receive a notification on the site. 

**Desktop (please complete the following information):**

any

**Additional context**

No information is displayed on the error page, so the admin has to look into the logs. Alternatively, the error page could say that this method of joining a project is not available and that a project admin has to add them manually.

**Comment by stuzart** [comment]
I also came across this recently. It used to be the email was necessary, but since the notification in the browser was added along with the new route to get to the page, this has become a bug
