### ISSUE TITLE
Ordering option is wrongly available

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#992]
The option to order items is shown even though the user does not have full permission.

**Comment by alaninmcr** [comment]
For example I supposedly cannot even see the investigations in https://fairdomhub.org/projects/106 but can order them :-O

**Comment by alaninmcr** [comment]
Similarly https://fairdomhub.org/projects/250 allows me to manage the project when I should not have the rights

**Comment by stuzart** [comment]
you're an administrator

**Comment by alaninmcr** [comment]
Found the underlying issue. Need to check that user can manage the resources being ordered.

Added code to do this to fairdomhub-992

Probably not the correct branch :)

**Comment by stuzart** [comment]
Does it make sense that the items being ordered need manage rights? I'd say it should be that just edit rights on the container that they are being ordered within is required?

Make sure you fix it off the seek-1.12 branch, no the fairdomhub branch.

**Comment by alaninmcr** [comment]
Bit confused now - though code is fairly easy to change.

Container -> edit?
Contained -> manage?

or do you want

Container -> edit
Contained -> any rights (possibly at least view)

**Comment by stuzart** [comment]
I'd say the 2nd case. This matches the rights for adding things to an Assay

**Comment by alaninmcr** [comment]
Changed to make edit (for container) and edit for contained.
